### ISSUE TITLE
Missing pinkie-2.0.5

### ISSUE THREAD

**Issue by tybor** [DeviaVir/zenbot#1081]
Zenbot failed "npm install" after a git pull 

- OS Linux Debian Stretch
- zenbot master branch
- node 8.2.1
- Python 2.7.13
- "git pull; npm install" 

npm install fails to complete. The most relevant error is

npm ERR! 404 Not Found: pinkie@https://registry.npmjs.org/pinkie/-/pinkie-2.0.5.tgz

I attach the comple npm log

[log.zip](https://github.com/DeviaVir/zenbot/files/1610271/log.zip)

**Comment by adrianocr** [comment]
@tybor it's an issue with an NPM package that was deleted: https://stackoverflow.com/questions/48131111/npm-err-404-not-found-pinkie-promise

You're not the only who has had issues with it in the past day or two.

**Comment by psi-4ward** [comment]
delete package-lock.json and retry npm install

**Comment by tybor** [comment]
Thank you. The workaround shown in that question wasn't effective. 
I ended up cloning https://github.com/floatdrop/pinkie locally and installing it from my local repo.

Now it seems I've encountered another show-stopper issue:

/home/paolo/zenbot/extensions/output/api.js:21
    const {[key]: deletedKey, ...otherKeys} = object;
                              ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/paolo/zenbot/extensions/output/_codemap.js:4:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /home/paolo/zenbot/boot.js:21:19
    at Array.forEach (native)
    at /home/paolo/zenbot/boot.js:20:15
    at f (/home/paolo/zenbot/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/paolo/zenbot/node_modules/glob/glob.js:151:7)

**Comment by DeviaVir** [comment]
Please use the `unstable` branch for now, and update your node to at least 8.3.0

**Comment by tybor** [comment]
Thanks DeviaVir, unstable runs smoothly!
