### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by nicolinux** [DeviaVir/zenbot#115]
Hey guys,

this is my very first attempt to get Zenbot to run. I am pretty new to it and I don't understand all concepts. I am using this docker image: [barnumd/zenbot](https://hub.docker.com/r/barnumd/zenbot/)

I left the config.js as it is (well I copied and renamed it of course).

This is the output I get:
```
02/17/2017 11:12:06 PM UTC [    launcher] cmd `launch` booting
02/17/2017 11:12:06 PM UTC [    launcher] cmd `launch` booting
02/17/2017 11:12:06 PM UTC [    launcher] cmd `launch` booting
02/17/2017 11:12:08 PM UTC [    launcher] cmd `reduce` booting
02/17/2017 11:12:08 PM UTC [    launcher] cmd `run` booting
02/17/2017 11:12:08 PM UTC [    launcher] cmd `map` booting
02/17/2017 11:12:08 PM UTC [      runner] starting
/usr/src/zenbot/utils/get_products.js:6
      if (c.assets.indexOf(product.asset) === -1) return false
                  ^

TypeError: Cannot read property 'indexOf' of undefined
    at /usr/src/zenbot/utils/get_products.js:6:19
    at Array.filter (native)
    at get_products (/usr/src/zenbot/utils/get_products.js:5:23)
    at mapper (/usr/src/zenbot/plugins/gdax/backfiller.js:12:20)
    at /usr/src/zenbot/node_modules/run-parallel/index.js:41:7
    at Array.forEach (native)
    at module.exports (/usr/src/zenbot/node_modules/run-parallel/index.js:40:11)
    at mapper (/usr/src/zenbot/node_modules/zenbrain/core/mapper/mapper.js:9:5)
    at Object.<anonymous> (/usr/src/zenbot/node_modules/zenbrain/core/launcher/launcher.js:76:11)
    at Immediate.<anonymous> (/usr/src/zenbot/node_modules/sosa/api.js:15:12)
02/17/2017 11:12:08 PM UTC [    launcher] cmd `map` exited with code 1, respawning now.
02/17/2017 11:12:08 PM UTC [    launcher] cmd `server` booting
02/17/2017 11:12:08 PM UTC [      server] zenbot/3.5.16 booted!
02/17/2017 11:12:08 PM UTC [      server] open http://localhost:3013/?secret=xxx to see a live graph.
02/17/2017 11:12:10 PM UTC [    launcher] cmd `map` booting
```

To me it looks like it chokes on this bit from the config:
```
// watch these exchanges
c.watch_exchanges = [
  //"bitfinex",
  "gdax",
//  "kraken",
//  "poloniex",
]
```

But why?

**Comment by levibe** [comment]
I'm getting the same error. Fresh install.

Using latest Node lts, 6.10.0, and npm 3.10.10.

**Comment by carlosfvp** [comment]
the config.js requires to define currencies and assets

```
c.assets = [
  "BTC"
c.currencies = [
  "ETC"
]
```

**Comment by carlos8f** [comment]
Cleaning up 3.x issues
