### ISSUE TITLE
GDAX Error 'Order size is too small. Minimum size is 0.001'

### ISSUE THREAD

**Issue by micheledicosmo** [DeviaVir/zenbot#1158]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:
vanilla
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04 running on AWS
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```
- **Zenbot version**:
```
./zenbot.sh --version
4.1.0
```
on commit a656e95683153dd9e0254ddb69dea641c8869cd6
- **NodeJS version**: 
```
node --version
v8.9.4
```
- **Python version**:
```
python --version
Python 2.7.12
```
- **Exact command to reproduce**:
`./zenbot.sh trade --strategy=stddev`

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in Zenbot or a feature request.

trading on GDAX with ~92 GBP left (started with 100 GBP)
bot tried trading an amount > 0.001 BTC yet GDAX returns the following inconsistent error
bot stops trading with this error in loop:
```
GDAX API is down! unable to call sell, retrying in 10s
{ Error: non-200 status: 400
    at statusErr (/home/ubuntu/zenbot/extensions/exchanges/gdax/exchange.js:65:17)
    at /home/ubuntu/zenbot/extensions/exchanges/gdax/exchange.js:273:25
    at Request._callback (/home/ubuntu/zenbot/node_modules/gdax/lib/clients/public.js:53:9)
    at Request.self.callback (/home/ubuntu/zenbot/node_modules/gdax/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ubuntu/zenbot/node_modules/gdax/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/zenbot/node_modules/gdax/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'HTTP_STATUS',
  body: { message: 'Order size is too small. Minimum size is 0.001' } }
[ { price: '8022.79',
    size: '0.00011056',
    orig_size: '0.00011056',
    remaining_size: '0.00011056',
    orig_price: '8022.79',
    cancel_after: 'day',
    product_id: 'BTC-GBP',
    post_only: true,
    time_in_force: 'GTT',
    side: 'sell' } ]
```

Might be related to #900 and #370

**Comment by firepol** [comment]
I think that this was resolved just an hour ago by this commit: https://github.com/DeviaVir/zenbot/commit/80b6f7d951b931307fdbcbc1affd1652cd39c082 (Exchanges: update-products 194 )

@micheledicosmo try to pull in order to update your repo, it should work now. The minimum size for BTC-GBP was updated to 0.001 (instead of 0.0001, which created the error)

**Comment by DeviaVir** [comment]
yay for automation (if it indeed solved this) 👍

**Comment by firepol** [comment]
Judging from the error above, the log and checking the commit, I'm confident it's solved.

**Comment by micheledicosmo** [comment]
haven't seen it since the pull :) thanks you all :)
