### ISSUE TITLE
Problem with Bittrex exchange.js:113

### ISSUE THREAD

**Issue by sembsa** [DeviaVir/zenbot#1170]
### System information
- **macOS 10.13.2**:
- **Zenbot 4.1.0**:
- **NodeJS 9.3.0**: 
- **Python 2.7.14**:
- **zenbot trade bittrex.ETH-BTC **:

### Describe the problem
Program error condition after one hour of work.

### Source code / logs
zenbot/extensions/exchanges/bittrex/exchange.js:113
        if(!data.success) {
                 ^

TypeError: Cannot read property 'success' of null
    at /Users/sembsa/Desktop/zenbot/extensions/exchanges/bittrex/exchange.js:113:18
    at Request._callback (/Users/sembsa/Desktop/zenbot/node_modules/node.bittrex.api/node.bittrex.api.js:127:11)
    at self.callback (/Users/sembsa/Desktop/zenbot/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at ClientRequest.<anonymous> (/Users/sembsa/Desktop/zenbot/node_modules/request/request.js:785:18)
    at Object.onceWrapper (events.js:254:19)
    at ClientRequest.emit (events.js:159:13)
    at TLSSocket.emitTimeout (_http_client.js:710:34)
    at Object.onceWrapper (events.js:254:19)
    at TLSSocket.emit (events.js:159:13)
    at TLSSocket.Socket._onTimeout (net.js:421:8)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

**Comment by station384** [comment]
This fix for this has been merged into the unstable branch.
