### ISSUE TITLE
Kraken API rate limit exceeded

### ISSUE THREAD

**Issue by tybor** [DeviaVir/zenbot#1172]
### System information
- zenbot vanilla 
- Linux Debian 9
- **Zenbot version**: unstable, freshly pulled from repo
- **NodeJS version**:  v8.9.4
- **Python version**: Python 2.7.13
- **Exact command to reproduce**:  ./zenbot.sh trade kraken.DASH-ZEUR --strategy=forex_analytics --manual --period=5m --modelfile=models/current.DASH-ZEUR.json

### Describe the problem
Automated trading with forex analytics and period 5 minutes often hits Kraken API limit. 
If API rate limit is exceeded during startup the program quits without any trade

### Source code / logs

getBalance error:
Error: Kraken API returned error: API:Rate limit exceeded
    at Request._callback (/home/paolo/zenbot-unstable/node_modules/kraken-api/kraken.js:155:34)
    at Request.self.callback (/home/paolo/zenbot-unstable/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/paolo/zenbot-unstable/node_modules/request/request.js:1060:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/paolo/zenbot-unstable/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
/home/paolo/zenbot-unstable/commands/trade.js:406
                    throw err
                    ^

Error: Kraken API returned error: API:Rate limit exceeded
    at Request._callback (/home/paolo/zenbot-unstable/node_modules/kraken-api/kraken.js:155:34)
    at Request.self.callback (/home/paolo/zenbot-unstable/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/paolo/zenbot-unstable/node_modules/request/request.js:1060:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/paolo/zenbot-unstable/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by CloudyMountain** [comment]
same concern here...I was also looking at the code and try to lower the frequency to send the getBalance request, but didn't find the variable yet. Could someone help us to locate this frequency variable? Many thanks!

**Comment by CloudyMountain** [comment]
Also I don't think this is zenbot's problem, my bot had been running for months without problem, and this error only occurs after the notoriously long update of Kraken weeks ago.

**Comment by CloudyMountain** [comment]
@tybor you can try doubling all the time-related parameters in conf.js, and see if it solves the problem.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖

**Comment by tybor** [comment]
I was able to avoid subscribing to reddit until now as every active subscription actually require time and time is my most scarce and precious resource. 
It seems I'll need to subscribe to reddit... :)
