### ISSUE TITLE
Bittrex 'URL request error'

### ISSUE THREAD

**Issue by station384** [DeviaVir/zenbot#1218]
Version: Unstable

Discovered an occasional condition 'URL request error'

This error is mostly a recoverable error, but sometimes its  not.  Not sure how to handle it and looking for input.

This can happen when 
1.  The exchange api goes down temporary
2.  Your system running zenbot looses its DNS, or can't query DNS.
3.  You lose internet
4.  The exchange is gone, domain is gone

1 is usually temporary, and the next call will go thru.
2 should be temporary unless there is something wrong with the dns server, and its backup
3 hopefully temporary :)
4 yeah.... hopefully its temporary. 

The current functionality is to exit out of zenbot on this error,  but looking at these, I think we should just let it keep retrying.  

Thoughts?

**Comment by brucetus** [comment]
Agreed

**Comment by XarImoR** [comment]
URL request error                                                                  
/home/ubuntu/zenbot/commands/trade.js:512
                throw new Error('Error during syncing balance. Please check your API-Key')
                ^

Error: Error during syncing balance. Please check your API-Key
    at /home/ubuntu/zenbot/commands/trade.js:512:23
    at /home/ubuntu/zenbot/lib/engine.js:276:11
    at /home/ubuntu/zenbot/extensions/exchanges/bittrex/exchange.js:195:9
    at Request._callback (/home/ubuntu/zenbot/node_modules/node-bittrex-api/node.bittrex.api.js:143:11)
    at Request.self.callback (/home/ubuntu/zenbot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ubuntu/zenbot/node_modules/request/request.js:1060:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/zenbot/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

have the same issue...and no clue to catch it
