### ISSUE TITLE
Filter failure: MIN_NOTIONAL

### ISSUE THREAD

**Issue by Rutinguer** [DeviaVir/zenbot#1238]
Latest Version
Strategy Neural

Sorry for my english
After sell the bot still triying sell more and this is the problem. I have reset the bot and start again. I cant leave bot working alone

```
An error occurred { Error: binance order cost = amount * price should be > (0.001 BTC or 0.01 ETH or 1 BNB or 1 USDT){"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
    at binance.handleErrors (/home/borja/zenbot/node_modules/ccxt/js/binance.js:790:23)
    at response.text.then.text (/home/borja/zenbot/node_modules/ccxt/js/base/Exchange.js:443:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidOrder] }
```
***Now is 0.002 BTC minimum on binance** where can change this?

I just change this for the minimum order, and works but i guess this is not the best fix

 {
    "id": "IOSTBTC",
    "asset": "IOST",
    "currency": "BTC",
    **"min_size": "1000.00000000",**
    "max_size": "100000.00000000",
    "increment": "1.00000000",
    "label": "IOST/BTC"
  },

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/1516

**Comment by Rutinguer** [comment]
@kroitorThanks. Im waiting until this will fix
If i understand all is binance  api problem, right?

**Comment by kroitor** [comment]
> If i understand all is binance api problem, right?

Not really, it's telling you that the order that is being placed is too small, and this isn't a problem in Binance or ccxt, more like a problem in the decision logic that calculates the amount and the price of the order. The calculated values have to satisfy exchanges rules. This can be fixed within zenbot. I was just posting info for developers to help them fix it quicker and easier.

P.S. I would also recommend you to update the ccxt module, as your version is quite old.

**Comment by Rutinguer** [comment]
@kroitor My temporal soultion was change in "products" the min size ( more than 0.002 ) and "works"

How can do that easy? Im a little bit noob yet

**Comment by Rutinguer** [comment]
@kroitor updated ccxt now. Should be work fine now?

I clone into node folder from new

**Comment by kroitor** [comment]
@Rutinguer 

> updated ccxt now.

Cool!

> Should be work fine now?

No, not necessarily. It may still not work, unless the authors of zenbot fix it in their code that does submit orders to binance for it to account for the limits (those are described in [official Binance docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#filters)).

You see, I'm not the author nor a developer of zenbot. So, I can't really help you fix the problem with it. The only thing I can do for you is to give the developers a hint on how they should be fixing it (I already did that above). But until the devs fix it, I'm afraid, this will not work fine.

**Comment by Rutinguer** [comment]
@kroitor 
After updtate cant work with binance

An error occurred { Error: binance GET https://api.binance.com/api/v1/aggTrades?symbol=TRXETH&startTime=1517107157521&endTime=1517110757521&limit= 400 Bad Request {"code":-1105,"msg"**:"Parameter 'limit' was was empty."}** (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
    at binance.defaultErrorHandler (/home/xxx/zenbot/node_modules/ccxt/js/base/Exchange.js:412:15)
    at response.text.then.text (/home/xxx/zenbot/node_modules/ccxt/js/base/Exchange.js:428:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) constructor: [Function: ExchangeNotAvailable] }

**Comment by kroitor** [comment]
@Rutinguer then just restore the version that comes with zenbot. A clean reinstall usually fixes that easily. Yet still, the problem won't be fixed until it is fixed in the zenbot source.

**Comment by Rutinguer** [comment]
@kroitor Still no working. Maybe because the latest version binance https://github.com/ccxt/ccxt/blob/master/js/binance.js have diferent things than the older in zenbot

I have 2 folders , zenbot like you can found here and other with ccxt and other modules updated

With the older versions works ( with error  MIN_NOTIONAL ) the only way i found for trade with the bot was change "min_size": with a value above 0.002. 
How would you do?

Thanks for all


Edit : I changed only Binance.js and It seems to work well,but not with the last version

**Comment by Rutinguer** [comment]
Me again .. @kroitor  

Im using normal zenbot with this https://github.com/ccxt/ccxt/pull/1222 and It seems to work wel
