### ISSUE TITLE
Error backfilling with Kraken

### ISSUE THREAD

**Issue by simclem77** [DeviaVir/zenbot#1285]
I've an issue with backfilling with exchange Kraken.
When I use the command zenbot backfill kraken.XXBT-ZEUR --days 30 I've this message 👍 

> 35 trades processed so far. The mose recently processed trade happened 4 minutes ago.
> 
> final trade id ==> [undefined]

and trades are not backfilled.

If I ask again few seconds after the number of trades is less than first time.
If I wait more time, the number of trade is higher but still same erreur (final trade id ==> [undefined])

**Comment by rondijkstra** [comment]
Hi, 
I'm facing the same issue.. My syntax: zenbot backfill poloniex.burst-btc 
This is the syntax I've been using forever. 
I did try a --paper trade with two different coins. Did I stress Polo out?

**Comment by simclem77** [comment]
@rondijkstra Just in case, there was another issue with backfilling (#1292) which was fixed with updating zenbot to last version. It fixes this issue with Kraken at the same time.

**Comment by rondijkstra** [comment]
What's the correct syntax in that? git pull ? Any additions?

**Comment by vadzen** [comment]
I used with master branch next command without issues:
`./zenbot.sh backfill --conf conf-kraken-XETH-ZUSD.js --days 30`
I have issue after switching to unstable branch with the same command:
`module.js:540
    throw err;
    ^
Error: Cannot find module 'lolex'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/zenbot/lib/engine.js:14:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)`
