### ISSUE TITLE
ERROR on Learner ../zenbot/poloniex_logic.js:142

### ISSUE THREAD

**Issue by nozyqubis** [DeviaVir/zenbot#129]
Hello Everyone,
I have tried and search for fixing this issue but until now i didnt succeed it.Is there any solution on this error?

/home/alpha/zenbot/poloniex_logic.js:142
          get('logger').learn('learner', (('No learned params to load, using default settings.').yellow))
                        ^

TypeError: get(...).learn is not a function
    at /home/alpha/zenbot/poloniex_logic.js:142:25
    at doNext (/home/alpha/zenbot/node_modules/zenbrain/utils/apply_funcs.js:10:12)
    at apply_funcs (/home/alpha/zenbot/node_modules/zenbrain/utils/apply_funcs.js:19:7)
    at tick_handler (/home/alpha/zenbot/node_modules/zenbrain/core/runner/tick_handler.js:24:5)
    at doNext (/home/alpha/zenbot/node_modules/zenbrain/utils/apply_funcs.js:10:12)
    at apply_funcs (/home/alpha/zenbot/node_modules/zenbrain/utils/apply_funcs.js:19:7)
    at runner (/home/alpha/zenbot/node_modules/zenbrain/core/runner/runner.js:4:5)
    at Array.task (/home/alpha/zenbot/node_modules/zenbrain/core/actions/run.js:47:17)
    at module.exports (/home/alpha/zenbot/node_modules/run-series/index.js:20:33)
    at Object.<anonymous> (/home/alpha/zenbot/node_modules/zenbrain/core/actions/run.js:53:13)

**Comment by laoyaoshine** [comment]
[ERROR] poloniex non-200 status: 403

**Comment by carlos8f** [comment]
Cleaning up 3.x issues.
