### ISSUE TITLE
Localhost site crashes server process on Windows

### ISSUE THREAD

**Issue by xangma** [DeviaVir/zenbot#13]
Hi,

After just updating to your v3.0.2 and rebuilding /data/db, everything is working fine (expect still requiring cross-spawn on Windows), but when I go to load the localhost website it gives me this error:

```
08/14/2016 10:37:14 PM BST [      server] open http://localhost:3013/?secret=dc3d5ed33f476e8e to see a live graph.
D:\zenbot-3.x\node_modules\motley-templ\node_modules\templ\index.js:48
        if (typeof file === 'undefined') throw new Error('template not found: ' + p);
                                         ^

Error: template not found: home
    at render (D:\zenbot-3.x\node_modules\motley-templ\node_modules\templ\index.js:48:48)
    at ServerResponse.res.render (D:\zenbot-3.x\node_modules\motley-templ\node_modules\templ\index.js:70:23)
    at Runner.<anonymous> (D:\zenbot-3.x\plugins\server\controllers\home.js:11:11)
    at Immediate.nextRoute [as _onImmediate] (D:\zenbot-3.x\node_modules\motley\node_modules\middler\node_modules\bladerunner\index.js:51:23)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
 08/14/2016 10:37:14 PM BST [    launcher] cmd `server` exited with code 1, respawning now.
08/14/2016 10:37:17 PM BST [    launcher] cmd `server` booting
```

I can't figure it out myself sorry, so I thought I'd report it.

**Comment by carlos8f** [comment]
hmm, looks like my templating library is failing on windows. not surprising, I don't test on windows at all. I recommend running this on a linux docker container or mac instead.

**Comment by ghostnegotiator** [comment]
Heya, just updated and currently on my mobile phone (SSH FTW!). Bot seems
to be running smoothly. Although it would be verry pleasent to have
config.js moved to sample-config.js (one for Euro and one for USD). I wilk
report back as soon as possible.

There are a few things I am really hoping for like:
- BTC-ETH Trading (GDAX)
- Euro/USD (Seperated configs)
- Config renamed to sample-eur-config.js. (example)
- config.js added to .gitignore (saves trouble!)

Next to that this is some great stuff!

Yours Faithfully,
RDash

**Comment by ghostnegotiator** [comment]
Whoops, replied to the wrong mail :')

**Comment by ghostnegotiator** [comment]
_http_outgoing.js:399                                                                                  throw new Error('Can\'t render headers after they are sent to the client');
    ^  
Error: Can't render headers after they are sent to the client
    at ServerResponse.OutgoingMessage._renderHeaders (_http_outgoing.js:399:11)                        at ServerResponse.writeHead (_http_server.js:184:20)
    at ServerResponse.res.renderStatus (/home/gekko/zenbot/node_modules/templ/index.js:83:13)          at Object.<anonymous> (/home/gekko/zenbot/plugins/server/controllers/data.js:17:37)
    at Immediate.<anonymous> (/home/gekko/zenbot/node_modules/sosa/api.js:15:12)
    at runCallback (timers.js:570:20)                                                                  at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback](timers.js:529:5)                                  08/15/2016 12:06:38 AM CEST [    launcher] cmd `server` exited with code 1, respawning now.

Linux too apparently

**Comment by carlos8f** [comment]
@RDash21 just published 3.0.3 which should resolve that.

**Comment by ghostnegotiator** [comment]
Pulled & did not crash when attempting to break it. Great job!

**Comment by xangma** [comment]
@carlos8f Ah that's fair enough. A sell signal didn't execute either when running under Windows so I've not set up a virtual machine to run it on Ubuntu instead.
