### ISSUE TITLE
An error occurred RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sasasavic82** [DeviaVir/zenbot#1314]
--------------------------------------- STARTING LIVE TRADING ----------------------------------------
Press  l  to list available commands.
Web GUI running on http://0.0.0.0:20068/
2018-02-10 00:46:00  0.100613 ETH-BTC               319                               0.00033000 ETH  0.21824758 BTC   +0.00%   -0.09%
2018-02-10 00:48:00  0.100495 ETH-BTC   -0.12%      520                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.02%
2018-02-10 00:50:00  0.100357 ETH-BTC   -0.14%      360                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.16%
2018-02-10 00:52:00  0.100358 ETH-BTC   +0.00%      407                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.16%
2018-02-10 00:54:00  0.100358 ETH-BTC   +0.00%      341                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.16%
2018-02-10 00:56:00  0.100358 ETH-BTC   +0.00%      435                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.16%
2018-02-10 00:58:00  0.100258 ETH-BTC   -0.10%      386                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.26%
2018-02-10 01:00:00  0.100187 ETH-BTC   -0.08%      304                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.33%
2018-02-10 01:02:00  0.100379 ETH-BTC   +0.19%      502                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.14%
2018-02-10 01:04:00  0.100512 ETH-BTC   +0.13%      539                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.01%
2018-02-10 01:06:00  0.100483 ETH-BTC   -0.03%      350                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.04%
2018-02-10 01:08:00  0.100325 ETH-BTC   -0.16%      298                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.19%
2018-02-10 01:10:00  0.100037 ETH-BTC   -0.29%      653                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.48%
2018-02-10 01:12:00  0.100196 ETH-BTC   +0.15%      418                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.32%
2018-02-10 01:14:00  0.099984 ETH-BTC   -0.22%      346                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.54%
2018-02-10 01:16:00  0.100035 ETH-BTC   +0.05%      300                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.48%
2018-02-10 01:18:00  0.100037 ETH-BTC   +0.00%      358                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.48%
2018-02-10 01:20:00  0.099981 ETH-BTC   -0.06%      377                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.54%
2018-02-10 01:22:00  0.099967 ETH-BTC   -0.02%      276                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.55%
2018-02-10 01:24:00  0.099966 ETH-BTC   -0.01%      258                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.55%
2018-02-10 01:26:00  0.100032 ETH-BTC   +0.06%      234                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.49%
2018-02-10 01:28:00  0.099918 ETH-BTC   -0.12%      485                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.60%
2018-02-10 01:30:00  0.099827 ETH-BTC   -0.10%      378                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.69%
2018-02-10 01:32:00  0.099897 ETH-BTC   +0.07%      370                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.62%
2018-02-10 01:34:00  0.100027 ETH-BTC   +0.13%      419                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.49%
2018-02-10 01:36:00  0.099949 ETH-BTC   -0.08%      314                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.57%
2018-02-10 01:38:00  0.099924 ETH-BTC   -0.03%      324                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.60%
2018-02-10 01:40:00  0.099769 ETH-BTC   -0.16%      250                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.75%
2018-02-10 01:42:00  0.099754 ETH-BTC   -0.02%      480                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.77%
2018-02-10 01:43:59  0.099800 ETH-BTC   +0.04%      406                               0.00033000 ETH  0.21824758 BTC   -0.01%   +0.72%An error occurred RangeError: Maximum call stack size exceeded
    at each (/home/ubuntu/zenbot/node_modules/run-series/index.js:14:17)
    at Array.<anonymous> (/home/ubuntu/zenbot/lib/engine.js:864:20)
    at each (/home/ubuntu/zenbot/node_modules/run-series/index.js:17:24)
    at Array.<anonymous> (/home/ubuntu/zenbot/lib/engine.js:864:20)
    at each (/home/ubuntu/zenbot/node_modules/run-series/index.js:17:24)
    at Array.<anonymous> (/home/ubuntu/zenbot/lib/engine.js:864:20)
    at each (/home/ubuntu/zenbot/node_modules/run-series/index.js:17:24)
    at Array.<anonymous> (/home/ubuntu/zenbot/lib/engine.js:864:20)
    at each (/home/ubuntu/zenbot/node_modules/run-series/index.js:17:24)
    at Array.<anonymous> (/home/ubuntu/zenbot/lib/engine.js:864:20)
An error occurred RangeError: Maximum call stack size exceeded

**Comment by Shawn8901** [comment]
Looks like #1299 ?

**Comment by defkev** [comment]
Is this also on Binance?

**Comment by sasasavic82** [comment]
yep binance. latest code i pulled yesterday.

**Comment by defkev** [comment]
Does it work if you revert the changeset as mentioned in https://github.com/DeviaVir/zenbot/issues/1299#issuecomment-363981818
