### ISSUE TITLE
./zenbot sim [--verbose]  Error

### ISSUE THREAD

**Issue by ph0rest** [DeviaVir/zenbot#132]
Hello! 

I'm trying to run simulation and receive this error.

```
./zenbot sim [--verbose]

04/12/2017 11:40:35 PM EEST [    launcher] cmd `sim` booting
/Users/pro/zenbot/node_modules/zenbrain/core/actions/sim.js:17
      throw new Error('unknown arg')
      ^

Error: unknown arg
    at sim (/Users/pro/zenbot/node_modules/zenbrain/core/actions/sim.js:17:13)
    at Object.<anonymous> (/Users/pro/zenbot/node_modules/zenbrain/core/launcher/launcher.js:76:11)
    at Immediate.<anonymous> (/Users/pro/zenbot/node_modules/sosa/api.js:15:12)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

But if type ./run.sh command bot works fine.
Any suggestions?

**Comment by ph0rest** [comment]
I tried to run Simulation from different computers and  MacOs.. Error is the same :(

Node.js v6.10.2 and npm v3.10.10 

Please help!

**Comment by papacasper** [comment]
The command for sim with verbose is `./zenbot sim --verbose` without the brackets

**Comment by carlos8f** [comment]
cleaning up 3.x issues
