### ISSUE TITLE
--use_prev_trades stopped to work after `Remove sosa-mongo, run-parallel dependencies (#1305)`

### ISSUE THREAD

**Issue by illya13** [DeviaVir/zenbot#1325]
`unstable` branch

after merge of 
`Remove sosa-mongo, run-parallel dependencies (#1305)`

on
```
node zenbot.js trade ... --use_prev_trades --reset_profit
```

I started to have
```
TypeError: my_trades.select is not a function
    at commands/trade.js:403:25
    at args.push (/home/ubuntu/zenbot/node_modules/mongodb/lib/utils.js:404:72)
    at handleCallback (/home/ubuntu/zenbot/node_modules/mongodb/lib/utils.js:128:55)
    at self.close (/home/ubuntu/zenbot/node_modules/mongodb/lib/cursor.js:934:60)
    at handleCallback (/home/ubuntu/zenbot/node_modules/mongodb/lib/utils.js:128:55)
    at completeClose (/home/ubuntu/zenbot/node_modules/mongodb/lib/cursor.js:1073:14)
    at Cursor.close (/home/ubuntu/zenbot/node_modules/mongodb/lib/cursor.js:1086:10)
    at /home/ubuntu/zenbot/node_modules/mongodb/lib/cursor.js:934:21
    at handleCallback (/home/ubuntu/zenbot/node_modules/mongodb-core/lib/cursor.js:178:5)
    at setCursorDeadAndNotified (/home/ubuntu/zenbot/node_modules/mongodb-core/lib/cursor.js:545:3)
```

CC @DeviaVir @krystophv

**Comment by illya13** [comment]
👍 
thx
