### ISSUE TITLE
GDAX: Invalid pagination before range

### ISSUE THREAD

**Issue by mpskovvang** [DeviaVir/zenbot#1410]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian, Docker version 17.12.0-ce
- **Zenbot version**: unstable branch
- **NodeJS version**: 
- **Python version**:
- **Exact command to reproduce**: zenbot trade --paper --debug

### Describe the problem
Pagination seems broken in GDAX exchange. Looks like timestamp is used as `before` parameter but last seen product id should be used instead?

Backfill uses product id with `after` parameter.

### Source code / logs
server_1   | fetching pre-roll data:
server_1   | getproducttrades call {}
server_1   | websocket connection to BTC-EUR opened
server_1   | 
server_1   | gdax.BTC-EUR saved 100 trades 1 days left
server_1   | getproducttrades call { after: 12459847 }

...

server_1   | ------------------------------------------ INITIALIZE  OUTPUT ------------------------------------------
server_1   | ---------------------------------------- STARTING PAPER TRADING ----------------------------------------
server_1   | !!! Paper mode enabled. No real trades are performed until you remove --paper from the startup command.
server_1   | Press  l  to list available commands.
server_1   | getproductticker call
server_1   | Web GUI running on http://0.0.0.0:20008/
server_1   | **getproducttrades call { before: 1519395162356 }**
server_1   | websocket connection to BTC-EUR opened
server_1   | { Error: non-200 status: 400
server_1   |     at statusErr (/app/extensions/exchanges/gdax/exchange.js:114:17)
server_1   |     at /app/extensions/exchanges/gdax/exchange.js:232:25
server_1   |     at Request._callback (/app/node_modules/gdax/lib/clients/public.js:64:9)
server_1   |     at Request.self.callback (/app/node_modules/gdax/node_modules/request/request.js:188:22)
server_1   |     at emitTwo (events.js:126:13)
server_1   |     at Request.emit (events.js:214:7)
server_1   |     at Request.<anonymous> (/app/node_modules/gdax/node_modules/request/request.js:1171:10)
server_1   |     at emitOne (events.js:116:13)
server_1   |     at Request.emit (events.js:211:7)
server_1   |     at IncomingMessage.<anonymous> (/app/node_modules/gdax/node_modules/request/request.js:1091:12)
server_1   |     at Object.onceWrapper (events.js:313:30)
server_1   |     at emitNone (events.js:111:20)
server_1   |     at IncomingMessage.emit (events.js:208:7)
server_1   |     at endReadableNT (_stream_readable.js:1055:12)
server_1   |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
server_1   |     at process._tickCallback (internal/process/next_tick.js:180:9)
server_1   |   code: 'HTTP_STATUS',
server_1   |   body: { message: 'Invalid pagination before range' } }

**Comment by mpskovvang** [comment]
Perhaps the getproducttrades call should store the cb-after and cb-before response headers. Alternately the most recent id from db should be used.

I've just started using this awesome project so I haven't figured out the relations between methods calls yet.

**Comment by mpskovvang** [comment]
I traced the code and found that the timestamp is coming from [commands/trade.js:408](https://github.com/DeviaVir/zenbot/blob/unstable/commands/trade.js#L408).

_Edited_: After a lot debugging I finally realized the backfiller is updating the same `trade_cursor` 
 variable (https://github.com/DeviaVir/zenbot/blob/unstable/commands/trade.js#L525).

Without any further understanding of the code I believe the backfiller should use a local scoped `trade_cursor` variable preventing modification of the gdax exchange `trade_cursor` variable?

_Updated_: Testing a bit more it seems the `s.exchange` gets overriden. In the beginning the `s.exchange.name` is gdax but after `engineFactory` it changes to sim exchange. It appears to be related to this recent commit #1405 (https://github.com/DeviaVir/zenbot/pull/1405/files/37da340fdf0f1608083b920f258c0a3614c73557#diff-a41b519e7979a713e894ef8d1b3fe568R24)

**Comment by mpskovvang** [comment]
I just tried to checkout commit bbacc1fc98dd85efa8917f2f0550e7f110394091 (the one right before #1405) and the issue disapperaed.

**Comment by mpskovvang** [comment]
#1429 fixes this issue.
