### ISSUE TITLE
ypeError: s.exchange.getTime is not a function

### ISSUE THREAD

**Issue by araviel** [DeviaVir/zenbot#1424]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu
- **Zenbot version**: 4.1 (with latest pull at this time)
- **NodeJS version**: latest
- **Python version**: latest
- **Exact command to reproduce**: ./zenbot.sh trade --strategy dema --period 30m bitfinex.iot-usd

### Describe the problem
this error come after some hours of live trading on iot-usd bitfinex

### Source code / logs
2018-02-24 23:30:00  1.71160 IOT-USD   +0.61%    86582   55.17 ++   +00.0001      55      buy  1.15107663 IOT  196.44 USD   +0.01%   -1.35%
/home/osboxes/zenbot/lib/engine.js:659
      return s.exchange.getTime()
                        ^

TypeError: s.exchange.getTime is not a function
    at now (/home/osboxes/zenbot/lib/engine.js:659:25)
    at /home/osboxes/zenbot/lib/engine.js:313:26
    at Object.trade (/home/osboxes/zenbot/extensions/exchanges/bitfinex/exchange.js:476:14)
    at Object.buy (/home/osboxes/zenbot/extensions/exchanges/bitfinex/exchange.js:480:16)
    at placeOrder (/home/osboxes/zenbot/lib/engine.js:284:21)
    at doOrder (/home/osboxes/zenbot/lib/engine.js:521:7)
    at /home/osboxes/zenbot/lib/engine.js:457:17
    at /home/osboxes/zenbot/lib/engine.js:325:7
    at Object.getQuote (/home/osboxes/zenbot/extensions/exchanges/bitfinex/exchange.js:384:7)
    at getQuote (/home/osboxes/zenbot/lib/engine.js:322:16)
    at /home/osboxes/zenbot/lib/engine.js:376:7
    at /home/osboxes/zenbot/lib/engine.js:259:9
    at Object.getQuote (/home/osboxes/zenbot/extensions/exchanges/bitfinex/exchange.js:384:7)
    at /home/osboxes/zenbot/lib/engine.js:248:18
    at Object.getBalance (/home/osboxes/zenbot/extensions/exchanges/bitfinex/exchange.js:379:9)
    at syncBalance (/home/osboxes/zenbot/lib/engine.js:245:16)
    at executeSignal (/home/osboxes/zenbot/lib/engine.js:372:5)
    at /home/osboxes/zenbot/lib/engine.js:967:13
    at Object.onPeriod (/home/osboxes/zenbot/extensions/strategies/dema/strategy.js:62:5)
    at onTrade (/home/osboxes/zenbot/lib/engine.js:961:27)
    at /home/osboxes/zenbot/lib/engine.js:939:5
    at /home/osboxes/zenbot/node_modules/async/dist/async.js:4082:9

**Comment by araviel** [comment]
same with --period=30m

**Comment by DeviaVir** [comment]
Can you retry with the latest commit?
