### ISSUE TITLE
(darwin cci_srsi)  TypeError: Cannot read property 'currency' of undefined

### ISSUE THREAD

**Issue by araviel** [DeviaVir/zenbot#1470]
KINDLY READ AND ACT ON THE BELOW INFORMATION BEFORE FILING YOUR ISSUE!

Please go to our Zenbot subreddit for questions, help and support:

[https://www.reddit.com/r/zenbot/](https://www.reddit.com/r/zenbot/)

If you open a GitHub issue, here is our policy:

1. It must be a bug or a feature request.
2. The form below must be filled out.

**Here's why we have that policy**: Zenbot developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals and rarely leads to bugfixes or useful enhancements. GitHub also notifies hundreds of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Reddit.

------------------------
Remove everything above before creating your issue.
------------------------

### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Zenbot version** (commit ref, or version):  93452e6  
- **Zenbot branch**: unstable
- **NodeJS version**: latest
- **Python version (when using a python script)**: latest
- **Exact command to reproduce (include everything)**:
/scripts/genetic_backtester/darwin.js --selector="bitfinex.ETH-USD" --days="50" --currency_capital="1000" --use_strategies="cci_srsi" --population="40" --population_data="simulations/cci_srsi1" --asset_capital="1" --order_type="taker"

- **Did I make any changes to conf-sample.js?**: No

### Describe the problem
The error didn't happen in first sims, it happens after the first 2 completed

### Source code / Error logs
TypeError: Cannot read property 'currency' of undefined

TypeError: Cannot read property 'currency' of undefined
    at processOutput (/home/osboxes/zenbot/lib/backtester.js:66:47)
    at ChildProcess.proc.on (/home/osboxes/zenbot/lib/backtester.js:522:18)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
0: 67.1%, 1: 1.1%, 2: 67.2%

**it happens for cci_srsi and srsi_macd**

**Comment by krystophv** [comment]
Just checking, but did you do an `npm install` after pulling the update?

**Comment by araviel** [comment]
I'm using this : git pull && npm install

But this error in darwin with those two specific strategy gave me this error since a long time ago

can someone try it by running a quick 20 pop of it please ?

./scripts/genetic_backtester/darwin.js --selector="bitfinex.ETH-USD" --days="50" --currency_capital="1000" --use_strategies="srsi_macd" --population="20" --population_data="simulations/cci_srsi1" --asset_capital="1" --order_type="taker"

**Comment by araviel** [comment]
same with trend_ema, idk if i'm missing something

**Comment by simclem77** [comment]
+1
I've the same issue wiht srsi_macd
