### ISSUE TITLE
MongoError: not authorized on zenbrain to execute command 

### ISSUE THREAD

**Issue by imjonathan** [DeviaVir/zenbot#148]
I'v just done a stock build and verified mongodb is running (version  v3.4.4) but when I try to run (using the config_sample.js as config.js) I get the following errors:

$ ./run.sh

/home/bitnami/zenbot/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^
MongoError: not authorized on zenbrain to execute command { listIndexes: "ticks", cursor: {} }
    at Function.MongoError.create (/home/bitnami/zenbot/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/bitnami/zenbot/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /home/bitnami/zenbot/node_modules/mongodb-core/lib/connection/pool.js:461:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by carlos8f** [comment]
my guess is in your config, you probably need `mongo_username` and `mongo_password` defined.

however, zenbot 3 is not maintained anymore, and likely isn't profitable anymore. 4 will come out soon and you might want to wait for that.
