### ISSUE TITLE
Cannot npm install on windows properly?

### ISSUE THREAD

**Issue by zachiechan** [DeviaVir/zenbot#1515]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Zenbot version** (commit ref, or version): 4.1
- **Zenbot branch**: ?
- **NodeJS version**: 8.10
- **Python version (when using a python script)**: 3.6.4
- **Exact command to reproduce (include everything)**: npm install .... any zenbot command
- **Did I make any changes to conf-sample.js?**: only passwords

### Describe the problem
I just cannot seem to get zenbot installed properly. I follow the steps download nodejs, get mongodb account, change conf.js file for my mongodb and api keys, cloned the zenbot.git as administrator but then npm install returns the following error about forex.analytics unable to be moved, and then any zenbot command says something about cannot find module analytics.node. 

### Source code / Error logs
C:\Windows\System32\zenbot>npm install
npm ERR! path C:\Windows\System32\zenbot\node_modules\forex.analytics
npm ERR! code EISGIT
npm ERR! git C:\Windows\System32\zenbot\node_modules\forex.analytics: Appears to be a git repo or submodule.
npm ERR! git     C:\Windows\System32\zenbot\node_modules\forex.analytics
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\benig_000\AppData\Roaming\npm-cache\_logs\2018-03-18T21_56_32_706Z-debug.log

C:\Windows\System32\zenbot>zenbot list-selectors

C:\Windows\System32\zenbot>node zenbot.js list-selectors
module.js:549
    throw err;
    ^

Error: Cannot find module './build/Release/analytics.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Windows\System32\zenbot\node_modules\forex.analytics\index.js:1:79)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

[2018-03-18T21_56_32_706Z-debug.log](https://github.com/DeviaVir/zenbot/files/1823203/2018-03-18T21_56_32_706Z-debug.log)

**Comment by biovolt** [comment]
I get the same error on Windows 8
No custom code clean install
node -v v8.12.0
npm -v  6.4.1

```
node zenbot.js backfill bitstamp.USD-BTC --days 5
(node:5536) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
module.js:550
    throw err;
    ^

Error: Cannot find module './build/Release/analytics.node'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\work\temp\zen\zenbot\node_modules\forex.analytics\index.js:1:79)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```
