### ISSUE TITLE
--min_prev_trades  it not working 

### ISSUE THREAD

**Issue by voravitl** [DeviaVir/zenbot#1530]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Docker
- **Zenbot version** (commit ref, or version): #1526 
- **Zenbot branch**:unstable
- **NodeJS version**: v8.9.10
- **Python version (when using a python script)**:
- **Exact command to reproduce (include everything)**:
zenbot trade \
binance.NCASH-BTC \
--buy_max_amt=0.007 \
--strategy=macd \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=6 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=22 \
--overbought_rsi=76 \
--poll_trades=3000 \
--exact_buy_orders \
--exact_sell_orders \
--use_prev_trades \
--min_prev_trades=10 \
--sell_stop_pct=2 \
--buy_stop_pct=2 \
--max_sell_loss_pct=3 \
--max_buy_loss_pct=25 \
--profit_stop_enable_pct=9 \
--profit_stop_pct=0.5 \
--markdown_buy_pct=0.79 \
--order_poll_time=5000 \
--order_adjust_time=5000 \
--markup_sell_pct=0.84
- **Did I make any changes to conf-sample.js?**: NO

### Describe the problem
--min_prev_trades=10  it not working 

### Source code / Error logs
module.js:549
    throw err;
    ^

Error: Cannot find module '/app/extensions/exchanges/10/exchange'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (/app/lib/engine.js:31:20)
    at Command.<anonymous> (/app/commands/trade.js:87:20)
    at Command.listener (/app/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/app/node_modules/commander/index.js:651:12)

**Comment by defkev** [comment]
That's indeed not working...let me take a look.
