### ISSUE TITLE
ti_hma not working (both sim and trade)

### ISSUE THREAD

**Issue by tybor** [DeviaVir/zenbot#1540]
### System information
- vanilla (freshly git pulled)
- Linux Debian testing
- commit 3e881cc012f9941f95314be94e7b7d239eee529d
- unstable
- node 8.11.0
- Python n/a
- ./zenbot.sh sim gdax.LTC-EUR --sell_stop_pct 0.1 --strategy ti_hma --start 201803 --days 30
- **Did I make any changes to conf-sample.js?**:

### Describe the problem

It crashes using ti_hma strategy, both in sim and trade mode

### Source code / Error logs
/home/paolo/zenbot-unstable/node_modules/timebucket/lib/bucket-size.js:15
  if (!match) throw new Error('invalid bucket size spec: ' + spec);
              ^

Error: invalid bucket size spec: undefined
    at BucketSize.parse (/home/paolo/zenbot-unstable/node_modules/timebucket/lib/bucket-size.js:15:21)
    at new BucketSize (/home/paolo/zenbot-unstable/node_modules/timebucket/lib/bucket-size.js:5:21)
    at Bucket.resize (/home/paolo/zenbot-unstable/node_modules/timebucket/lib/bucket.js:30:14)
    at Command.<anonymous> (/home/paolo/zenbot-unstable/commands/sim.js:98:49)
    at Command.listener (/home/paolo/zenbot-unstable/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/home/paolo/zenbot-unstable/node_modules/commander/index.js:651:12)
    at Command.parse (/home/paolo/zenbot-unstable/node_modules/commander/index.js:474:21)
    at /home/paolo/zenbot-unstable/zenbot.js:46:13

**Comment by LoneWolf345** [comment]
You forgot to specify a Period_Length
