### ISSUE TITLE
Mongojs error

### ISSUE THREAD

**Issue by theposs101** [DeviaVir/zenbot#1571]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Zenbot version** (commit ref, or version): 4.1.0
- **Zenbot branch**: unstable
- **NodeJS version**: 9.11.1
- **Python version (when using a python script)**: n/a
- **Exact command to reproduce (include everything)**: ./zenbot.sh binance.BTC-USDT —paper —strategy neural
- **Did I make any changes to conf-sample.js? Yes, https://pastebin.com/hPKwZzHn
### Describe the problem

After running zenbot for about 5 or so minutes, it throws an error. Seems to be an issue with the mongo module, after researching and looking at the error.

### Source code / Error logs

/root/zenbot/node_modules/mongodb/lib/utils.js:132
throw err;
^
MongoError: cursor id 34859244662 not found
at /root/zenbot/node_modules/mongodb-core/lib/connection/pool.js:598:61
at authenticateStragglers (/root/zenbot/node_modules/mongodb-core/lib/connection/pool.js:516:16)
at Connection.messageHandler (/root/zenbot/node_modules/mongodb-core/lib/connection/pool.js:552:5)
at emitMessageHandler (/root/zenbot/node_modules/mongodb core/lib/connection/connection.js:309:10)
at Socket.<anonymous> (/root/zenbot/node_modules/mongodb-core/lib/connection/connection.js:452:17)
at Socket.emit (events.js:180:13)
at addChunk (_stream_readable.js:274:12)
at readableAddChunk (_stream_readable.js:261:11)
at Socket.Readable.push (_stream_readable.js:218:10)
at TCP.onread (net.js:581:20

**Comment by theposs101** [comment]
This also seems to happen when the bot does a sell.

**Comment by theposs101** [comment]
Seems that updating the mongojs module fixes it

**Comment by theposs101** [comment]
Just got the error again, reopening.

**Comment by kenorb** [comment]
See: mongodb-js/mongodb-core/issues/199

**Comment by theposs101** [comment]
Managed to fix it by downgrading to Ubuntu 16.04. I've had it run for 24 hours without issue. It might be an issue related to MongoDB and/or NodeJS's MongoJS module on Ubuntu 18.04. Thanks!

**Comment by vovchisko** [comment]
Same issue.
mongodb server v3.6.5
mongodb module v3.0.10
nodejs v10.2.1

**Comment by vovchisko** [comment]
@PossibilitiesMC What MongoDB version you have now?
