### ISSUE TITLE
get balance error on kraken

### ISSUE THREAD

**Issue by sfdu** [DeviaVir/zenbot#1590]
I have this error when I am running ./zenbot.sh balance and when the zenbot wants to buy or sell any currency.  zenbot is running on ubuntu and kraken API

./zenbot.sh balance
/zenbot/commands/balance.js:36
        s.exchange.getBalance(s, function (err, balance) {
                   ^

TypeError: Cannot read property 'getBalance' of undefined
    at balance (/zenbot/commands/balance.js:36:20)
    at Command.<anonymous> (/zenbot/commands/balance.js:68:7)
    at Command.listener (/zenbot/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/zenbot/node_modules/commander/index.js:651:12)
    at Command.parse (/zenbot/node_modules/commander/index.js:474:21)
    at /zenbot/zenbot.js:46:13
    at FSReqWrap.oncomplete (fs.js:135:15)

Any idea what is wrong?
thank you

**Comment by njannink** [comment]
I'm busy adding support for another exchange and I get the same error so I doubt it has anything to do with Kraken.

**Comment by wiiisp** [comment]
I get the exact same error on kraken. Anyone have an idea?

**Comment by brucetus** [comment]
I have a feeling these balance errors on many exchanges might be due to this commit https://github.com/DeviaVir/zenbot/commit/0d0bfd3dbb4c91772c3f78a164bcbe59187f1661#diff-ea60a8f0911de04106529d9e530373a8
