### ISSUE TITLE
 Error: read ECONNRESET

### ISSUE THREAD

**Issue by Peggy1012** [DeviaVir/zenbot#1597]
From time to time, I get the following error messages although the balance of currency and asset are shown correctly. Can you please help on this? Thanks.

{ Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:610:25)
 code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:610:25)

**Comment by DeviaVir** [comment]
Please re-open your issue using the issue template, thanks!
