### ISSUE TITLE
module.js:549     throw err;     ^  Error: Cannot find module 'semver'     a

### ISSUE THREAD

**Issue by diveyez** [DeviaVir/zenbot#1610]
Used on Debian 8 in WSL with a full debian install. Not the packaged Windows Store Version.

diveyez@Alienware:~/zenbot$ ./zenbot.sh
module.js:549
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/diveyez/zenbot/zenbot.js:2:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by diveyez** [comment]
Closing, NPM did not install it correctly. Fixed by running the npm install command again.
