### ISSUE TITLE
MongoError: server instance pool was destroyed 

### ISSUE THREAD

**Issue by yaotian** [DeviaVir/zenbot#1612]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **Zenbot version** (commit ref, or version):4.1.0
- **Zenbot branch**:unstanble
- **NodeJS version**:v9.5.0
- **Python version (when using a python script)**:n/a
- **Exact command to reproduce (include everything)**:
env node zenbot.js trade binance.BTC-USDT --paper --strategy=bollinger --currency_capital=5000 --period_length=5m
- **Did I make any changes to conf-sample.js?**:no

### Describe the problem
crash and print error msg again and again.
restart mongdb, it is still there.

### Source code / Error logs

2018-06-10 09:17:41 - error saving session
{ MongoError: server instance pool was destroyed
    at basicWriteValidations (/home/yaotian/app/zenbot/node_modules/mongodb-core/lib/topologies/server.js:641:41)
    at Server.update (/home/yaotian/app/zenbot/node_modules/mongodb-core/lib/topologies/server.js:781:16)
    at Server.update (/home/yaotian/app/zenbot/node_modules/mongodb/lib/topologies/topology_base.js:326:25)
    at updateDocuments (/home/yaotian/app/zenbot/node_modules/mongodb/lib/collection.js:1023:19)
    at save (/home/yaotian/app/zenbot/node_modules/mongodb/lib/collection.js:1273:12)
    at executeOperation (/home/yaotian/app/zenbot/node_modules/mongodb/lib/utils.js:420:24)
    at Collection.save (/home/yaotian/app/zenbot/node_modules/mongodb/lib/collection.js:1260:10)
    at /home/yaotian/app/zenbot/commands/trade.js:611:22
    at /home/yaotian/app/zenbot/lib/engine.js:240:9
    at /home/yaotian/app/zenbot/lib/engine.js:309:7
  name: 'MongoError',
  message: 'server instance pool was destroyed' }

**Comment by diegstroyer** [comment]
Trty to update MongoDB via npm, in meteor project any user have a similar issue.
```
zenbot update npm-mongo
zenbot update --all-packages
```
Related issues:
https://github.com/meteor/meteor/issues/7822
