### ISSUE TITLE
Error GetBalance Kraken API

### ISSUE THREAD

**Issue by rroux** [DeviaVir/zenbot#1649]
**System information**

Have I written custom code (as opposed to using zenbot vanilla): No.
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
Zenbot version (commit ref, or version): Commits on Jul 1, 2018
Zenbot branch: stable
NodeJS version: v9.11.1
Python version (when using a python script): Not using python
Exact command to reproduce (include everything): No
Did I make any changes to conf-sample.js?:
c.selector = 'kraken.XXMR-ZEUR'
c.strategy = 'trend_ema'

**Describe the problem**

I can't see the purchase and sale on the chart, the trade meter remains at 0, while there is trades done on Kraken. And I have the following error in the logs

getBalance error:
{ RequestError: Request timed out
    at timeoutFn (/root/zenbot/node_modules/kraken-api/node_modules/got/index.js:131:53)
    at asPromise (/root/zenbot/node_modules/kraken-api/node_modules/got/index.js:134:9)
    at got (/root/zenbot/node_modules/kraken-api/node_modules/got/index.js:386:10)
    at rawRequest (/root/zenbot/node_modules/kraken-api/kraken.js:42:25)
    at KrakenClient.privateMethod (/root/zenbot/node_modules/kraken-api/kraken.js:171:20)
    at KrakenClient.api (/root/zenbot/node_modules/kraken-api/kraken.js:96:16)
    at Object.getBalance (/root/zenbot/extensions/exchanges/kraken/exchange.js:146:14)
    at Object.syncBalance (/root/zenbot/lib/engine.js:211:16)
    at saveSession (/root/zenbot/commands/trade.js:551:18)
    at /root/zenbot/commands/trade.js:712:13
    at /root/zenbot/extensions/exchanges/kraken/exchange.js:139:9
    at response.then (/root/zenbot/node_modules/kraken-api/kraken.js:125:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'RequestError',
  code: 'ETIMEDOUT',
  host: 'api.kraken.com',
  hostname: 'api.kraken.com',
  method: 'POST',
  path: '/0/private/Balance',
  protocol: 'https:',
  url: 'https://api.kraken.com/0/private/Balance' }

2018-07-05 11:25:56 - error syncing balance
{ RequestError: Request timed out
    at timeoutFn (/root/zenbot/node_modules/kraken-api/node_modules/got/index.js:131:53)
    at asPromise (/root/zenbot/node_modules/kraken-api/node_modules/got/index.js:134:9)
    at got (/root/zenbot/node_modules/kraken-api/node_modules/got/index.js:386:10)
    at rawRequest (/root/zenbot/node_modules/kraken-api/kraken.js:42:25)
    at KrakenClient.privateMethod (/root/zenbot/node_modules/kraken-api/kraken.js:171:20)
    at KrakenClient.api (/root/zenbot/node_modules/kraken-api/kraken.js:96:16)
    at Object.getBalance (/root/zenbot/extensions/exchanges/kraken/exchange.js:146:14)
    at Object.syncBalance (/root/zenbot/lib/engine.js:211:16)
    at saveSession (/root/zenbot/commands/trade.js:551:18)
    at /root/zenbot/commands/trade.js:712:13
    at /root/zenbot/extensions/exchanges/kraken/exchange.js:139:9
    at response.then (/root/zenbot/node_modules/kraken-api/kraken.js:125:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'RequestError',
  code: 'ETIMEDOUT',
  host: 'api.kraken.com',
  hostname: 'api.kraken.com',
  method: 'POST',
  path: '/0/private/Balance',
  protocol: 'https:',
  url: 'https://api.kraken.com/0/private/Balance' }

**Comment by diegstroyer** [comment]
Try the things suggested in doc from Zenbot:

 zenbot/docs/exchanges/kraken.md
