### ISSUE TITLE
Invalid Quantity Error

### ISSUE THREAD

**Issue by carpionetwork** [DeviaVir/zenbot#1671]
KINDLY READ AND ACT ON THE BELOW INFORMATION BEFORE FILING YOUR ISSUE!

Please go to our Zenbot subreddit for questions, help and support:

[https://www.reddit.com/r/zenbot/](https://www.reddit.com/r/zenbot/)

If you open a GitHub issue, here is our policy:

1. It must be a bug or a feature request.
2. The form below must be filled out.

**Here's why we have that policy**: Zenbot developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals and rarely leads to bugfixes or useful enhancements. GitHub also notifies hundreds of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Reddit.

------------------------
Remove everything above before creating your issue.
------------------------

### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **Zenbot version** (commit ref, or version):  As of Commits on Jul 23, 2018
- **Zenbot branch**: unstable
- **NodeJS version**: v8
- **Python version (when using a python script)**:
- **Exact command to reproduce (include everything)**:
- **Did I make any changes to conf-sample.js?**:

### Describe the problem

Prior to the most recent git pull buys and sells were working normally, but with the recent updates for every sell I am seeing:

code":-1013,"msg":"Invalid quantity."}
    at binance.handleErrors (/home/crypto/bots/zenbot/ada/node_modules/ccxt/js/binance.js:863:31)
    at response.text.then (/home/crypto/bots/zenbot/ada/node_modules/ccxt/js/base/Exchange.js:513:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidOrder] }                 
 
and during a typical buy signal the code does not print 'buy' and happily bypasses the buy times and once a 'sell' signal happens the above error is produced.

There are coins to sell and funds for buying.

I changed the max_sell/buy_loss_pct to 0 and a greater number just to see if it would trigger and it is no longer being triggered.

Anyone else seeing similar issues?

Thank you,
Jeff C

**Comment by mekstrem** [comment]
Two questions:
1. Which exchange are you getting these errors on?
2. What pair are you trading?

Usually this happens because the values in the exchanges products.json are mismatching the exchanges criterias.

**Comment by carpionetwork** [comment]
Thanks for the reply.

Gdax (btc/usd)
Binance (ada/btc, xlm,btc)

Should running the products.json update script sync the bot and the exchange back up?

Sidenote: I run three separate zenbot instances each with their own db, so they should not have conflicting trade signals.

**Comment by carpionetwork** [comment]
So I installed another zenbot instance and it's throwing the same error....
  -- git clone <latest code>
  -- npm install

I have enough funds to buy >15usd, which I read may be a Binance requirement.

Here is the error:

manual limit BUY command executed
An error occurred { Error: binance {"code":-1013,"msg":"Invalid quantity."}
    at binance.handleErrors (/home/crypto/bots/zenbot/xlm/node_modules/ccxt/js/binance.js:863:31)
    at response.text.then (/home/crypto/bots/zenbot/xlm/node_modules/ccxt/js/base/Exchange.js:513:18)
    at process._tickCallback (internal/process/next_tick.js:68:7) constructor: [Function: InvalidOrder] }

**Comment by carpionetwork** [comment]
Update:

During a new install package.json lists sass module (v4.8.3) but it was throwing a 404 error, so updating this to (4.9.2), seems to have fixed the buy / sell issue.

Will run it for a few hours and see how it goes.

**Comment by carpionetwork** [comment]
So far so good.  Zenbot has been chugging along.  Sidenote: it seems to run well with nodejs v10 and mongodb v4.0.
