### ISSUE TITLE
warning: mongodb not accessible. some features (such as backfilling/simulation) may be disabled.

### ISSUE THREAD

**Issue by albertolive** [DeviaVir/zenbot#168]
Hi,

I'm having this error whatever command I run. I have followed every step in readme me file.

Thanks

**Comment by carlos8f** [comment]
when you run the `mongo` command, can you connect to the CLI? if not, mongod is down. or else, try adding console.error(err) to line 37 of boot.js at see what it spits out.

**Comment by carlos8f** [comment]
also I recently changed `c.mongo_host` etc in to `c.mongo.host`. could that be it?

**Comment by dotsi** [comment]
I had to use the name of the container instead of localhost to get it working.

**Comment by itsMichael** [comment]
Me too have this error, with default settings for docker.

**Comment by DeviaVir** [comment]
Had the same "problem", the conf.js sample might want to add a comment to use `mongodb` (the name of the mongo docker link) instead of localhost?

**Comment by albertolive** [comment]
Hi,

I added a console log on line you said and it tells me that:

`{ MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Volumes/Macintosh HD/Users/albertolive/Documents/Webs/zenbot/node_modules/mongodb-core/lib/topologies/server.js:328:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Volumes/Macintosh HD/Users/albertolive/Documents/Webs/zenbot/node_modules/mongodb-core/lib/connection/pool.js:274:12)
    at Object.onceWrapper (events.js:290:19)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Volumes/Macintosh HD/Users/albertolive/Documents/Webs/zenbot/node_modules/mongodb-core/lib/connection/connection.js:177:49)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }`

**Comment by albertolive** [comment]
Never mind, I ended up using docker. My mac OSX is old and have a lot of issues.

**Comment by albertolive** [comment]
Ok, the real error was that I couldn't use mongod because I needed sudo rights. If I want to use zenbot, first I have to run in another terminal sudo mongod.

**Comment by DeviaVir** [comment]
Docker to the rescue.

**Comment by ghost** [comment]
I had the same problem, I went and installed monogdb again then ran mongodb in a separate terminal and it worked.
