### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by YuriyTigiev** [DeviaVir/zenbot#1682]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Microsoft Windows [Version 10.0.17134.228] 64 bit
- **Zenbot version** (commit ref, or version): 4.1.0
- **Zenbot branch**:
- **NodeJS version**: 8.11.4
- **Python version (when using a python script)**: 2.7.14 64 bit
- **Exact command to reproduce (include everything)**: zenbot sim --strategy cci_srsi binance.BNB-BTC
- **Did I make any changes to conf-sample.js?**: No. I have copied conf-sample.js as conf.js and add a binance key.

### Describe the problem
When I run  zenbot sim --strategy cci_srsi binance.BNB-BTC it returns error. 
This command worked perfectly a few hours before. I have recreated zenbot4 database.
I have used update.bat and  npm install binance. Nothing was changed. 

### Source code / Error logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

c:\zenbot>node zenbot.js sim --strategy cci_srsi binance.BNB-BTC
If you have questions about this strategy, contact me... @talvasconcelos
(node:9908) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
2018-08-05 13:59:00  0.00193540 BNB-BTC   +0.04%    16337   51.81 +         139   -->              0.00000000 BNB  1000.2018-08-05 14:19:00  0.00193620 BNB-BTC   +0.04%    70181   52.16 +         100   -->              0.00000000 BNB  1000.2018-08-05 14:39:00  0.00194330 BNB-BTC   +0.37%    27688   55.26 ++        136     075           0.00000000 BNB  1000.02018-08-05 14:59:00  0.00193090 BNB-BTC   -0.64%    15188     - 49.26       061   -->              0.00000000 BNB  1000.2018-08-05 15:19:00  0.00192850 BNB-BTC   -0.12%    37888     - 48.17       003   -->              0.00000000 BNB  1000.2018-08-05 15:39:00  0.00191510 BNB-BTC   -0.69%    20831    -- 42.52      -063     057           0.00000000 BNB  1000.02018-08-05 15:59:00  0.00191980 BNB-BTC   +0.25%    14417    -- 44.96      -073     041           0.00000000 BNB  1000.02018-08-05 16:19:00  0.00191580 BNB-BTC   -0.21%    12656    -- 43.27      -078     032           0.00000000 BNB  1000.02018-08-05 16:39:00  0.00191590 BNB-BTC   +0.01%    12404    -- 43.33      -074     023           0.00000000 BNB  1000.02018-08-05 16:59:00  0.00192260 BNB-BTC   +0.35%    16612     - 47.17      -053   -->              0.00000000 BNB  1000.2018-08-05 17:19:00  0.00192800 BNB-BTC   +0.28%    16516   50.11 +         004   -->              0.00000000 BNB  1000.2018-08-05 17:39:00  0.00192650 BNB-BTC   -0.08%    10279     - 49.29      -003   -->              0.00000000 BNB  1000.2018-08-05 17:59:00  0.00192560 BNB-BTC   -0.05%    10898     - 48.77      -035   -->              0.00000000 BNB  1000.2018-08-05 18:19:00  0.00192510 BNB-BTC   -0.03%    10096     - 48.47      -023   -->              0.00000000 BNB  1000.2018-08-05 18:39:00  0.00192310 BNB-BTC   -0.10%    14317     - 47.20      -020   -->              0.00000000 BNB  1000.2018-08-05 18:59:00  0.00192360 BNB-BTC   +0.03%     8892     - 47.57      -014   -->              0.00000000 BNB  1000.2018-08-05 19:19:00  0.00192980 BNB-BTC   +0.32%    12249   52.04 +         026   -->              0.00000000 BNB  1000.2018-08-05 19:39:00  0.00192970 BNB-BTC   -0.01%    12907   51.96 +         112   -->              0.00000000 BNB  1000.2018-08-05 19:59:00  0.00193590 BNB-BTC   +0.32%    13271   56.27 ++        180   -->              0.00000000 BNB  1000.2018-08-05 20:19:00  0.00193290 BNB-BTC   -0.15%     9372   53.76 +         159   -->              0.00000000 BNB  1000.2018-08-05 20:39:00  0.00192390 BNB-BTC   -0.47%     9799     - 46.98       053   -->              0.00000000 BNB  1000.2018-08-05 20:59:00  0.00193310 BNB-BTC   +0.48%    14013   53.44 +         093   -->              0.00000000 BNB  1000.2018-08-05 21:19:00  0.00194370 BNB-BTC   +0.55%    14416   59.56 ++        204     069           0.00000000 BNB  1000.02018-08-05 21:39:00  0.00194130 BNB-BTC   -0.12%    13220   57.71 ++        240     074           0.00000000 BNB  1000.02018-08-05 21:59:00  0.00193900 BNB-BTC   -0.12%    30347   55.92 ++        177   -->              0.00000000 BNB  1000.2018-08-05 22:19:00  0.00194150 BNB-BTC   +0.13%    18508   57.46 ++        128     081           0.00000000 BNB  1000.02018-08-05 22:39:00  0.00193470 BNB-BTC   -0.35%    31908   52.11 +         066   -->              0.00000000 BNB  1000.2018-08-05 22:59:00  0.00193970 BNB-BTC   +0.26%    23433   55.40 ++        053   -->              0.00000000 BNB  1000.2018-08-05 23:19:00  0.00193670 BNB-BTC   -0.15%    28577   53.05 +         040   -->              0.00000000 BNB  1000.2018-08-05 23:39:00  0.00194280 BNB-BTC   +0.31%    12365   57.04 ++        103     057           0.00000000 BNB  1000.02018-08-05 23:59:00  0.00194590 BNB-BTC   +0.16%    21274   58.96 ++        113     062           0.00000000 BNB  1000.02018-08-06 00:19:00  0.00193460 BNB-BTC   -0.58%     9401   50.19 +         030   -->              0.00000000 BNB  1000.2018-08-06 00:39:00  0.00193200 BNB-BTC   -0.13%     8397     - 48.40      -075   -->              0.00000000 BNB  1000.2018-08-06 00:59:00  0.00192980 BNB-BTC   -0.11%     7495     - 46.88      -108   -->              0.00000000 BNB  1000.2018-08-06 01:19:00  0.00192280 BNB-BTC   -0.36%     8703    -- 42.33      -217     029           0.00000000 BNB  1000.02018-08-06 01:39:00  0.00191730 BNB-BTC   -0.29%    38284    -- 39.12      -366     007           0.00000000 BNB  1000.02018-08-06 01:59:00  0.00191500 BNB-BTC   -0.12%    39713    -- 37.82      -306     002           0.00000000 BNB  1000.02018-08-06 02:19:00  0.00192480 BNB-BTC   +0.51%    15441     - 46.01      -116   -->              0.00000000 BNB  1000.2018-08-06 02:39:00  0.00192520 BNB-BTC   +0.02%     9688     - 46.32      -068   -->              0.00000000 BNB  1000.2018-08-06 02:59:00  0.00192420 BNB-BTC   -0.05%     6796     - 45.62      -055   -->              0.00000000 BNB  1000.2018-08-06 03:19:00  0.00193270 BNB-BTC   +0.44%     9169   52.28 +         002   -->              0.00000000 BNB  1000.2018-08-06 03:39:00  0.00193340 BNB-BTC   +0.04%     6216   52.80 +         031   -->              0.00000000 BNB  1000.2018-08-06 03:59:00  0.00193910 BNB-BTC   +0.29%    13080   56.86 ++        082   -->              0.00000000 BNB  1000.2018-08-06 04:19:00  0.00193430 BNB-BTC   -0.25%    18730   52.74 +         051   -->              0.00000000 BNB  1000.2018-08-06 04:39:00  0.00193440 BNB-BTC   +0.01%     7979   52.82 +         053   -->              0.00000000 BNB  1000.2018-08-06 04:59:00  0.00193810 BNB-BTC   +0.19%     8167   55.69 ++        096   -->              0.00000000 BNB  1000.2018-08-06 05:19:00  0.00194210 BNB-BTC   +0.21%    12730   58.61 ++        147     087           0.00000000 BNB  1000.02018-08-06 05:39:00  0.00194230 BNB-BTC   +0.01%     7146   58.76 ++        137     089           0.00000000 BNB  1000.02018-08-06 05:59:00  0.00194190 BNB-BTC   -0.02%     6782   58.32 ++        105   -->              0.00000000 BNB  1000.2018-08-06 06:19:00  0.00193770 BNB-BTC   -0.22%     5578   53.71 +         063   -->              0.00000000 BNB  1000.2018-08-06 06:39:00  0.00193560 BNB-BTC   -0.11%     8144   51.52 +         042   -->              0.00000000 BNB  1000.2018-08-06 06:59:00  0.00194250 BNB-BTC   +0.36%    26769   57.63 ++        051   -->              0.00000000 BNB  1000.2018-08-06 07:19:00  0.00195780 BNB-BTC   +0.79%    33135   67.44 +++       238     080           0.00000000 BNB  1000.02018-08-06 07:39:00  0.00196570 BNB-BTC   +0.40%    81645   71.15 +++       395     081           0.00000000 BNB  1000.02018-08-06 07:59:00  0.00195990 BNB-BTC   -0.30%    32997   65.27 +++       235     085           0.00000000 BNB  1000.02018-08-06 08:19:00  0.00195370 BNB-BTC   -0.32%    16173   59.59 ++        136     086           0.00000000 BNB  1000.02018-08-06 08:39:00  0.00195290 BNB-BTC   -0.04%     9228   58.88 ++        078     069           0.00000000 BNB  1000.02018-08-06 08:59:00  0.00195650 BNB-BTC   +0.18%    12085   61.13 ++        067     055           0.00000000 BNB  1000.02018-08-06 09:19:00  0.00194940 BNB-BTC   -0.36%    22944   54.77 +         039   -->              0.00000000 BNB  1000.2018-08-06 09:39:00  0.00195920 BNB-BTC   +0.50%    20558   60.83 ++        062     033           0.00000000 BNB  1000.02018-08-06 09:59:00  0.00195910 BNB-BTC   -0.01%    11590   60.74 ++        065     037           0.00000000 BNB  1000.02018-08-06 10:19:00  0.00194900 BNB-BTC   -0.52%    13832   52.37 +         004   -->              0.00000000 BNB  1000.2018-08-06 10:39:00  0.00195360 BNB-BTC   +0.24%    11205   55.38 ++        016   -->              0.00000000 BNB  1000.2018-08-06 10:59:00  0.00194900 BNB-BTC   -0.24%    16337   51.85 +        -025   -->              0.00000000 BNB  1000.2018-08-06 11:19:00  0.00195020 BNB-BTC   +0.06%     9623   52.70 +        -036   -->              0.00000000 BNB  1000.2018-08-06 11:39:00  0.00195560 BNB-BTC   +0.28%    12666   56.42 ++        021     008           0.00000000 BNB  1000.02018-08-06 11:59:00  0.00195040 BNB-BTC   -0.27%    19134   52.16 +        -039   -->              0.00000000 BNB  1000.2018-08-06 12:19:00  0.00195080 BNB-BTC   +0.02%     8653   52.46 +        -135   -->              0.00000000 BNB  1000.2018-08-06 12:39:00  0.00195290 BNB-BTC   +0.11%     7678   54.07 +        -055   -->              0.00000000 BNB  1000.2018-08-06 12:59:00  0.00196090 BNB-BTC   +0.41%    17096   59.68 ++        132     012           0.00000000 BNB  1000.02018-08-06 13:19:00  0.00195960 BNB-BTC   -0.07%    20103   58.43 ++        262     043           0.00000000 BNB  1000.02018-08-06 13:39:00  0.00196630 BNB-BTC   +0.34%    14885   62.76 ++        196     051           0.00000000 BNB  1000.02018-08-06 13:59:00  0.00195950 BNB-BTC   -0.35%    17414   56.35 ++        142     075           0.00000000 BNB  1000.02018-08-06 14:19:00  0.00195300 BNB-BTC   -0.33%    20526   50.99 +        -002   -->              0.00000000 BNB  1000.2018-08-06 14:39:00  0.00195190 BNB-BTC   -0.06%    23915   50.12 +        -061   -->              0.00000000 BNB  1000.2018-08-06 14:59:00  0.00196360 BNB-BTC   +0.60%    46950   58.27 ++        093     028           0.00000000 BNB  1000.02018-08-06 15:19:00  0.00197680 BNB-BTC   +0.67%    41800   65.18 +++       276     037           0.00000000 BNB  1000.02018-08-06 15:39:00  0.00196930 BNB-BTC   -0.38%    73922   59.18 ++        173     049           0.00000000 BNB  1000.02018-08-06 15:59:00  0.00195930 BNB-BTC   -0.51%    19578   52.28 +         058   -->              0.00000000 BNB  1000.2018-08-06 16:19:00  0.00197270 BNB-BTC   +0.68%    39196   59.15 ++        112     053           0.00000000 BNB  1000.02018-08-06 16:39:00  0.00196640 BNB-BTC   -0.32%    24796   55.13 ++        087     057           0.00000000 BNB  1000.02018-08-06 16:59:00  0.00197190 BNB-BTC   +0.28%    24031   57.83 ++        118     040           0.00000000 BNB  1000.02018-08-06 17:19:00  0.00195930 BNB-BTC   -0.64%    30588   50.36 +        -008   -->              0.00000000 BNB  1000.2018-08-06 17:39:00  0.00195850 BNB-BTC   -0.04%    18621     - 49.92      -037   -->              0.00000000 BNB  1000.2018-08-06 17:59:00  0.00196030 BNB-BTC   +0.09%    20486   50.96 +        -012   -->              0.00000000 BNB  1000.2018-08-06 18:19:00  0.00198590 BNB-BTC   +1.31%    52178   62.79 ++        188     013           0.00000000 BNB  1000.02018-08-06 18:39:00  0.00196870 BNB-BTC   -0.87%    25307   53.46 +         117   -->              0.00000000 BNB  1000.2018-08-06 18:59:00  0.00197040 BNB-BTC   +0.09%    20693   54.18 +         067     029           0.00000000 BNB  1000.02018-08-06 19:19:00  0.00196360 BNB-BTC   -0.35%    26991   50.78 +        -018   -->              0.00000000 BNB  1000.2018-08-06 19:39:00  0.00196280 BNB-BTC   -0.04%    34664   50.38 +        -056   -->              0.00000000 BNB  1000.2018-08-06 19:59:00  0.00195890 BNB-BTC   -0.20%    17685     - 48.37      -098   -->              0.00000000 BNB  1000.2018-08-06 20:19:00  0.00195460 BNB-BTC   -0.22%    20743     - 46.18      -149   -->              0.00000000 BNB  1000.2018-08-06 20:39:00  0.00195590 BNB-BTC   +0.07%    21521     - 46.96      -168   -->              0.00000000 BNB  1000.2018-08-06 20:59:00  0.00195740 BNB-BTC   +0.08%    29816     - 47.90      -097   -->         buy  0.00000000 BNB  1000.00000000 BTC   +0.00%   -1.21%c:\zenbot\node_modules\lolex\src\lolex-src.js:663
                throw firstException;
                ^

TypeError: Cannot read property 'toString' of null
    at multiplier (c:\zenbot\node_modules\numbro\numbro.js:1123:23)
    at c:\zenbot\node_modules\numbro\numbro.js:1139:22
    at Array.reduce (<anonymous>)
    at correctionFactor (c:\zenbot\node_modules\numbro\numbro.js:1137:21)
    at Numbro.add (c:\zenbot\node_modules\numbro\numbro.js:1218:47)
    at c:\zenbot\lib\engine.js:362:61
    at c:\zenbot\lib\engine.js:235:9
    at c:\zenbot\lib\engine.js:304:7
    at c:\zenbot\extensions\exchanges\sim\exchange.js:66:18
    at callTimer (c:\zenbot\node_modules\lolex\src\lolex-src.js:356:24)
    at Object.tick (c:\zenbot\node_modules\lolex\src\lolex-src.js:622:25)
    at withOnPeriod (c:\zenbot\lib\engine.js:767:19)
    at onTrade (c:\zenbot\lib\engine.js:934:7)
    at c:\zenbot\lib\engine.js:895:5
    at c:\zenbot\node_modules\async\dist\async.js:4096:9
    at Object.process (c:\zenbot\node_modules\async\dist\async.js:2344:17)
    at c:\zenbot\node_modules\async\dist\async.js:2252:19
    at Immediate._onImmediate (c:\zenbot\node_modules\async\dist\async.js:119:16)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by YuriyTigiev** [comment]
I have done an additional test 

Doesn't work
c:\zenbot>node zenbot.js sim --strategy cci_srsi binance.BNB-BTC --period=1m

Works
c:\zenbot>node zenbot.js sim --strategy cci_srsi binance.BNB-BTC --period=1h

**Comment by YuriyTigiev** [comment]
For (1h) period the bot use data only for 17 days. But I have downloaded data for the last 90 days.
zenbot backfill --days 90 binance.BNB-BTC

node zenbot.js sim --strategy cci_srsi binance.BNB-BTC --period=1h

end balance: 1000.00000000 (0.00%)
buy hold: 1016.89298941 (1.69%)
vs. buy hold: -1.66%
0 trades over 17 days (avg 0.00 trades/day)
{
  "asset_capital": 0,
  "avg_slippage_pct": 0.045,
  "buy_pct": 99,
  "buy_stop_pct": 0,
  "cci_periods": 14,
  "constant": 0.015,
  "currency_capital": 1000,
  "days": 14,
  "debug": true,
  "ema_acc": 0.03,
  "markdown_buy_pct": 0,
  "markup_sell_pct": 0,
  "max_buy_loss_pct": 99,
  "max_sell_loss_pct": 99,
  "max_slippage_pct": 5,
  "min_periods": 30,
  "mode": "sim",
  "order_adjust_time": 5000,
  "order_poll_time": 5000,
  "order_type": "maker",
  "overbought_cci": 140,
  "overbought_rsi": 85,
  "oversold_cci": -90,
  "oversold_rsi": 18,
  "period": "1h",
  "period_length": "1h",
  "profit_stop_enable_pct": 0,
  "profit_stop_pct": 1,
  "rsi_periods": 14,
  "selector": {
    "exchange_id": "binance",
    "product_id": "BNB-BTC",
    "asset": "BNB",
    "currency": "BTC",
    "normalized": "binance.BNB-BTC"
  },
  "sell_pct": 99,
  "sell_stop_pct": 0,
  "show_options": true,
  "srsi_d": 3,
  "srsi_k": 5,
  "srsi_periods": 9,
  "start": 1533513600000,
  "stats": false,
  "strategy": "cci_srsi",
  "verbose": false,
  "simresults": {
    "start_capital": 1000,
    "last_assest_value": 0.0015651,
    "asset_capital": 0,
    "currency": 1000,
    "profit": 0,
    "buy_hold": 1016.8929894093951,
    "buy_hold_profit": 0.016892989409395112,
    "total_trades": 0,
    "length_days": 17,
    "total_sells": 0,
    "total_losses": 0,
    "vs_buy_hold": -1.6612357037888965
  },
  "net_currency": 1000
}
wrote simulations/sim_result_binance.BNB-BTC_180820_004200_UTC.html
(node:6192) DeprecationWarning: collection.save is deprecated. Use insertOne, insertMany, updateOne, or updateMany instead.

**Comment by YuriyTigiev** [comment]
I have reinstalled the software and now it works.
