### ISSUE TITLE
[bug]  Filter failure: MIN_NOTIONAL

### ISSUE THREAD

**Issue by YuriyTigiev** [DeviaVir/zenbot#1688]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro on Azure (Ubuntu Bash 18.04) 
- **Zenbot version** (commit ref, or version):  v.4.1.0 (latest)
- **Zenbot branch**:
- **NodeJS version**: nodejs 8.11.4-1nodesource1.
- **Python version (when using a python script)**: Python 2.7.15rc1

- **Exact command to reproduce (include everything)**:
./zenbot.sh trade --trade-strategy cci_srsi  binance.ETC-BTC --debug  --period=1m --ema_acc=0.03 --cci_periods=14 --rsi_periods=14 --srsi_periods=9 --srsi_k=5 --srsi_d=3 --oversold_rsi=25 --overbought_rsi=75 --oversold_cci=-140  --overbought_cci=180 --constant=0.015

- **Did I make any changes to conf-sample.js?**:
I have madden changes in the conf.js 
I have added binance keys 

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in Zenbot or a feature request.
I have tried to trade with my bitcoin balance 0.01119022 BTC. I got the error - see below. 
On this computer, I have traded from the Gekko without any problem. I have used Ubuntu Bash for Windows 10 and I have used the same binance keys. 
  
Before I have tried to install the software on the windows 10 and for this cases I also have gotten the same error.  I use the US regional settings on my Windows 10 pro. 

### Source code / Error logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

2018-08-23 15:04:19 - preparing buy order over 0.01940000 ETC of 0.0110672 BTC (99%) tradeable balance with a expected fee of 0.00001107 BTC (0.1%)

2018-08-23 15:04:19 - placing buy order...
An error occurred { Error: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
    at binance.handleErrors (/home/ytigiev/zenbot/node_modules/ccxt/js/binance.js:863:31)
    at response.text.then (/home/ytigiev/zenbot/node_modules/ccxt/js/base/Exchange.js:513:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidOrder] }

2018-08-23 15:04:19 - not enough balance for buy, aborting

**Comment by YuriyTigiev** [comment]
Hello, 

Today I have seen your post (https://github.com/DeviaVir/zenbot/pull/1690) and I have updated zenbot by ./update.sh 

I have tested the zenbot after the update.   Result in the bellow. I will continue to use the gekko, until the issue will not fix. 

-- in the paper mode I have gotten the error  

buy order completed at 2018-08-26 11:09:00:

0.01840500 ETC at 0.00183400 BTC
total 0.00003375 BTC
0.0000% slippage (orig. price 0.00183400 BTC)
execution: Invalid date
 

======================================================
In the trade mode I have gotten the following error:

2018-08-26 15:53:17 - preparing buy order over 0.01840500 ETC of 0.0106339 BTC (99%) tradeable balance with a expected fee of 0.00001064 BTC (0.1%)
2018-08-26 15:53:17 - placing buy order...
2018-08-26 15:53:00  0.00186300 ETC-BTC   +0.00%      515   53.41 +       0.0037   0.0036   buying  0.00005000 ETC  0.01075211 BTC   -0.01%   +0.21%An error occurred { Error: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
    at binance.handleErrors (/home/ytigiev/zenbot/node_modules/ccxt/js/binance.js:971:31)
    at response.text.then (/home/ytigiev/zenbot/node_modules/ccxt/js/base/Exchange.js:592:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidOrder] }

2018-08-26 15:53:17 - not enough balance for buy, aborting

2018-08-26 15:53:17 - not enough balance, or signal switched, cancel buy
