### ISSUE TITLE
could not execute sell: error placing order

### ISSUE THREAD

**Issue by vitorego** [DeviaVir/zenbot#176]
Hi,
I´m using zenbot since december last year (v3.x) and let me tell you that you have done a amazing bot for trading bitcoins. 
Today I got this error:
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at TLSSocket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ECONNRESET',
  desc: 'could not execute sell: error placing order' }
```
and the order was placed, however the bot said that the order wasn´t placed. Would be better to abort orders when there is such errors?

**Comment by urnotsam** [comment]
Have you updated to zenbot 4.x?  3.x is no longer supported

**Comment by vitorego** [comment]
Yes. I'm using 4.x.

**Comment by DeviaVir** [comment]
This look a lot like network issues, are you using it over a brittle network?

**Comment by vitorego** [comment]
Yes, it is a network issue, sometimes I have network issues. I think there is nothing we can do to overcome. I will close this issue
