### ISSUE TITLE
TypeError: body.map is not a function

### ISSUE THREAD

**Issue by charlesastwood** [DeviaVir/zenbot#184]
Running latest v4 from master.

Getting the following on Poloniex post sell:

TypeError: body.map is not a function
    at /var/bot/zenbot/extensions/poloniex/exchange.js:77:27
    at Request._callback (/var/bot/zenbot/node_modules/poloniex.js/lib/poloniex.js:79:7)
    at Request.self.callback (/var/bot/zenbot/node_modules/poloniex.js/node_modules/request/request.js:122:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/var/bot/zenbot/node_modules/poloniex.js/node_modules/request/request.js:888:14)                             at emitOne (events.js:82:20)                                                                                                         at Request.emit (events.js:169:7)                                                                                                    at IncomingMessage.<anonymous> (/var/bot/zenbot/node_modules/poloniex.js/node_modules/request/request.js:839:12)                     at emitNone (events.js:72:20)

Also getting the same error trying to back fill although this was working a few days ago

**Comment by talvasconcelos** [comment]
Have you solved this? i got the same error for backfill

**Comment by GhostPunk** [comment]
I got the same.

**Comment by carlos8f** [comment]
I can't reproduce, but since this is in getTrades() public api, it might be that you're reaching the dreaded 6-api calls per second ban. Added a console debug and retry in v4.0.4, so it will no longer crash, and we can see what kind of response caused the error.

**Comment by GhostPunk** [comment]
The problem was that USDT-BTC is not a valid pair it seems like, BTC-USDT is. However USDT-BTC is in the list-selectors output.

```
:~/zenbot$ zenbot backfill poloniex.USDT-BTC --days 14
getTrades odd result:
{ error: 'Invalid currency pair.' }
```

**Comment by DeviaVir** [comment]
@GhostPunk `USDT-BTC` is not a selector:

``` 
$ ./zenbot.sh list-selectors | grep poloniex | grep USD | grep BTC
  poloniex.BTC-USDT   (Bitcoin/Tether USD)
```

**Comment by DeviaVir** [comment]
Closing due to inactivity, and I haven't seen this pop up anymore since.
