### ISSUE TITLE
Error: Command is not a function

### ISSUE THREAD

**Issue by bryanbartow** [DeviaVir/zenbot#191]
Just updated from master and ran command ```zenbot trade``` and got the following error:
```
/home/zenbot/zenbot.sh:19
    command(program)
    ^

TypeError: command is not a function
    at /home/zenbot/zenbot.sh:19:5
    at Array.forEach (native)
    at /home/zenbot/zenbot.sh:18:12
    at /home/zenbot/boot.js:30:7
    at f (/home/zenbot/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/zenbot/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:191:7)
    at Glob._finish (/home/zenbot/node_modules/glob/glob.js:199:8)
    at done (/home/zenbot/node_modules/glob/glob.js:184:14)
```

Funny thing is, zenbot.sh hasn't been updated in a while, so I don't see any breaking change there. Anyone else?

**Comment by carlos8f** [comment]
that's weird. before line 19 if you `console.log(commands)`, what do you get?

**Comment by esalter** [comment]
Probably have to do 
```
npm install
```

**Comment by DeviaVir** [comment]
Closing due this ticket already being answered with what I believe is the correct answer, feel free to comment in case you still have this problem.
