### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by joker5bb** [DeviaVir/zenbot#215]
Latest commit breaks functionality 

$ zenbot list-selectors
module.js:327
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/zenbot/zenbot.sh:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by crubb** [comment]
Please try `npm install` first, some modules were added.

**Comment by DeviaVir** [comment]
Always `npm install` (or use the docker build) after an update. Thanks.
