### ISSUE TITLE
Error: Cannot find module 'kraken-api'

### ISSUE THREAD

**Issue by felipecaldas** [DeviaVir/zenbot#218]
Hey all,

Just pulled the repo minutes ago and getting this error now:

```
caldas@instance-1:~/zenbot$ ./zenbot.sh sim
module.js:328
    throw err;
    ^
Error: Cannot find module 'kraken-api'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/caldas/zenbot/extensions/kraken/exchange.js:1:82)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

**Comment by grigio** [comment]
did you run `npm install` ?

**Comment by felipecaldas** [comment]
Well, that was silly of me. That was indeed the issue. Didnt think to run the install after the pull.
closing.

**Comment by DeviaVir** [comment]
Fourth issue I find with the same problem, starting to wonder if we should add an `update` section in the `README`, instead of assuming people know how to update.

**Comment by grigio** [comment]
Probably an upgrade section for classic npm an docker
