### ISSUE TITLE
crashes when receives a 408 http code

### ISSUE THREAD

**Issue by alexanderscott** [DeviaVir/zenbot#225]
running on ubuntu 16.04, node v6.10.3

crash output:

```
{ Error: non-200 status: 408
    at statusErr (/home/alex/projects/zenbot/extensions/gdax/exchange.js:26:17)
    at /home/alex/projects/zenbot/extensions/gdax/exchange.js:54:25
    at Request._callback (/home/alex/projects/zenbot/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/home/alex/projects/zenbot/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/alex/projects/zenbot/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/alex/projects/zenbot/node_modules/request/request.js:965:12) code: 'HTTP_STATUS', body: null }
```

**Comment by carlos8f** [comment]
This is fixed in master branch, GDAX extension now retries the request when there's a non-200 status.

**Comment by alexanderscott** [comment]
thanks!
