### ISSUE TITLE
Order cancelled error occurs randomly

### ISSUE THREAD

**Issue by zhaozdi** [DeviaVir/zenbot#235]
Running zenbot 4.0.5 in docker on a google cloud vps, get this error randomly. 
```
{ Error: order cancelled
    at Timeout.checkOrder [as _onTimeout] (/app/lib/engine.js:227:25)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
  order: 
   { price: '30.69',
     size: '0.15773106',
     orig_size: '0.15773106',
     orig_price: '30.51',
     product_id: 'LTC-USD',
     post_only: true,
     side: 'buy',
     order_id: '1a2c081c-72ee-4ebd-9ee5-6b06b666b19a',
     orig_time: 1496809810269,
     time: 1496809955428,
     local_time: 1496809955441,
     status: 'pending' },
  desc: 'could not execute buy: error placing order' }
```
Latency time to api.gdax.com is about 1ms, so I do not think it is caused by network problem.
Does any one know the real cause of this problem and how to fix it? Thanks.

**Comment by DeviaVir** [comment]
It is possible your order was not filled on time, or funds were on hold at GDAX. It might help to check your parameters.

**Comment by carlos8f** [comment]
no longer an issue with zenbot master branch.
