### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 46.

### ISSUE THREAD

**Issue by ToX82** [DeviaVir/zenbot#24]
I have installed Zenbot using the instructions here, but when I try to launch `./run` I am having this error:

```
/home/tox/Scrivania/zenbot/node_modules/bindings/bindings.js:83
    throw e
    ^

Error: Module version mismatch. Expected 48, got 46.
at Error (native)
at Object.Module._extensions..node (module.js:568:18)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
at Module.require (module.js:468:17)
at require (internal/module.js:20:19)
at bindings (/home/tox/Scrivania/zenbot/node_modules/bindings/bindings.js:76:44)
at Object.<anonymous> (/home/tox/Scrivania/zenbot/node_modules/microtime/index.js:1:96)
at Module._compile (module.js:541:32)
```

MongoDB is at version 3.2.8
Node.JS is 6.3.1

**Comment by ghostnegotiator** [comment]
Your currently using old modules,

Update them trough:

```
npm install
npm install zenbrain
```

Otherwise use:

```
sh update.sh
```

**Comment by ToX82** [comment]
Wow fast! Thanks :)

I did it, but nothing has changed:

```
tox@portatilone:~/Scrivania/zenbot$ npm install
npm WARN zenbot_trader@3.1.2 No repository field.
npm WARN zenbot_trader@3.1.2 No license field.

tox@portatilone:~/Scrivania/zenbot$ npm install zenbrain
zenbot_trader@3.1.2 /home/tox/Scrivania/zenbot
└─┬ zenbrain@1.0.0-alpha      (git+https://github.com/carlos8f/zenbrain.git#e3d5b6430da645f44a420007fb90d34753ee67cf)
  └── numbro@1.8.1      (git+https://github.com/carlos8f/numbro.git#e6e9a0d5f4c32939a7c19cf1546c7766b38cd31f)

npm WARN zenbot_trader@3.1.2 No repository field.
npm WARN zenbot_trader@3.1.2 No license field.
tox@portatilone:~/Scrivania/zenbot$ ./run.sh 
/home/tox/Scrivania/zenbot/node_modules/bindings/bindings.js:83
    throw e
    ^

Error: Module version mismatch. Expected 48, got 46.
at Error (native)
at Object.Module._extensions..node (module.js:568:18)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
at Module.require (module.js:468:17)
at require (internal/module.js:20:19)
at bindings (/home/tox/Scrivania/zenbot/node_modules/bindings/bindings.js:76:44)
at Object.<anonymous> (/home/tox/Scrivania/zenbot/node_modules/microtime/index.js:1:96)
at Module._compile (module.js:541:32)
```

**Comment by ToX82** [comment]
I have tried with ./update.sh too, but the local repository is `Already up-to-date`

**Comment by ghostnegotiator** [comment]
Could you re create your config.json? (Since it updated a _several_ times :) )

**Comment by carlos8f** [comment]
`Error: Module version mismatch. Expected 48, got 46.`

Means you compiled microtime module on a different version of node than you're running now.

```
cd /home/tox/Scrivania/zenbot
rm -Rf node_modules
npm install
```

should fix it

**Comment by ToX82** [comment]
Reinstalled node modules, now the error is

```
tox@portatilone:~/Scrivania/zenbot$ ./run.sh 
/home/tox/Scrivania/zenbot/node_modules/mongodb/lib/mongo_client.js:210
      throw err
      ^

ReferenceError: cb is not defined
at /home/tox/Scrivania/zenbot/node_modules/zenbrain/core/launcher/launcher.js:17:18
at /home/tox/Scrivania/zenbot/node_modules/motley/hooks/runMount.js:5:25
at /home/tox/Scrivania/zenbot/node_modules/motley/hooks/runBoot.js:4:23
at /home/tox/Scrivania/zenbot/node_modules/motley/hooks/runHook.js:5:23
at end (/home/tox/Scrivania/zenbot/node_modules/run-series/index.js:8:15)
at done (/home/tox/Scrivania/zenbot/node_modules/run-series/index.js:11:10)
at each (/home/tox/Scrivania/zenbot/node_modules/run-series/index.js:16:43)
at /home/tox/Scrivania/zenbot/node_modules/motley-mongo/db/connectMongo.js:7:23
at connectCallback (/home/tox/Scrivania/zenbot/node_modules/mongodb/lib/mongo_client.js:300:5)
at /home/tox/Scrivania/zenbot/node_modules/mongodb/lib/mongo_client.js:207:11
```

:(

**Comment by grigio** [comment]
@ToX82 now it's mongodb unavailable @ localhost:27017 see config.js

**Comment by ToX82** [comment]
@grigio you were right, I was actually missing something in my mongodb installation... thank you all!

**Comment by grigio** [comment]
Maybe it's worth to catch this exception in `zenbrain/core/launcher/launcher.js:17:18` and print some more informative output

**Comment by carlos8f** [comment]
should be `throw err`, fixed in zenbrain/zenbot master

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
