### ISSUE TITLE
./zenbot backfill FAILED

### ISSUE THREAD

**Issue by rasdehya** [DeviaVir/zenbot#251]
At my first lauch of zenbot, i get this:
```
Object.keys(data.result[args.pair]).forEach(function (i) {
               ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at KrakenClient.<anonymous> (/home/ryms/PYTHON/project/NODE.JS/zenbot/extensions/exchanges/kraken/exchange.js:88:16)
    at Request._callback (/home/ryms/PYTHON/project/NODE.JS/zenbot/node_modules/kraken-api/kraken.js:159:22)
    at Request.self.callback (/home/ryms/PYTHON/project/NODE.JS/zenbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/ryms/PYTHON/project/NODE.JS/zenbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/ryms/PYTHON/project/NODE.JS/zenbot/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```
And sorry if it's too obvious, I'm quite new in computer (ex= it has been hard to set up Nodejs and mongo in first place)

**Comment by DeviaVir** [comment]
What command did you use to get this output?

**Comment by rasdehya** [comment]
sorry i'm so noob... i just start learninng programming ... computer...
web-dev... all in same time.. and now crypto,  trading,  and bot!!! 
only few times ago....  

I simply lauch ./zenbot backfill without the kraken.XETH-ZEUR that's
why...

Every day i learn a little....

Congratulation for your work and thanks for sharing.
Each one teach one rasta
