### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by joker5bb** [DeviaVir/zenbot#252]
zenbot backfill poloniex.BTC-USDT
/home/user/zenbot/node_modules/bitfinex-api-node/index.js:11
  constructor (apiKey, apiSecret, opts = { version: 1, transform: false }) {
                                       ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/zenbot/extensions/exchanges/bitfinex/exchange.js:1:75)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by DeviaVir** [comment]
What `node` version do you have installed?

```
node --version
```

**Comment by msisco** [comment]
I'm getting this also, my node version is 4.2.6

**Comment by DeviaVir** [comment]
@msisco the latest LTS is 6.x and latest is 8.x, could you install a newer version of nodejs and try again?
https://nodejs.org/en/

**Comment by msisco** [comment]
Awesome! Fixed after installing 8.x

**Comment by crubb** [comment]
Got the same error with nodejs 4, should we implement a version check?

**Comment by DeviaVir** [comment]
@crubb I think that would be useful, opened: https://github.com/carlos8f/zenbot/issues/259
