### ISSUE TITLE
Kraken API returned error: General:Invalid arguments:postonly

### ISSUE THREAD

**Issue by nibzo1** [DeviaVir/zenbot#254]
I've received this error in the bot log several times today and no orders seem to execute.

This only seems to happen after pulling the latest changes from master, I also enabled taker for market orders. Not sure if this has caused it or not. Sim appears to work correctly, just seem to get this exception when the bot tries to place an order. 

I see some of the post_only code was added / edited a month ago but have not seen this issue before.

Perhaps someone using Kraken API may have seen this unsupported parameter issue before
```
{
    Error: order rejected
    at / home / kraken / zbot / lib / engine.js: 226: 23
    at KrakenClient. < anonymous > (/home/kraken / zbot / extensions / exchanges / kraken / exchange.js: 224: 20)
    at Request._callback(/home/kraken / zbot / node_modules / kraken - api / kraken.js: 155: 23)
    at Request.self.callback(/home/kraken / zbot / node_modules / request / request.js: 188: 22)
    at emitTwo(events.js: 106: 13)
    at Request.emit(events.js: 191: 7)
    at Request. < anonymous > (/home/kraken / zbot / node_modules / request / request.js: 1171: 10)
    at emitOne(events.js: 96: 13)
    at Request.emit(events.js: 188: 7)
    at IncomingMessage. < anonymous > (/home/kraken / zbot / node_modules / request / request.js: 1091: 12)
    at IncomingMessage.g(events.js: 292: 16)
    at emitNone(events.js: 91: 20)
    at IncomingMessage.emit(events.js: 185: 7)
    at endReadableNT(_stream_readable.js: 974: 12)
    at _combinedTickCallback(internal / process / next_tick.js: 80: 11)
    at process._tickCallback(internal / process / next_tick.js: 104: 9)
    order: {
        id: null,
        status: 'rejected',
        price: '0.10431350',
        size: '5.11381288',
        post_only: true,
        created_at: 1497088254385,
        filled_size: '0',
        reject_reason: 'Kraken API returned error: General:Invalid arguments:postonly'
    },
    desc: 'could not execute buy: error placing order'
}
```

**Comment by DeviaVir** [comment]
@nibzo1 would you mind testing with https://github.com/carlos8f/zenbot/pull/255?

**Comment by nibzo1** [comment]
yes sure, I will drop in the change and report back later this afternoon

**Comment by nibzo1** [comment]
@DeviaVir so the bot has been running now for some time and the error has now changed to an error about and invalid api key. This is strange as the bot does not even start if the API key is incorrect 

Followed by by a temp account lockout :(

```
{ Error: order rejected
    at /home/kraken/zbot/lib/engine.js:226:23
    at KrakenClient.<anonymous> (/home/kraken/zbot/extensions/exchanges/kraken/exchange.js:221:20)
    at Request._callback (/home/kraken/zbot/node_modules/kraken-api/kraken.js:155:23)
    at Request.self.callback (/home/kraken/zbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/kraken/zbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/kraken/zbot/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  order:
   { id: null,
     status: 'rejected',
     price: '0.10882150',
     size: '3.95758435',
     post_only: false,
     created_at: 1497115225001,
     filled_size: '0',
     reject_reason: 'Kraken API returned error: API:Invalid key' },
  desc: 'could not execute buy: error placing order' }
```
