### ISSUE TITLE
Run time error "cannot find module concat-map"

### ISSUE THREAD

**Issue by msisco** [DeviaVir/zenbot#279]
Just pulled the latest today and am getting this error when I try to run any zenbot command.
Node v8.1.0 

Error: Cannot find module 'concat-map'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/zenbot/zenbot/node_modules/brace-expansion/index.js:1:79)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by egorbenko** [comment]
remove package.lock and run npm install
