### ISSUE TITLE
Could not execute buy.

### ISSUE THREAD

**Issue by kusayuzayushko** [DeviaVir/zenbot#282]
Every time i'm trying to use manual buy fiture i'm getting the same error.

```
$ buy poloniex.ETH-BTC
placing order...
placing order...
placing order...
placing order...
placing order...
placing order...
placing order...
placing order...
placing order...
placing order...
placing order...
placing order...
{ Error: unable to buy
    at /home/kusayu/zenbot/extensions/exchanges/poloniex/exchange.js:197:17
    at Request._callback (/home/kusayu/zenbot/node_modules/poloniex.js/lib/poloniex.js:79:7)
    at Request.self.callback (/home/kusayu/zenbot/node_modules/poloniex.js/node_modules/request/request.js:122:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/kusayu/zenbot/node_modules/poloniex.js/node_modules/request/request.js:888:14)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/kusayu/zenbot/node_modules/poloniex.js/node_modules/request/request.js:839:12)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  body: { error: 'Order execution timed out.' },
  desc: 'could not execute buy: error placing order' }
```
How can i fix it?

**Comment by DeviaVir** [comment]
Sounds like you cannot connect to the API. Closing this ticket due to inactivity.
