### ISSUE TITLE
Bitfinex live trade crash

### ISSUE THREAD

**Issue by louisswart** [DeviaVir/zenbot#292]
I created the conf.js and simulated, all works fine.

The when I want to trade live I use the following command and get the error below:
> zenbot trade
...
---------------------------- STARTING LIVE TRADING ----------------------------
2017-06-15 23:28:00  2358.70 BTC-USD   -0.5%      220      ++      -0.93%      buy  0.00000 BTC  1345.42 USD    +0.0%   +0.5%
2017-06-15 23:28:29  2355.70 BTC-USD   -0.1%       63      ++      -0.80%   buying  0.00000 BTC  1345.42 USD    +0.0%   +0.6%
D:\Software\Zenbot\zenbot-master\extensions\exchanges\bitfinex\exchange.js:139
        if (body.is_live === true) {
                ^
TypeError: Cannot read property 'is_live' of undefined
    at D:\Software\Zenbot\zenbot-master\extensions\exchanges\bitfinex\exchange.js:139:17
    at Request.error1 [as _callback] (D:\Software\Zenbot\zenbot-master\node_modules\bitfinex-api-node\rest.js:61:14)
    at Request.self.callback (D:\Software\Zenbot\zenbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\Software\Zenbot\zenbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\Software\Zenbot\zenbot-master\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

I can see that zenbot is able to get the correct balance from my Bitfinex account, so the API key/secret is correct. Its when it starts "buying" that there is an error.

**Comment by nedievas** [comment]
That is already corrected, though "masters" are slow to merge it.

**Comment by DeviaVir** [comment]
https://github.com/carlos8f/zenbot/pull/288
