### ISSUE TITLE
Raspberry Pi Errors

### ISSUE THREAD

**Issue by megrimm** [DeviaVir/zenbot#3]
Hello,
I just tried your software on RPI and got the following errors.

Thanks!

pi@raspberrypi:~/Development/bitcoin/zenbot $ npm install && npm link
npm WARN package.json zenbot_btc@2.7.0 No repository field.

> microtime@2.1.1 install /home/pi/Development/bitcoin/zenbot/node_modules/timebucket/node_modules/microtime
> node-gyp rebuild

make: Entering directory '/home/pi/Development/bitcoin/zenbot/node_modules/timebucket/node_modules/microtime/build'
  CXX(target) Release/obj.target/microtime/src/microtime.o
In file included from ../src/microtime.cc:9:0:
../node_modules/nan/nan.h:324:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
microtime.target.mk:82: recipe for target 'Release/obj.target/microtime/src/microtime.o' failed
make: **\* [Release/obj.target/microtime/src/microtime.o] Error 1
make: Leaving directory '/home/pi/Development/bitcoin/zenbot/node_modules/timebucket/node_modules/microtime/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.11-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/Development/bitcoin/zenbot/node_modules/timebucket/node_modules/microtime
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN engine safefs@4.1.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine requirefresh@2.1.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! microtime@2.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the microtime@2.1.1 install script.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.11-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Development/bitcoin/zenbot
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Development/bitcoin/zenbot/npm-debug.log
npm ERR! not ok code 0

**Comment by megrimm** [comment]
also just tried on amd64 ubuntu. seems like a prob. with node-microtime.

**Comment by megrimm** [comment]
needed to do:

npm -g install npm

then microtime compiles
