### ISSUE TITLE
Error Running Zenbot on Mac - Cannot find module 'options'

### ISSUE THREAD

**Issue by mc9090** [DeviaVir/zenbot#310]
I receive the following error with the new Zenbot version on Mac Sierra. I have tried a complete install and still receive the same error trying to find the 'options' module. Please advise. Thank you.

zenbot backfill gdax.BTC-USD --days 14
module.js:487
    throw err;
    ^

Error: Cannot find module 'options'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/agitate/zenbot/node_modules/gdax/node_modules/ws/lib/WebSocket.js:16:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/agitate/zenbot/node_modules/gdax/node_modules/ws/index.js:9:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/agitate/zenbot/node_modules/gdax/lib/clients/websocket.js:2:17)
    at Module._compile (module.js:569:30)

**Comment by nao0811ta** [comment]
Did you run npm install?

**Comment by DeviaVir** [comment]
this is for sure a missing `npm install`

**Comment by mc9090** [comment]
Hmmm - I am very capable of being a noob. I validated both node and nsm.

Node -v equals 8.1.2
Npm -v equals 5.0.3

I have two other zenbot 4 nodes running on Mac Sierra with the same versions that are running without issue. I also have Xcode dev tools installed as a prerequisite for node.js. I appreciate the pointer - any other suggestions?

Thanks
Marc

**Comment by mc9090** [comment]
I fell back to node v 6 to fix the issue

**Comment by mc9090** [comment]
Thank you for pointing me in the right direction. It ended up being the version. I fell back to node v 6 and installed. It works fine now. Thanks!
