### ISSUE TITLE
sim output to file broken on non root dir of zenbot

### ISSUE THREAD

**Issue by nedievas** [DeviaVir/zenbot#317]
**Broken:**
```
rebootfin@zenbot:~/zenbot/extensions/exchanges/bitfinex$ zenbot sim  bitfinex.iot-usd
2017-06-20 20:21:11  0.43 IOT-USD   +0.1%      124      ++      0.0422   0.0428    -0.3%   173.27 IOT     0.89 USD   -92.4%  -95.6%
{
  "asset_capital": 0,
  "avg_slippage_pct": 0.045,
  "buy_pct": 99,
  "buy_stop_pct": 0,
  "currency_capital": 1000,
  "days": 14,
  "markup_pct": 0,
  "max_sell_loss_pct": 25,
  "max_slippage_pct": 5,
  "min_periods": 52,
  "mode": "sim",
  "neutral_rate": "auto",
  "order_adjust_time": 30000,
  "order_type": "maker",
  "oversold_rsi": 10,
  "oversold_rsi_periods": 14,
  "period": "2m",
  "profit_stop_enable_pct": 0,
  "profit_stop_pct": 1,
  "rsi_periods": 14,
  "selector": "bitfinex.IOT-USD",
  "sell_pct": 99,
  "sell_stop_pct": 0,
  "start": 1496707200000,
  "stats": false,
  "strategy": "trend_ema",
  "trend_ema": 26,
  "verbose": false
}
end balance: 76.32807095 (-92.37%)
buy hold: 1741.44000000 (74.14%)
vs. buy hold: -95.62%
319 trades over 9 days (avg 35.44 trades/day)
win/loss: 19/139
error rate: 87.97%
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open 'simulations/sim_result_bitfinex.IOT-USD_170620_202613_UTC.html'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at exitSim (/home/rebootfin/zenbot/commands/sim.js:161:14)
    at Object.exit (/home/rebootfin/zenbot/lib/engine.js:817:9)
    at Object.<anonymous> (/home/rebootfin/zenbot/commands/sim.js:203:22)
    at Immediate.<anonymous> (/home/rebootfin/zenbot/node_modules/sosa/api.js:15:12)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
rebootfin@zenbot:~/zenbot/extensions/exchanges/bitfinex$ 
```
**Working:**
```
rebootfin@zenbot:~/zenbot/extensions/exchanges/bitfinex$ cd -
/home/rebootfin/zenbot
rebootfin@zenbot:~/zenbot$ zenbot sim  bitfinex.iot-usd
2017-06-20 20:21:11  0.43 IOT-USD   +0.1%      124      ++      0.0422   0.0428    -0.3%   173.27 IOT     0.89 USD   -92.4%  -95.6%
{
  "asset_capital": 0,
  "avg_slippage_pct": 0.045,
  "buy_pct": 99,
  "buy_stop_pct": 0,
  "currency_capital": 1000,
  "days": 14,
  "markup_pct": 0,
  "max_sell_loss_pct": 25,
  "max_slippage_pct": 5,
  "min_periods": 52,
  "mode": "sim",
  "neutral_rate": "auto",
  "order_adjust_time": 30000,
  "order_type": "maker",
  "oversold_rsi": 10,
  "oversold_rsi_periods": 14,
  "period": "2m",
  "profit_stop_enable_pct": 0,
  "profit_stop_pct": 1,
  "rsi_periods": 14,
  "selector": "bitfinex.IOT-USD",
  "sell_pct": 99,
  "sell_stop_pct": 0,
  "start": 1496707200000,
  "stats": false,
  "strategy": "trend_ema",
  "trend_ema": 26,
  "verbose": false
}
end balance: 76.32807095 (-92.37%)
buy hold: 1741.44000000 (74.14%)
vs. buy hold: -95.62%
319 trades over 9 days (avg 35.44 trades/day)
win/loss: 19/139
error rate: 87.97%
wrote simulations/sim_result_bitfinex.IOT-USD_170620_203031_UTC.html
rebootfin@zenbot:~/zenbot$ 
```

**Comment by DeviaVir** [comment]
Looks like we will want to set that to the root of our app, always.

**Comment by arphen** [comment]
My genetic algorithm needs a directory now :) Would be cool if you could hardwire it to root of the app, then I can delete the "simulations" directory.

**Comment by LoneWolf345** [comment]
Are you still experiencing this problem?  If not, consider closing this.
