### ISSUE TITLE
Error: Cannot find module 'quadrigacx'

### ISSUE THREAD

**Issue by dymex0** [DeviaVir/zenbot#350]
docker-compose up result:

```
server_1        | module.js:487
server_1        |     throw err;
server_1        |     ^
server_1        |
server_1        | Error: Cannot find module 'quadrigacx'
server_1        |     at Function.Module._resolveFilename (module.js:485:15)
server_1        |     at Function.Module._load (module.js:437:25)
server_1        |     at Module.require (module.js:513:17)
server_1        |     at require (internal/module.js:11:18)
server_1        |     at Object.<anonymous> (/app/extensions/exchanges/quadriga/exchange.js:1:80)
server_1        |     at Module._compile (module.js:569:30)
server_1        |     at Object.Module._extensions..js (module.js:580:10)
server_1        |     at Module.load (module.js:503:32)
server_1        |     at tryModuleLoad (module.js:466:12)
server_1        |     at Function.Module._load (module.js:458:3)
server_1        |     at Module.require (module.js:513:17)
server_1        |     at require (internal/module.js:11:18)
server_1        |     at Object.<anonymous> (/app/extensions/exchanges/quadriga/_codemap.js:5:25)
server_1        |     at Module._compile (module.js:569:30)
server_1        |     at Object.Module._extensions..js (module.js:580:10)
server_1        |     at Module.load (module.js:503:32)
server_1        |     at tryModuleLoad (module.js:466:12)
server_1        |     at Function.Module._load (module.js:458:3)
server_1        |     at Module.require (module.js:513:17)
server_1        |     at require (internal/module.js:11:18)
server_1        |     at /app/boot.js:25:19
server_1        |     at Array.forEach (native)
```

**Comment by vaisov** [comment]
`npm install` solves the issue

**Comment by jonathanenlared** [comment]
I run docker-compose build and the output was: Successfully built. So how does nmp install solves? 
![screen shot 2017-07-04 at 2 17 48 p m](https://user-images.githubusercontent.com/2179798/27840008-9b41fb92-60c3-11e7-9bc2-9b770e0e9153.png)

**Comment by DeviaVir** [comment]
`rm -rf package-lock.json && docker-compose up -d --build` should do the trick
