### ISSUE TITLE
Getting Zenbot Crash

### ISSUE THREAD

**Issue by mxaddict** [DeviaVir/zenbot#355]
Zenbot Crash with the following log

```
/home/mxaddict/Projects/zenbot/lib/engine.js:93
        if (str.split('.')[1].length === 7) str += '0'
                             ^

TypeError: Cannot read property 'length' of undefined
    at fc (/home/mxaddict/Projects/zenbot/lib/engine.js:93:30)
    at /home/mxaddict/Projects/zenbot/lib/engine.js:232:44
    at /home/mxaddict/Projects/zenbot/extensions/exchanges/bitfinex/exchange.js:173:18
    at Request.request [as _callback] (/home/mxaddict/Projects/zenbot/node_modules/bitfinex-api-node/rest.js:61:14)
    at Request.self.callback (/home/mxaddict/Projects/zenbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/mxaddict/Projects/zenbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/mxaddict/Projects/zenbot/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

```

**Comment by nedievas** [comment]
Please provide info how to reproduce this error.

**Comment by mxaddict** [comment]
Conf file here:

```javascript
var c = module.exports = {}

// CUSTOM CONF for TRADE STRAT
c.selector          = 'bitfinex.XMR-BTC'
c.strategy          = 'trend_ema'
c.period            = '1m'
c.trend_ema         = 5
c.oversold_rsi      = 20
c.order_type        = 'maker'
c.buy_pct           = 50
c.sell_pct          = 50
c.poll_trades       = 30000
c.order_poll_time   = 5000
c.order_adjust_time = 10000
```

Command run

```
zenbot trade --conf=conf-xmr.js
```

**Comment by mxaddict** [comment]
Created PR #361 to fix this crash that I experienced.
