### ISSUE TITLE
Mongo Issues

### ISSUE THREAD

**Issue by AGZ98** [DeviaVir/zenbot#359]
> ~/zenbot$ zenbot trade
fetching pre-roll data:
(node:15518) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: not authorized on zenbot4 to execute command { listIndexes: "trades", cursor: {} }
(node:15518) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15518) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: not authorized on zenbot4 to execute command { listIndexes: "resume_markers", cursor: {} }
(node:15529) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: not authorized on zenbot4 to execute command { listIndexes: "trades", cursor: {} }
(node:15529) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15529) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: not authorized on zenbot4 to execute command { listIndexes: "resume_markers", cursor: {} }
/home/ubuntu/zenbot/commands/backfill.js:52
          if (err) throw err
                   ^
MongoError: not authorized on zenbot4 to execute command { find: "resume_markers", filter: { selector: "gdax.BTC-USD" } }
    at Function.MongoError.create (/usr/local/lib/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/usr/local/lib/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /usr/local/lib/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

Keep getting the above error when running Zenbot trade. It looks like there is an issue with setting up the mongo db. I used this tutorial to set up mongo: [https://www.howtoforge.com/tutorial/install-mongodb-on-ubuntu-16.04/](url)
Anyone know the reason behind this?

**Comment by ghost** [comment]
It looks like a permissions issue, is mongod running?

service status mongod

then:
```
/ mongo configuration
c.mongo = {}
c.mongo.host = process.env.MONGODB_PORT_27017_TCP_ADDR || 'localhost' ##check with netstat or check mongod configuration
c.mongo.port = 27017
c.mongo.db = 'zenbot4'
c.mongo.username = null #username with permissions
c.mongo.password = null #password with permissions
// when using mongodb replication, i.e. when running a mongodb cluster, you can define your replication set here; when you are not using replication (most of the users), just set it to `null` (default).
c.mongo.replicaSet = null

```

then on your linux system:

```
mongo
use admin
// Create root user
db.createUser({ user:"root", pwd:"SUPERSECUREPASSWORD", roles: [{ role:"root", db:"admin" }] })
Edit the service to run secured and save
sudo nano /lib/systemd/system/mongod.service
modify the following line
ExecStart=/usr/bin/mongod --quiet --auth --config /data/mongo/mongod.conf

Restart the service
sudo service mongod restart

Access the server with credentials
mongo -u root -p "SUPERSECUREPASSWORD" --authenticationDatabase admin

Add user-account(s)

db.createUser({ user:"dataload", pwd:"SUPERSECUREPASSWORD", roles: [ { role:"dbOwner", db:"magic" } ] })
```

then run

```
mongo > show dbs
use zenbot4
```

That will create the database

Reference:
https://github.com/Automattic/mongoose/issues/4717
http://theholmesoffice.com/how-to-create-a-mongodb-database/

**Comment by DeviaVir** [comment]
Closing due to inactivity.
