### ISSUE TITLE
Sell or Buy --size issue

### ISSUE THREAD

**Issue by nedievas** [DeviaVir/zenbot#370]
I'm having issue with buying or selling amount which is > than balance.

**Poloniex** account is empty:
```
rebootfin@zenbot:~/zenbot$ zenbot sell --pct 99 --markup_pct 5 --size=10 --debug poloniex.btc-usdt

2017-07-08 14:31:49 - sell delayed: NaN% of funds (0.00000000 BTC) on hold
placing order...
placing order...

2017-07-08 14:32:00 - sell delayed: NaN% of funds (0.00000000 BTC) on hold
placing order...
^C
rebootfin@zenbot:~/zenbot$
```
**Bitfinex** has some asset (~0.03 BTC) left:
```
rebootfin@zenbot:~/zenbot$ zenbot sell --pct 99 --markup_pct 5 --size=10 --debug bitfinex.btc-usd

2017-07-08 14:43:39 - sell delayed: +0.0% of funds (0.00000000 BTC) on hold
placing order...
^C
rebootfin@zenbot:~/zenbot$
```
**Bitstamp** account is empty:
```
rebootfin@zenbot:~/zenbot$ zenbot sell --pct 99 --markup_pct 5 --size=10 --debug bitstamp.btc-usd

2017-07-08 15:27:03 - sell delayed: +0.0% of funds (0.00000000 BTC) on hold
placing order...

2017-07-08 15:27:08 - sell delayed: +0.0% of funds (0.00000000 BTC) on hold
^C
rebootfin@zenbot:~/zenbot$

```
Shouldn't it show error or message of not enough funds? It ignores reject_reason "balance" in sell or buy functions.

Interesting! I get the right message with **negative** size:
```
rebootfin@zenbot:~/zenbot$ zenbot sell --pct 99 --markup_pct 5 --size=-10 --debug bitfinex.btc-usd
not enough asset balance to sell!
rebootfin@zenbot:~/zenbot$ zenbot sell --pct 99 --markup_pct 5 --size=-10 --debug poloniex.btc-usdt
not enough asset balance to sell!
rebootfin@zenbot:~/zenbot$
```
Maybe it is an issue in other exchanges? I don't have accounts on them to test.

**Comment by ghost** [comment]
--markup_pct 5  is too much normally for poloniex to accept. 

I don't know why... Try --debug

But I get this same error to be honest.:   

API Is down, which I think stops the programs checkbalance function loop.

then I get:
```

{ Error: unable to sell
    at /zenbot0/extensions/exchanges/poloniex/exchange.js:197:17
    at Request._callback (/zenbot0/node_modules/poloniex.js/lib/poloniex.js:79:7)
    at Request.self.callback (/zenbot0/node_modules/poloniex.js/node_modules/request/request.js:122:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/zenbot0/node_modules/poloniex.js/node_modules/request/request.js:888:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/zenbot0/node_modules/poloniex.js/node_modules/request/request.js:839:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  body: { error: 'Nonce must be greater than 149957786662300. You provided 149957786575900.' },
  desc: 'could not execute sell: error placing order' }

```
I think this one is due to this:
https://stackoverflow.com/questions/15401211/date-vs-date-gettime

Which, I'm trying out now. Also set my time server to sync every minute.

I noticed this in the poloniex api documentation -> 

> Additionally, all queries must include a "nonce" POST parameter. The nonce parameter is an integer which must always be greater than the previous nonce used.


```


2017-07-09 00:04:00  0.02180148 OMNI-BTC   +3.8%        5      ++      0.2183   0.1112      buy  0.00 OMNI  0.00048 BTC    +0.0%   -2.7%
2017-07-09 00:05:20  0.02118033 OMNI-BTC   -2.8%        1      +      -0.0151   0.1207           0.00 OMNI  0.00048 BTC    +0.0%   +0.1%ggetBalance error:
{ error: 'Nonce must be greater than 149957672675000. You provided 149957672674400.' }

Poloniex API is down! unable to call getBalance, retrying in 10s

2017-07-09 00:05:40 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold

2017-07-09 00:05:45 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold

2017-07-09 00:05:51 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold

2017-07-09 00:05:56 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold
2017-07-09 00:05:20  0.02118033 OMNI-BTC   -2.8%        1      +      -0.0151   0.1207           0.00 OMNI  0.00048 BTC    +0.0%   +0.1%
2017-07-09 00:06:01 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold
2017-07-09 00:05:20  0.02118033 OMNI-BTC   -2.8%        1      +      -0.0151   0.1207           0.00 OMNI  0.00048 BTC    +0.0%   +0.1%
2017-07-09 00:06:11 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold

2017-07-09 00:06:21 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold

2017-07-09 00:06:26 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold
2017-07-09 00:06:00  0.02118033 OMNI-BTC   -2.8%        1      +      -0.0151   0.1207           0.00 OMNI  0.00048 BTC    +0.0%   +0.1%
2017-07-09 00:06:01  0.02118033 OMNI-BTC   +0.0%        0      +      -0.0140   0.1023           0.00 OMNI  0.00048 BTC    +0.0%   +0.1%
2017-07-09 00:06:36 - placing buy order...

2017-07-09 00:06:42 - buy order placed at 0.02117289 BTC
2017-07-09 00:06:01  0.02118033 OMNI-BTC   +0.0%        0      +      -0.0140   0.1023   buying  0.00 OMNI  0.00048 BTC    +0.0%   +0.1%
2017-07-09 00:07:16 - 0.02117661 vs our 0.02117289

2017-07-09 00:07:20 - buy order timed out, adjusting price

2017-07-09 00:07:21 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold
2017-07-09 00:06:01  0.02118033 OMNI-BTC   +0.0%        0      +      -0.0140   0.1023   buying  0.00 OMNI  0.00048 BTC    +0.0%   +0.1%
2017-07-09 00:07:33 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold

2017-07-09 00:07:38 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold

2017-07-09 00:07:43 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold

2017-07-09 00:07:48 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold
ggetBalance error:
{ error: 'Nonce must be greater than 149957687674700. You provided 149957687361500.' }

Poloniex API is down! unable to call getBalance, retrying in 10s
2017-07-09 00:06:01  0.02118033 OMNI-BTC   +0.0%        0      +      -0.0140   0.1023   buying  0.00 OMNI  0.00048 BTC    +0.0%   +0.1%
2017-07-09 00:08:06 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold

2017-07-09 00:08:11 - buy delayed: +0.0% of funds (0.00000000 BTC) on hold

```

Which I think is a time issue maybe with javascript? 

Maybe this?

**Comment by nedievas** [comment]
@TheRoboKitten you are wrong. I'm already debugging. You may remove --markup_pct and test only --size. There will be the same issue. That should be corrected and it is not exchange.js problem.

**Comment by ghost** [comment]
Totally got ya, I tried all of that stuff and got the same errors.

**Comment by ghost** [comment]
I'm trying to update nodejs on centos, I think that node >7.10.0 is too slow.

NPM installed node 6.10.3 on my machine, and I had to uninstall npm to install node 8.

Try that :)

The command for the node version is node -v

**Comment by nedievas** [comment]
@TheRoboKitten, do you propose this as a solution? And it works?

**Comment by ghost** [comment]
@nedievas 

Well after testing, I still get nonce issues no matter what. The nonce issue is what causes everything to not work sometimes with poloniex.  Node 8 seemed to work better, as well as modifying my time to be two minutes ahead. But I've tried everything and still get nonce errors.

Its mostly with my sell orders, when I get a nonce error the sell order completely stops and is tricked into being completed so the price does not actively change around.

I did have my price update set too fast in my config before and the orders would cancel and re-open too fast. (why I got so many issues with my manual sells at first and buys.)

**Comment by nedievas** [comment]
I do not get nonce errors on bitfinex and bitstamp. You are digging the wrong place.

**Comment by blisk92** [comment]
I was looking at the products.json of bittrex exchange and noticed that if you are trading in ETH markets ETH is set as the ASSET and the token you are BUYING and SELLING is set to CURRENCY. Could this be the cause?

**Comment by DeviaVir** [comment]
@nedievas is this still an active issue?

**Comment by nedievas** [comment]
@DeviaVir It is.

Recent test with zero LTC balance :
```
[nedievas@nedievas cexio]$ zenbot sell --pct 99 --markup_pct 5 --size=10 --debug bitfinex.ltc-usd

WebSockets: We are now fully connected and authenticated.
placing order...
placing order...

2017-09-19 14:09:43 - sell delayed: NaN% of funds (0.00000000 LTC) on hold
placing order...

2017-09-19 14:09:48 - sell delayed: NaN% of funds (0.00000000 LTC) on hold
placing order...

2017-09-19 14:09:53 - sell delayed: NaN% of funds (0.00000000 LTC) on hold
^C
[nedievas@nedievas cexio]$ zenbot sell --pct 99 --markup_pct 5 --size=-10 --debug bitfinex.ltc-usd

WebSockets: We are now fully connected and authenticated.
placing order...
placing order...
not enough asset balance to sell!
```

**Comment by haxwell** [comment]
This is the culprit code in engine.js

```
                if (n(s.balance.asset).subtract(s.balance.asset_hold || 0).value() < n(size).value()) {
                  msg('sell delayed: ' + pct(n(s.balance.asset_hold || 0).divide(s.balance.asset).value()) + ' of funds (' + fa(s.balance.asset_hold) + ') on hold')
                  return setTimeout(function () {
                    if (s.last_signal === signal) {
                      executeSignal(signal, cb, size, true)
                    }
                  }, c.wait_for_settlement)
                }
```

It checks the available asset balance is less than the amount you said to sell. If it is, it waits for some amount of time  and then tries again. If you haven't added assets, the available balance will still be less than the amount you said to sell, and you will get this message again. Rinse and repeat.

The question is, what should happen here? Should it try once, and fail if there is not enough asset? When, if ever, should it loop and wait for more assets, as it is presently doing?

PS. The reason a negative value gives the correct message is that prior to this culprit code, it checks to see if the size requested to sell is less than the minimum size for this product. If it is smaller, as in the case of a negative, it returns, doing nothing. The sell.js code, seeing that no order was placed, displays the error message.

**Comment by glennfu** [comment]
I got this error last night and right now it's my top priority. At first, Zenbot purchased 10 EOS, no problem. My order adjust is 20sec. Zenbot goes back to sell it, adjusting the order price over and over until it finally sells
```
2018-02-22 05:22:35 - sell order timed out, adjusting price
Selling BINANCE: placing sell order at 0.00078497 BTC, 0.00000488 BTC over best ask
2018-02-22 05:22:35 - placing sell order...
2018-02-22 05:22:35 - sell order placed at 0.00078497 BTC
2018-02-22 05:22:54 - 0.00078493 vs! our 0.00078497
2018-02-22 05:22:54 - sell order placed at 0.00078358 BTC
2018-02-22 05:22:54 - sell order timed out, adjusting price
2018-02-22 05:22:54 - sell delayed: +100.00% of funds (10.00000000 EOS) on hold

# I don't know why this got "sell delayed" here, but you can see a partial fill of 8 EOS occurred.

2018-02-22 05:22:54 - sell delayed: +100.00% of funds (2.00000000 EOS) on hold
2018-02-22 05:22:54 - sell delayed: +100.00% of funds (2.00000000 EOS) on hold
2018-02-22 05:22:54 - sell delayed: +100.00% of funds (2.00000000 EOS) on hold
2018-02-22 05:23:36 - sell order timed out, adjusting price
2018-02-22 05:23:36 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 05:23:36 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 05:23:36 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 05:23:36 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 05:23:36 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 05:23:36 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 05:23:36 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 05:23:36 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
```

I think more concerning is that I'm getting this output that many times in the same second. Something is up there.

When I woke up hours later, I had a balance of 2 EOS. I put in an order to sell it, Zenbot semi-noticed:
```
2018-02-22 09:32:34 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 09:32:34 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 09:32:34 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 09:32:34 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 09:32:34 - sell delayed: +0.00% of funds (0.00000000 EOS) on hold
2018-02-22 09:32:34 - sell delayed: +100.00% of funds (2.00000000 EOS) on hold
2018-02-22 09:32:34 - sell delayed: +100.00% of funds (2.00000000 EOS) on hold
2018-02-22 09:32:34 - sell delayed: +100.00% of funds (2.00000000 EOS) on hold
2018-02-22 09:32:34 - sell delayed: +100.00% of funds (2.00000000 EOS) on hold
```

Sell order filled, now I'm seeing:
```
2018-02-22 09:33:06 - sell delayed: NaN% of funds (0.00000000 EOS) on hold
2018-02-22 09:33:06 - sell delayed: NaN% of funds (0.00000000 EOS) on hold
2018-02-22 09:33:06 - sell delayed: NaN% of funds (0.00000000 EOS) on hold
2018-02-22 09:33:06 - sell delayed: NaN% of funds (0.00000000 EOS) on hold
2018-02-22 09:33:06 - sell delayed: NaN% of funds (0.00000000 EOS) on hold
2018-02-22 09:33:06 - sell delayed: NaN% of funds (0.00000000 EOS) on hold
2018-02-22 09:33:06 - sell delayed: NaN% of funds (0.00000000 EOS) on hold
2018-02-22 09:33:06 - sell delayed: NaN% of funds (0.00000000 EOS) on hold
```

Super angry Zenbot. I had to kill it and restart it.
