### ISSUE TITLE
child_process error since last pull 

### ISSUE THREAD

**Issue by talvasconcelos** [DeviaVir/zenbot#379]
Guys i'm having this error since last git pull, on trade only: 

```
fetching pre-roll data:
internal/child_process.js:319
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at Command.<anonymous> (C:\Users\tvasconcelos\Desktop\zenbot\commands\trade.js:100:26)
    at Command.listener (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\commander\index.js:458:21)
    at C:\Users\tvasconcelos\Desktop\zenbot\zenbot.sh:39:11
    at C:\Users\tvasconcelos\Desktop\zenbot\boot.js:28:7
    at f (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\glob\glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\glob\glob.js:197:8)
    at done (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\glob\glob.js:182:14)
    at Glob._processGlobStar2 (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\glob\glob.js:637:12)
    at C:\Users\tvasconcelos\Desktop\zenbot\node_modules\glob\glob.js:626:10
    at RES (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\inflight\inflight.js:31:16)
    at f (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\once\once.js:25:25)
    at lstatcb_ (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\glob\glob.js:519:7)
```

I've used latest node, node 7, node 6.11 node 6.10 they all throw this error. I can do backfill and sim. just the trade command is not working. is it just a windows problem? it's easilly solvable?

**Comment by DeviaVir** [comment]
can you try running a `npm link`?

**Comment by talvasconcelos** [comment]
already did, no luck

**Comment by DeviaVir** [comment]
I think this is a windows problem, and by the inactivity on this ticket, it seems to not occur a lot. Closing this for now. If the issue persists please create a new ticket.
