### ISSUE TITLE
Implement mkmarek/forex.analytics: Genetic analysis to build decision trees for buy and sell signals

### ISSUE THREAD

**Issue by crubb** [DeviaVir/zenbot#385]
Hey guys,

just documenting @infatrus idea from #general/Discord. https://github.com/mkmarek/forex.analytics looks very promising:

> The result of technical analysis are two binary trees describing strategies for buy and sell signals which produced profit in a certain period of time specified by the input OHLC data set.

@arpheno, @gelotus, what do you guys think of the approach?

Best,
-crubb

**Comment by Ekliptor** [comment]
Great idea.
But can we also use this to optimize parameters of our own strategies written in javascript?
The way I see it this forex depends on the c++ indicators of ta-lib and we can not add our own there? (at least not so easily)

**Comment by crubb** [comment]
That's been done (or is underway at least). Take a look at #298 and #299.

**Comment by gelotus** [comment]
The best person to talk about is @arpheno, he write a thesis about genetics algo.
anyway that lib seems very wip.. And it's for fiat market, will work well in crypto market?
If you are in a good point to merge that with zenbot, simply test it and see the results, for me it's a coin flip

**Comment by crubb** [comment]
zenbot already has some strategies using ta-lib, so that should be fine. Might be working well, see #389 ;)

**Comment by crubb** [comment]
Ok, the current implementation does show some promise (see sim results in the PR #389).

There is still work to do, though (@mkmarek, if you read this, is your forex.analytics still actively maintained?):

- Currently, only the indicators in https://github.com/mkmarek/forex.analytics/tree/master/src/indicators are available (so no EMA, for example).
- Also, the time periods for the indicators are fixed, for example at [14 for RSI](https://github.com/mkmarek/forex.analytics/blob/master/src/indicators/RSI.cpp#L10). This should be optimised by a genetic algorithm as well, I think.

**Comment by crubb** [comment]
Pinged the author, let's see.

**Comment by sandroid10** [comment]
how do i pull this branch ?/

**Comment by crubb** [comment]
Pull zenbot from my github profile and then switch branches to crubb/forex.analytics.

**Comment by sandroid1** [comment]
@crubb when i switch crubb/forex.analytics, i dont see train.js in commands

**Comment by sandroid1** [comment]
@crubb error in this branch 


/home/ubu/mywork/zenbot# ./zenbot.sh train gdax.ETH-USD --days_training 5 --days_test 3 --period 10m --generationCount 2000  --populationCount 200 --indicators CCI,MACD,RSI,SAR
Generating training candlesticks from database...
2017-07-22 23:49:41  231.75000000 ETH-USD   -0.4%     2565
Training [================================================================================] 100% 0.0s - Fitness: 22370.776646760474

Model temporarily written to models/temp.b25cae2e28a0f0386aacb683888c05ce377d2a474325aa2fc4f06acfbbb489e8-20170718_000000+0000.json

Running simulation on training data from 2017-07-18 00:00:00 +0000 to 2017-07-23 00:00:00 +0000.

/home/ubu/mywork/zenbot/node_modules/codemap/index.js:233
        throw err;
        ^

Error: path `zenbot:strategies.forex_analytics` is undefined
    at Object.get (/home/ubu/mywork/zenbot/node_modules/codemap/index.js:231:19)
    at get (/home/ubu/mywork/zenbot/node_modules/codemap/index.js:60:22)
    at /home/ubu/mywork/zenbot/lib/engine.js:65:20
    at Command.<anonymous> (/home/ubu/mywork/zenbot/commands/sim.js:75:39)
    at Command.listener (/home/ubu/mywork/zenbot/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/home/ubu/mywork/zenbot/node_modules/commander/index.js:635:12)
    at Command.parse (/home/ubu/mywork/zenbot/node_modules/commander/index.js:457:21)
    at /home/ubu/mywork/zenbot/zenbot.sh:39:11
    at /home/ubu/mywork/zenbot/boot.js:28:7
    at f (/home/ubu/mywork/zenbot/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/ubu/mywork/zenbot/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:115:13)
    at Glob.emit (events.js:210:7)
    at Glob._finish (/home/ubu/mywork/zenbot/node_modules/glob/glob.js:197:8)
    at done (/home/ubu/mywork/zenbot/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/home/ubu/mywork/zenbot/node_modules/glob/glob.js:637:12)
    at /home/ubu/mywork/zenbot/node_modules/glob/glob.js:626:10
    at RES (/home/ubu/mywork/zenbot/node_modules/inflight/inflight.js:31:16)
    at f (/home/ubu/mywork/zenbot/node_modules/once/once.js:25:25)
    at lstatcb_ (/home/ubu/mywork/zenbot/node_modules/glob/glob.js:519:7)
Child process exited with code 1 and signal null

**Comment by crubb** [comment]
The strategy was committed as of today. [Documentation is available](https://github.com/carlos8f/zenbot/blob/master/docs/strategy_forex_analytics.md).

Please play special attention to the limitations section and please contribute code to also optimise the loopback periods ;)
