### ISSUE TITLE
mongodb doesnt work after latest pull 

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#393]
npm WARN zenbot4@4.0.5 No repository field.
npm WARN zenbot4@4.0.5 No license field.

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

Suhasms-MacBook-Pro:zenbot suhasm$ zenbot backfill
warning: mongodb not accessible. some features (such as backfilling/simulation) may be disabled.
/Users/suhasm/Public/zenbot/node_modules/sosa_mongo/mongo_backend.js:6
  if (!backend_options.db) throw new Error('must pass a node-mongodb-native db with backend_options.db');
                           ^

Error: must pass a node-mongodb-native db with backend_options.db
    at module.exports (/Users/suhasm/Public/zenbot/node_modules/sosa_mongo/mongo_backend.js:6:34)
    at /Users/suhasm/Public/zenbot/node_modules/sosa/index.js:7:17
    at createCollection (/Users/suhasm/Public/zenbot/db/createCollection.js:5:7)
    at Object.container (/Users/suhasm/Public/zenbot/db/trades.js:2:36)
    at Object.getValue (/Users/suhasm/Public/zenbot/node_modules/codemap/index.js:298:22)
    at /Users/suhasm/Public/zenbot/node_modules/codemap/index.js:238:23
    at Array.forEach (native)
    at Object.get (/Users/suhasm/Public/zenbot/node_modules/codemap/index.js:237:13)
    at get (/Users/suhasm/Public/zenbot/node_modules/codemap/index.js:60:22)
    at Command.<anonymous> (/Users/suhasm/Public/zenbot/commands/backfill.js:22:22)
    at Command.listener (/Users/suhasm/Public/zenbot/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/suhasm/Public/zenbot/node_modules/commander/index.js:635:12)
    at Command.parse (/Users/suhasm/Public/zenbot/node_modules/commander/index.js:457:21)
    at /Users/suhasm/Public/zenbot/zenbot.sh:39:11
    at /Users/suhasm/Public/zenbot/boot.js:28:7
    at f (/Users/suhasm/Public/zenbot/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/suhasm/Public/zenbot/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/Users/suhasm/Public/zenbot/node_modules/glob/glob.js:197:8)

**Comment by ghost** [comment]
Last login: Sat Jul 22 17:55:30 on ttys002
Suhasms-MacBook-Pro:~ suhasm$ /Users/suhasm/Downloads/mongodb-osx-x86_64-3.4.6\ 3/bin/mongo ; exit;
MongoDB shell version v3.4.6
connecting to: mongodb://127.0.0.1:27017
2017-07-22T17:55:45.282-0700 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2017-07-22T17:55:45.282-0700 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:237:13
@(connect):1:6
exception: connect failed
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by chrisli30** [comment]
Hi @Optictrollz , I've got the same error. Have you figured out the cause of it?

**Comment by ghost** [comment]
@chrisli30 no, I just switched it to a Linux vm it was much easier
