### ISSUE TITLE
GDAX API is down!

### ISSUE THREAD

**Issue by Sea9SH** [DeviaVir/zenbot#396]
From time to time, I get the following error messages although the balance of currency and asset are shown correctly. Can you please help on this? Thanks.

GDAX API is down! unable to call getQuote, retrying in 10s
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:610:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[ { product_id: 'ETH-EUR' } ]

GDAX API is down! unable to call getBalance, retrying in 10s
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:610:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by Sea9SH** [comment]
@carlos8f Sorry for your time and attention. It seems that the problem is on my end that the API (api.gdax.com) is not reliably accessible in China due the Great Fire Wall. Everything is fine now after a proxy has been applied. Thank you for the great work and I am looking forward to your continued updates.
