### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by megrimm** [DeviaVir/zenbot#4]
hello. i get following error with recent git pull:

pi@raspberrypi:~/Development/bitcoin/zenbot $ zenbot backfill

/home/pi/Development/bitcoin/zenbot/node_modules/ws/lib/WebSocket.js:9
const url = require('url');
^^^^^
[SyntaxError: Use of const in strict mode.]
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Development/bitcoin/zenbot/node_modules/ws/index.js:9:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by megrimm** [comment]
wow i keep jumping the gun on the issues. the solution here is simply to update nodejs:

npm cache clean -f
npm install -g n
n stable
node --version
npm rebuild

now it works!
