### ISSUE TITLE
Error when install / start zenbot

### ISSUE THREAD

**Issue by jooshxp** [DeviaVir/zenbot#409]
just want to ask how to solve this : 
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at handleExists (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:329:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:258:19)
5 verbose cwd C:\Users\User\Desktop\zenbot
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v6.11.1
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

is it because i'm running another node.js program ?? hmm maybe not, because there's have different port.
and i just want to ask if you guys can share your setting to profit on polo ? thank's

**Comment by DeviaVir** [comment]
Please review https://github.com/carlos8f/zenbot/blob/master/docs/FAQ.md#windows
