### ISSUE TITLE
Kraken pair issues

### ISSUE THREAD

**Issue by talvasconcelos** [DeviaVir/zenbot#410]
I'm having an issue with kraken not getting DASH/EUR pair. Here's the error output:

`Trades error:
Error: Kraken API returned error: Query:Unknown asset pair
    at Request._callback (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\kraken-api\kraken.js:155:34)
    at Request.self.callback (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\tvasconcelos\Desktop\zenbot\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

getTrades() returned no trades, --start may be too remotely in the past.`

Anyone with this problem?

**Comment by talvasconcelos** [comment]
If i try backfill and change selector to kraken.DASH-EUR is works and fetches data, but on trade it throws error: could not find product

anyway i can solve this?

**Comment by talvasconcelos** [comment]
solved it by changing the products json on kraken. in the pair DASH / EUR, change ZEUR to EUR

**Comment by nibzo1** [comment]
@talvasconcelos Sounds like the same issue I reported here #352. Some of the currency pairs just do not work correctly in trade, but back-fill appears to work. 

The `products.json` update does not fix this from my experience, #354

**Comment by Erim32** [comment]
Hi, same for me, any solution ?

**Comment by cmroche** [comment]
Kraken API incorrectly reports pairs... which ones are you have problems with?

**Comment by cmroche** [comment]
https://github.com/carlos8f/zenbot/pull/469
