### ISSUE TITLE
Failed at the forex.analytics@0.0.14 postinstall script

### ISSUE THREAD

**Issue by angelsalinasm** [DeviaVir/zenbot#411]
When running the command "npm install" after clonning zenbot, an issue keeps appearing, preventing me from succesfully installing the tool.

Find attached the mentioned log
[npm-debug.txt](https://github.com/carlos8f/zenbot/files/1180416/npm-debug.tx

Anyone can help?

**Comment by benpdavison** [comment]
(I Think) you don't have the latest version of node installed. see `624 error node v6.11.1
625 error npm  v3.10.10`. You can confirm your version with `node -v`. if it is outdated try updating to node 8.

**Comment by jooshxp** [comment]
me too have same problem, already install latest version of node,
before they add forex.analytics, i'm already succsesfull install this zenbot, but after they add forex.analystic it's not work anymore, any solution ?

Edit : 
try to using latest version git and replace them with 4.0.5 from release tag and show this error : 
```module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Users\Desktop\New folder (2)\extensions\excha
nges\_codemap'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\Josh\Desktop\New folder (2)\boot.js:27:19
    at Array.forEach (native)
    at C:\Users\Users\Desktop\New folder (2)\boot.js:23:15
    at f (C:\Users\Users\Desktop\New folder (2)\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (C:\Users\Users\Desktop\New folder (2)\node_modules\glob\
glob.js:151:7)
    at emitOne (events.js:96:13)
```

**Comment by DeviaVir** [comment]
Are you both Windows users? @angelsalinasm @newb1ez

**Comment by webworker01** [comment]
I'm on Ubuntu and I think receive a related error message now after updating to master

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'forex.analytics'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/zenbot/commands/train.js:9:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by shanehull** [comment]
@webworker01 do npm install forex.analytics and that should fix your issue.

~~However, I think there's a few more issues regarding the btce module still being present.~~
Nevermind, I npm install'ed that too and Zenbot is happy. Looks like it's still included.

**Comment by webworker01** [comment]
@shed909 thanks, that fixed up the issues after I updated all dependencies.  Will try to do that anytime I update from master

**Comment by jooshxp** [comment]
@DeviaVir i'm using windows and i'm already installed what you mention in my issues before, and it still occur when i try to update it to master, but it's not happen when i installed it before the latest version, maybe we should have python installed before ??

@shed909 can't run do npm install forex.analytics :(

**Comment by DeviaVir** [comment]
Sounds like we broke Windows support in that case, @newb1ez you should still be able to run it as a docker.

**Comment by DeviaVir** [comment]
I'm superseding this by https://github.com/carlos8f/zenbot/issues/420, please move relevant discussions there

**Comment by campbellgoe** [comment]
I am receiving this error. I have decided to not use forex.analytics strategy until I can install it. I'm attempting to skip it with [npm-install-que](https://www.npmjs.com/package/npm-install-que). However, this didn't help so I removed forex.analytics from package.json and hope it won't break zenbot.
