### ISSUE TITLE
cannot npm install, dependencies problem

### ISSUE THREAD

**Issue by asterismo** [DeviaVir/zenbot#413]
Hi guys i have this issue when i try to run "npm install" it seems ta-lib is missing, but i installed it through pip and pip3, any suggestions?

```
  CXX(target) Release/obj.target/analytics/src/indicators/CCI.o
  CXX(target) Release/obj.target/analytics/src/indicators/MACD.o
  CXX(target) Release/obj.target/analytics/src/indicators/Momentum.o
  CXX(target) Release/obj.target/analytics/src/indicators/RSI.o
  CXX(target) Release/obj.target/analytics/src/indicators/SAR.o
  CXX(target) Release/obj.target/analytics/src/indicators/SMA.o
  CXX(target) Release/obj.target/analytics/src/indicators/Stochastic.o
  CXX(target) Release/obj.target/analytics/src/indicators/ATR.o
  CXX(target) Release/obj.target/analytics/src/indicators/BOP.o
  CXX(target) Release/obj.target/analytics/src/indicators/BaseIndicator.o
  CXX(target) Release/obj.target/analytics/src/indicators/factories/IndicatorFactory.o
  CXX(target) Release/obj.target/analytics/src/models/Candlestick.o
  CXX(target) Release/obj.target/analytics/src/nodes/IndicatorTreeNode.o
  CXX(target) Release/obj.target/analytics/src/nodes/OperatorTreeNode.o
  CXX(target) Release/obj.target/analytics/src/nodes/TreeNode.o
In file included from ../src/nodes/TreeNode.cpp:4:0:
../src/nodes/../../include/nodes/OperatorTreeNode.h:7:21: warning: ‘OperatorStrings’ defined but not used [-Wunused-variable]
 static const char * OperatorStrings[] = { "And", "Or", "Xor"};
                     ^
In file included from ../src/nodes/TreeNode.cpp:5:0:
../src/nodes/../../include/nodes/IndicatorTreeNode.h:5:21: warning: ‘SignStrings’ defined but not used [-Wunused-variable]
 static const char * SignStrings[] = { ">", "<" };
                     ^
  CXX(target) Release/obj.target/analytics/src/utils/HeapSort.o
  CXX(target) Release/obj.target/analytics/src/export.o
  CXX(target) Release/obj.target/analytics/src/functions/convertOHLC.o
  CXX(target) Release/obj.target/analytics/src/functions/findStrategy.o
  CXX(target) Release/obj.target/analytics/src/functions/getIndicatorData.o
  CXX(target) Release/obj.target/analytics/src/functions/getMarketStatus.o
  CXX(target) Release/obj.target/analytics/src/functions/getTrades.o
  SOLINK_MODULE(target) Release/obj.target/analytics.node
g++: error: ../lib/ta-lib/lib/libta_abstract_csr.a: No such file or directory
g++: error: ../lib/ta-lib/lib/libta_func_csr.a: No such file or directory
g++: error: ../lib/ta-lib/lib/libta_common_csr.a: No such file or directory
g++: error: ../lib/ta-lib/lib/libta_libc_csr.a: No such file or directory
analytics.target.mk:152: recipe for target 'Release/obj.target/analytics.node' failed
make: *** [Release/obj.target/analytics.node] Error 1
make: Leaving directory '/home/admin/zenbot/node_modules/forex.analytics/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-48-pve
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/admin/zenbot/node_modules/forex.analytics
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN zenbot4@4.0.5 No repository field.
npm WARN zenbot4@4.0.5 No license field.
npm ERR! Linux 2.6.32-48-pve
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "forex.analytics"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! forex.analytics@0.0.14 postinstall: `node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the forex.analytics@0.0.14 postinstall script 'node-gyp configure && node-gyp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the forex.analytics package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && node-gyp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs forex.analytics
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls forex.analytics
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/admin/zenbot/npm-debug.log
```

**Comment by DeviaVir** [comment]
Please read this part thoroughly;

```
npm ERR! Failed at the forex.analytics@0.0.14 postinstall script 'node-gyp configure && node-gyp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the forex.analytics package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && node-gyp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs forex.analytics
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls forex.analytics
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/admin/zenbot/npm-debug.log
```

**Comment by DeviaVir** [comment]
Also, if you are on Windows, please consider using docker (see https://github.com/carlos8f/zenbot/issues/420)

**Comment by pushkarnagle** [comment]
I am getting the same error in Raspberry Pi. Any issue with forex.analytics package?

**Comment by pushkarnagle** [comment]
@asterismo Try giving read write execute permissions to make and g++ folders. I had similar problem on my Raspberry Pi.
Then run `sudo npm install --unsafe-perm`

_Sent from my Motorola XT1706 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
