### ISSUE TITLE
Problem # 1

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#414]
Suhasms-MacBook-Pro:zenbot suhasm$ zenbot trade --paper
warning: mongodb not accessible. some features (such as backfilling/simulation) may be disabled.
/Users/suhasm/zenbot/node_modules/sosa_mongo/mongo_backend.js:6
  if (!backend_options.db) throw new Error('must pass a node-mongodb-native db with backend_options.db');
                           ^

Error: must pass a node-mongodb-native db with backend_options.db
    at module.exports (/Users/suhasm/zenbot/node_modules/sosa_mongo/mongo_backend.js:6:34)
    at /Users/suhasm/zenbot/node_modules/sosa/index.js:7:17
    at createCollection (/Users/suhasm/zenbot/db/createCollection.js:5:7)
    at Object.container (/Users/suhasm/zenbot/db/sessions.js:2:36)
    at Object.getValue (/Users/suhasm/zenbot/node_modules/codemap/index.js:298:22)
    at /Users/suhasm/zenbot/node_modules/codemap/index.js:238:23
    at Array.forEach (native)
    at Object.get (/Users/suhasm/zenbot/node_modules/codemap/index.js:237:13)
    at get (/Users/suhasm/zenbot/node_modules/codemap/index.js:60:22)
    at Command.<anonymous> (/Users/suhasm/zenbot/commands/trade.js:81:24)
    at Command.listener (/Users/suhasm/zenbot/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/suhasm/zenbot/node_modules/commander/index.js:635:12)
    at Command.parse (/Users/suhasm/zenbot/node_modules/commander/index.js:457:21)
    at /Users/suhasm/zenbot/zenbot.sh:39:11
    at /Users/suhasm/zenbot/boot.js:28:7
    at f (/Users/suhasm/zenbot/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/suhasm/zenbot/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/Users/suhasm/zenbot/node_modules/glob/glob.js:197:8)

**Comment by benpdavison** [comment]
have you installed mongodb and have it running?

**Comment by DeviaVir** [comment]
No mongodb, please read the documentation before posting issues.
