### ISSUE TITLE
Trading issue on live for kraken

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#422]
Unhandeld AddOrder error:
Error: Kraken API returned error: General:Invalid arguments:volume
    at Request._callback (/app/node_modules/kraken-api/kraken.js:155:34)
    at Request.self.callback (/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

{ Error: order rejected
    at /app/lib/engine.js:229:23
    at KrakenClient.<anonymous> (/app/extensions/exchanges/kraken/exchange.js:253:20)
    at Request._callback (/app/node_modules/kraken-api/kraken.js:155:23)
    at Request.self.callback (/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  order: 
   { id: null,
     status: 'rejected',
     price: '40.55017050',
     size: '0.05056425',
     created_at: 1501282025995,
     filled_size: '0',
     post_only: true,
     reject_reason: 'Kraken API returned error: General:Invalid arguments:volume' },
  desc: 'could not execute buy: error placing order' }

**Comment by ghost** [comment]
It runs and works on kraken its just every few hours or sometimes 10 minutes intervals Im getting this.

**Comment by DeviaVir** [comment]
Googling around for that problem didn't yield too many results for me, you might be better off opening a support ticket with Kraken and asking them what it means- when you report back with what they said we might be able to update our code for it.

**Comment by timstoop** [comment]
Posted a request at support.kraken.com, will let you know what they tell me.

**Comment by timstoop** [comment]
They replied:

> Please make sure that you submit order volume as a string with up to 8 decimals precision. Also please check if you fit into the minimum order volume here:
> https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

At least we have an explanation now!

**Comment by grigio** [comment]
So it means that an order size is too little? Is possible to avoid it?

**Comment by timstoop** [comment]
I guess it requires ZenBot to test if the order size is not too small. I don't think they make the list available through the API, though.

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
