### ISSUE TITLE
errors after latest update

### ISSUE THREAD

**Issue by gpearson100** [DeviaVir/zenbot#430]
Getting this now when I run `sudo git pull origin master && rm -rf node_modules/ && npm install`

```
info it worked if it ends with ok
1 verbose cli [ '/opt/bitnami/nodejs/bin/.node.bin',
1 verbose cli   '/opt/bitnami/nodejs/bin/npm',
1 verbose cli   'install' ]
2 info using npm@5.3.0
3 info using node@v7.10.0
4 verbose npm-session 33cf06df7fe70d3c
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall zenbot4@4.0.5
7 info lifecycle zenbot4@4.0.5~preinstall: zenbot4@4.0.5
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly fetchPackageMetaData error for forex.analytics@git+https://github.com/mkmarek/forex.analytics.git#7bc278987700d4204e959af17de61495941d1a14 Command failed: /opt/bitnami/git/bin/git clone --depth=1 -q -b master https://github.com/mkmarek/forex.analytics.git /home/bitnami/.npm/_cacache/tmp/git-clone-207cf3f1
13 silly fetchPackageMetaData /home/bitnami/.npm/_cacache/tmp/git-clone-207cf3f1/.git: Permission denied
14 verbose stack Error: Command failed: /opt/bitnami/git/bin/git clone --depth=1 -q -b master https://github.com/mkmarek/forex.analytics.git /home/bitnami/.npm/_cacache/tmp/git-clone-207cf3f1
14 verbose stack /home/bitnami/.npm/_cacache/tmp/git-clone-207cf3f1/.git: Permission denied
14 verbose stack
14 verbose stack     at ChildProcess.exithandler (child_process.js:205:12)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose cwd /home/bitnami/zenbot
16 verbose Linux 3.13.0-117-generic
17 verbose argv "/opt/bitnami/nodejs/bin/.node.bin" "/opt/bitnami/nodejs/bin/npm" "install"
18 verbose node v7.10.0
19 verbose npm  v5.3.0
20 error code 1
21 error Command failed: /opt/bitnami/git/bin/git clone --depth=1 -q -b master https://github.com/mkmarek/forex.analytics.git /home/bitnami/.npm/_cacache/tmp/git-clone-207cf3f1
21 error /home/bitnami/.npm/_cacache/tmp/git-clone-207cf3f1/.git: Permission denied
22 verbose exit [ 1, true ]
```
and zenbot wont load anymore
ideas?

**Comment by DeviaVir** [comment]
Why are you `sudo git pull`-ing? Your permissions are most likely quite messed up due to this.

**Comment by gpearson100** [comment]
I tried using `sudo` after I saw the permissions error.
I'll just try a fresh install and see what I get.

**Comment by DeviaVir** [comment]
Let us know how that goes so we can close this one out :)
