### ISSUE TITLE
latest issue kraken

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#433]
suhasms-mbp:zenbot suhasm$ docker run --rm --link zenbot_mongodb_1:mongodb -it zenbot_server ./zenbot.sh backfill kraken.LTC-USD --days 30
/app/extensions/exchanges/kraken/exchange.js:98
        Object.keys(data.result[args.pair]).forEach(function (i) {
               ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at KrakenClient.<anonymous> (/app/extensions/exchanges/kraken/exchange.js:98:16)
    at Request._callback (/app/node_modules/kraken-api/kraken.js:159:22)
    at Request.self.callback (/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by ghost** [comment]
Try XLTC-ZUSD. Should work.
