### ISSUE TITLE
btce/update-products.sh: Error: non-200 status: 400

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#434]
The update-products script of BTC-e is not working for me.

```
{ Error: non-200 status: 400
    at /home/martijn/github/zenbot/extensions/exchanges/btce/update-products.sh:6:15
    at IncomingMessage.<anonymous> (/home/martijn/github/zenbot/node_modules/micro-request/index.js:100:7)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'HTTP_STATUS',
  body: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>400 Bad Request</title>\n</head><body>\n<h1>Bad Request</h1>\n<p>Your browser sent a request that this server could not understand.<br />\n</p>\n</body></html>\n' }
```

**Comment by DeviaVir** [comment]
uh.. yeah. https://btc-e.com/index.html

**Comment by vaisov** [comment]
btc-e.com domain has been seized by FBI. https://www.hackread.com/feds-seize-btc-e-exchange-website-coinbase-suffers-ddos-attacks/
