### ISSUE TITLE
mongo Crashed after 3 days live how to fix?

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#442]

**Comment by Optictrollz** [comment]
{ MongoError: server instance pool was destroyed
    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:29:11)
    at basicWriteValidations (/app/node_modules/mongodb-core/lib/topologies/server.js:450:51)
    at Server.update (/app/node_modules/mongodb-core/lib/topologies/server.js:569:16)
    at Server.update (/app/node_modules/mongodb/lib/server.js:397:17)
    at updateDocuments (/app/node_modules/mongodb/lib/collection.js:1055:19)
    at save (/app/node_modules/mongodb/lib/collection.js:1341:12)
    at Collection.save (/app/node_modules/mongodb/lib/collection.js:1324:44)
    at Object.save (/app/node_modules/sosa_mongo/mongo_backend.js:35:12)
    at withHooks (/app/node_modules/sosa/api.js:68:15)
    at Object.save (/app/node_modules/sosa/api.js:65:12)
    at /app/commands/trade.js:252:24
    at /app/lib/engine.js:187:14
    at KrakenClient.<anonymous> (/app/extensions/exchanges/kraken/exchange.js:142:9)
    at Request._callback (/app/node_modules/kraken-api/kraken.js:159:22)
    at Request.self.callback (/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
  name: 'MongoError',
  message: 'server instance pool was destroyed',
  saved: false,

**Comment by Optictrollz** [comment]
I restarted it and it seems to work, bot hasn't made any trades yesterday which might be weird will keep you updated
