### ISSUE TITLE
Bittrex RSI Strategy error after running about 10 hours

### ISSUE THREAD

**Issue by azrulhaifan** [DeviaVir/zenbot#446]
I was using zenbot for 10 hours to trade on Bittrex using RSI Strategy. The bot error with ouput like this :

`undefined
/root/zenbot/node_modules/numbro/numbro.js:1111
        var parts = x.toString().split('.');
                     ^

TypeError: Cannot read property 'toString' of undefined
    at multiplier (/root/zenbot/node_modules/numbro/numbro.js:1111:22)
    at /root/zenbot/node_modules/numbro/numbro.js:1127:22
    at Array.reduce (native)
    at correctionFactor (/root/zenbot/node_modules/numbro/numbro.js:1125:21)
    at Numbro.add (/root/zenbot/node_modules/numbro/numbro.js:1197:47)
    at /root/zenbot/commands/trade.js:234:78
    at /root/zenbot/lib/engine.js:191:14
    at /root/zenbot/extensions/exchanges/bittrex/exchange.js:113:18
    at Request._callback (/root/zenbot/node_modules/node.bittrex.api/node.bittrex.api.js:112:25)
    at Request.self.callback (/root/zenbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/root/zenbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/root/zenbot/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
`

Is this bug ? i start the bot again and now, the bot is normal.

**Comment by KryptoNova** [comment]
There appears to be a fix for this, but it is something that needs to be done after each time an  npm install happens.
See #457.
