### ISSUE TITLE
[SOLVED] GDAX API unable to call getBalance, http_status 'invalid signature'

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#448]
Sim and paper trading working fine but as soon as I try live trading I get this error. Been trying to dig into this myself without luck, would appreciate some help or pointers on rectifying this issue. GDAX status site shows everything is fine on their end.
Running CentOS7-1611 Core, all zenbot dependencies installed and up to date that I'm aware of. Everything else working fine, no other errors or warnings. Triple checked that all GDAX API info in conf.js was entered correctly.
I can grab version info on nodejs npm etc. if it will help. 
This is the console error output I receive after running zenbot in live trading mode:
`GDAX API is down! unable to call getBalance, retrying in 10s
{ Error: non-200 status: 400
    at statusErr (/root/zenbot/extensions/exchanges/gdax/exchange.js:30:17)
    at /root/zenbot/extensions/exchanges/gdax/exchange.js:93:25
    at Request._callback (/root/zenbot/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/root/zenbot/node_modules/gdax/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/zenbot/node_modules/gdax/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/zenbot/node_modules/gdax/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._TickCallback (internal/process/next_tick.js:104:9) code: 'HTTP_STATUS', body: { message: 'invalid signature' } }`

**Comment by ghost** [comment]
GDAX API is down! unable to call getBalance, retrying in 10s
{ Error: non-200 status: 400
    at statusErr (/root/zenbot/extensions/exchanges/gdax/exchange.js:30:17)
    at /root/zenbot/extensions/exchanges/gdax/exchange.js:93:25
    at Request._callback (/root/zenbot/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/root/zenbot/node_modules/gdax/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/zenbot/node_modules/gdax/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/zenbot/node_modules/gdax/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._TickCallback (internal/process/next_tick.js:104:9) code: 'HTTP_STATUS', body: { message: 'invalid signature' } }

**Comment by ghost** [comment]
Problem solved!
I had only enabled "view" and "trade" checkboxes when requesting my original API key on GDAX, when it appears that "manage" is also required. Generated a new key with those three checkboxes marked and now live trading works.
So this is not an issue with zenbot at all.
