### ISSUE TITLE
When using --currency_capital=0 there is an error

### ISSUE THREAD

**Issue by asafyish** [DeviaVir/zenbot#449]
Hi,

I am trying to run a simulation with assets only (no currency), like
--asset_capital=123 --currency_capital=0
But there is an error:

zenbot/node_modules/round-precision/index.js:8
    throw new Error('Value must be a finite number')
    ^

Error: Value must be a finite number
    at toPrecision (/Users/ayishai/Dev/zenbot/node_modules/round-precision/index.js:8:11)
    at processOutput (/Users/ayishai/Dev/zenbot/backtester.js:120:13)
    at shell.exec (/Users/ayishai/Dev/zenbot/backtester.js:94:14)
    at /Users/ayishai/Dev/zenbot/node_modules/shelljs/src/exec.js:199:9
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)

**Comment by tiagosiebler** [comment]
Division by 0 = infinity:
https://github.com/carlos8f/zenbot/blob/master/scripts/genetic_backtester/darwin.js#L121

**Comment by LoneWolf345** [comment]
Are you still experiencing this problem?  If not, consider closing this.

**Comment by asafyish** [comment]
Didn't tried for a long time.
