### ISSUE TITLE
Unhandled AddOrder error, Invalid arguments:volume

### ISSUE THREAD

**Issue by timstoop** [DeviaVir/zenbot#451]
Just got this error while trading on Kraken:

{{{
2017-08-07 14:30:03  229.000 XETH-ZEUR   +0.0%        4   60 ++   229.0000218.9979           0.00 XETH  32.21440 ZEUR    +0.5%   +0.1%                                                                                                [17/439]
Unhandeld AddOrder error:
Error: Kraken API returned error: General:Invalid arguments:volume
    at Request._callback (/app/node_modules/kraken-api/kraken.js:155:34)
    at Request.self.callback (/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

{ Error: 
order rejected
    at /app/lib/engine.js:233:23
    at KrakenClient.<anonymous> (/app/extensions/exchanges/kraken/exchange.js:253:20)
    at Request._callback (/app/node_modules/kraken-api/kraken.js:155:23)
    at Request.self.callback (/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  order: 
   { id: null,
     status: 'rejected',
     price: '228.59000000',
     size: '0.01409265',
     created_at: 1502116197466,
     filled_size: '0',
     reject_reason: 'Kraken API returned error: General:Invalid arguments:volume' },
  desc: 'could not execute buy: error placing order' }
}}}

This same build has bought ETH earlier todiay, though. The one thing I changed was setting `--buy_pct` to 10 instead of 50, what is was before.

**Comment by DeviaVir** [comment]
Looks like a dup of https://github.com/carlos8f/zenbot/issues/422
