### ISSUE TITLE
Kraken API Lockout

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#463]
getBalance error:
Error: Kraken API returned error: General:Temporary lockout
    at Request._callback (/home/masternode/zenbot/node_modules/kraken-api/kraken.js:155:34)
    at Request.self.callback (/home/masternode/zenbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/masternode/zenbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/masternode/zenbot/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
/home/masternode/zenbot/commands/trade.js:133
                    throw err
                    ^

Error: Kraken API returned error: General:Temporary lockout
    at Request._callback (/home/masternode/zenbot/node_modules/kraken-api/kraken.js:155:34)
    at Request.self.callback (/home/masternode/zenbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/masternode/zenbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/masternode/zenbot/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Current error I am getting after creating new API key, I created a support ticket with kraken will let you know if it gets fixed.

**Comment by ghost** [comment]
This error seens to only occurs on initial startup after I create a new API key. So I think the error is on krakens end unless the kraken.js file is calling the API too many times.

**Comment by ghost** [comment]
ok so I just tried it a few minutes back and it started working and then I started getting Kraken temporary lockout out so im starting to think its on zenbots end calling kraken's API too many times. 

 Here is a link to API call rate limits:
https://support.kraken.com/hc/en-us/articles/206548367-What-is-the-API-call-rate-limit-

**Comment by DeviaVir** [comment]
Closing due to inactivity.
