### ISSUE TITLE
x is undefined - crash in numbro.js

### ISSUE THREAD

**Issue by fishfugu** [DeviaVir/zenbot#472]
Got this crash and error message while running for bittrex.btc-eth:

undefined
undefined
<path to zenbot>/zenbot/node_modules/numbro/numbro.js:1111
        var parts = x.toString().split('.');
                     ^

TypeError: Cannot read property 'toString' of undefined
    at multiplier (<path to zenbot>/zenbot/node_modules/numbro/numbro.js:1111:22)
    at <path to zenbot>/zenbot/node_modules/numbro/numbro.js:1127:22
    at Array.reduce (native)
    at correctionFactor (<path to zenbot>/modules/numbro/numbro.js:1197:47)
    at <path to zenbot>/zenbot/commands/trade.js:236:78
    at <path to zenbot>/zenbot/lib/engine.js:191:14
    at <path to zenbot>/zenbot/extensions/exchanges/bittrex/exchange.js:113:18
    at Request._callback (<path to zenbot>/zenbot/node_modules/node.bittrex.api/node.bittrex.api.js:112:25)
    at self.callback (<path to zenbot>/zenbot/node_modules/node.bittrex.api/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (<path to zenbot>/zenbot/node_modules/node.bittrex.api/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by fishfugu** [comment]
Actually - think this might be the same as #457

**Comment by DeviaVir** [comment]
Yes, it's a dupe. As it's not adding any new information I will be closing this ticket in lieu of the other.
