### ISSUE TITLE
Unable to Configure Zenbot - "Cannot Find Module 'Semver'"

### ISSUE THREAD

**Issue by mtroemner** [DeviaVir/zenbot#488]
I have been trying to set up and configure Zenbot4, and am running into an issue where it cannot find the module 'semver'. I have tried setting it up on both my Ubuntu machine and on a separate one with Docker, both running into the exact same issue. Below is the output, any suggestions? Thanks!

    matthew@matthew-Lenovo-IdeaPad-Y580:~/zenbot$ ./zenbot.sh
        module.js:491
        throw err;
        ^

    Error: Cannot find module 'semver'
        at Function.Module._resolveFilename (module.js:489:15)
        at Function.Module._load (module.js:439:25)
        at Module.require (module.js:517:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/home/matthew/zenbot/zenbot.sh:2:14)
        at Module._compile (module.js:573:30)
        at Object.Module._extensions..js (module.js:584:10)
        at Module.load (module.js:507:32)
        at tryModuleLoad (module.js:470:12)
        at Function.Module._load (module.js:462:3)

**Comment by cmroche** [comment]
`npm install`
