### ISSUE TITLE
ENAMETOOLONG error in Forex_analytics

### ISSUE THREAD

**Issue by smartbrain** [DeviaVir/zenbot#502]
After trying to run a training on bitfinex.btc-usd on forex_analytics, Zenbot crashes with an ENAMETOOLONG error. I am guessing the filename is too long. Is there any way to set any parameters to allow longer filenames to be handled in the script or other workaround?

Using Xubutu 16.04 LTS.

Thanks,
Don.

```
2017-06-04 23:38:56  2469.20 BTC-USD   +0.5%       23   50 +          buy  0.4812017-06-04 23:59:59  2473.50 BTC-USD   +0.2%       62   52 +          buy  0.4812017-06-05 00:19:40  2478.00 BTC-USD   +0.2%       82   54 +          buy  0.4812017-06-05 00:39:57  2481.70 BTC-USD   +0.1%       90   56 ++         buy  0.48153 BTC    11.22031 USD   +20.6%   -1.5%
end balance: 1209.35128965 (20.94%)
buy hold: 1227.52836704 (22.75%)
vs. buy hold: -1.48%
29 trades over 16 days (avg 1.81 trades/day)
win/loss: 11/5
error rate: 31.25%
wrote /home/don/zenbot/models/temp.92b8777a81797d2cdde2111b99f2600c453302ebe7e36932a8aa9269e4052250-20160417_000000+0000.json-simTestResult.html
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENAMETOOLONG: name too long, open 'models/forex.model_bitfinex.BTC-USD_period=20m_from=20160417_000000+0000_to=20170522_000000+0000_trainingVsBuyHold=-2.47_testVsBuyHold=-1.48_created=20170820_081431+0000.json'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at writeFinalModel (/home/don/zenbot/commands/train.js:183:14)
    at ChildProcess.<anonymous> (/home/don/zenbot/commands/train.js:275:38)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by LoneWolf345** [comment]
Are you still experiencing this problem?  If not, consider closing this.
