### ISSUE TITLE
Errors in debian linux npm link

### ISSUE THREAD

**Issue by whiteneilys** [DeviaVir/zenbot#504]
(First, I'm talking with a translator, I'm sorry.)

I run "npm link" and "zenbot sim" to get an error.
My installation environment is Debian 8.8 / 64bit

Please solve this problem.. Thank you.

------------------------------------------------------------

1. npm link Error Messages.
  neilys@debian: ~/zenbot$ sudo npm link
  npm WARN zenbot4@4.0.5 No repository field.
  npm WARN zenbot4@4.0.5 No license field.
  /usr/bin/zenbot -> /usr/lib/node_modules/zenbot4/zenbot.sh
  /usr/lib/node_modules/zenbot4 -> /home/neilys/zenbot
  neilys@debian: ~/zenbot$

2. run zenbot simulation test Error.
 neilys@debian:~/zenbot$ zenbot sim --help
 module.js:471
    throw err;
    ^

 Error: Cannot find module './build/Release/analytics.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/neilys/zenbot/node_modules/forex.analytics/index.js:1:79)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
 neilys@debian:~/zenbot$

**Comment by ghost** [comment]
Are you pulling a release or the current codebase?

In any case, error is probably due to an outdated node version, should use 8.x and above, or else the node alias will not exist. Update nodejs to 8.x and run `rm -rf node_modules && npm install`

**Comment by whiteneilys** [comment]
I update node.js 8.x install.
It works normally after installation.

Thx, zonpalms91 :)

Close Issue.
