### ISSUE TITLE
Cant Paper Trade With Model File

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#517]
2017-09-02 18:25:52  0.00004954 XRP-BTC   +0.0%     3182   53 +       buying  0.2017-09-02 18:25:52  0.00004954 XRP-BTC   +0.0%     3182   53 +       buying  0.2017-09-02 18:25:52  0.00004954 XRP-BTC   +0.0%     3182   53 +       buying  0.00 XRP  1000.00000 BTC    +0.0%   -0.9%

{ Error: connect ETIMEDOUT 104.20.12.48:443
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.20.12.48',
  port: 443,
  desc: 'could not execute buy: error fetching quote' }

2017-09-02 18:26:00  0.00004962 XRP-BTC   +0.2%     3210   56 ++              0.00 XRP  1000.00000 BTC    +0.0%   -1.0%

how do I fix this?

**Comment by crubb** [comment]
This has nothing to do with the model file, zenbot has problems connecting to the exchange API. Just try again, check you exchange's status page and check your internet connection.

**Comment by ghost** [comment]
ok yea ur right it works now.
