### ISSUE TITLE
GDAX Balance Not Working

### ISSUE THREAD

**Issue by haroot** [DeviaVir/zenbot#519]
GDAX API is down! unable to call getBalance, retrying in 10s
{ Error: non-200 status: 400
    at statusErr (/home/ec2-user/zenbot/extensions/exchanges/gdax/exchange.js:30                                                                                                                                                             :17)
    at /home/ec2-user/zenbot/extensions/exchanges/gdax/exchange.js:93:25
    at Request._callback (/home/ec2-user/zenbot/node_modules/gdax/lib/clients/pu                                                                                                                                                             blic.js:45:7)
    at Request.self.callback (/home/ec2-user/zenbot/node_modules/gdax/node_modul                                                                                                                                                             es/request/request.js:187:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/ec2-user/zenbot/node_modules/gdax/node_modules                                                                                                                                                             /request/request.js:1044:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/ec2-user/zenbot/node_modules/gdax/node                                                                                                                                                             _modules/request/request.js:965:12)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  code: 'HTTP_STATUS',
  body: { message: 'request timestamp expired' } }
[ { currency: 'BTC', asset: 'ETH' } ]
^C

**Comment by JensvdHeydt** [comment]
Sometimes the GDAX API has little problems on their side. As the request body states: "request timestamp expired". I suppose the http request simply took to long and GDAX cancelled it. I don't think this is an actual error, Are you still experiencing this problem?

**Comment by DeviaVir** [comment]
Sounds like an ephemeral or network problem.

**Comment by ColterD** [comment]
Answered in #669
