### ISSUE TITLE
error after updateing to latest commit  `a33cac4 `

### ISSUE THREAD

**Issue by gpearson100** [DeviaVir/zenbot#522]
get this after running;
```
 Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bitnami/zenbot/node_modules/bitfinex-api-node/ws.js:6:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
also tried a clean install and same error .

thanks

**Comment by nedievas** [comment]
try again: `git pull` and then `npm install`.

**Comment by gpearson100** [comment]
no luck but what seems to have done the trick is `npm install ws`
