### ISSUE TITLE
url_parser.js 'missing delimiting slash between hosts and options'

### ISSUE THREAD

**Issue by Unique2690** [DeviaVir/zenbot#550]
Hello, I'm very new to Linux so I apologize if this is a something dumb but I keep pulling an error when I try to run zenbot. I've looked into url_parser but I have no idea what to do. Could anyone help me out with fixing this error? Thank you in advance. 

`/home/unique2690/zenbot/node_modules/mongodb/lib/url_parser.js:38
    throw new Error('missing delimiting slash between hosts and options');
    ^

Error: missing delimiting slash between hosts and options
    at module.exports (/home/unique2690/zenbot/node_modules/mongodb/lib/url_parser.js:38:11)
    at connect (/home/unique2690/zenbot/node_modules/mongodb/lib/mongo_client.js:486:16)
    at Function.MongoClient.connect (/home/unique2690/zenbot/node_modules/mongodb/lib/mongo_client.js:250:3)
    at module.exports (/home/unique2690/zenbot/boot.js:33:34)
    at Object.<anonymous> (/home/unique2690/zenbot/zenbot.sh:20:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
`

**Comment by Unique2690** [comment]
Nevermind. Somehow the zenbot file became corrupt. Reinstalled it and its working now.
