### ISSUE TITLE
Non RFC2822/ISO date formats

### ISSUE THREAD

**Issue by BarnumD** [DeviaVir/zenbot#557]
Got error when running zenbot train.
```
docker run --link zenbot_mongodb_1:mongodb -it zenbot_server ./zenbot.sh train --days 365
Generating training candlesticks from database...
2017-09-22 11:59:57  3558.48 BTC-USD   -1.38%      336
Training [================================================================================] 100% 0.0s - Fitness: 737098.7202632993

Model temporarily written to models/temp.bcb86862ce16666f80b9da614217ac986dcef4850b1c0f7b065da29132785153-20170923_024306+0000.json

Running simulation on training data from 2017-09-23 02:43:06 +0000 to 2017-09-22 12:00:00 +0000.

Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: undefined, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/app/node_modules/moment/moment.js:320:94)
    at configFromString (/app/node_modules/moment/moment.js:2178:11)
    at configFromInput (/app/node_modules/moment/moment.js:2547:9)
    at prepareConfig (/app/node_modules/moment/moment.js:2530:9)
    at createFromConfig (/app/node_modules/moment/moment.js:2497:40)
    at createLocalOrUTC (/app/node_modules/moment/moment.js:2584:12)
    at createLocal (/app/node_modules/moment/moment.js:2588:12)
    at hooks (/app/node_modules/moment/moment.js:16:25)
    at Command.<anonymous> (/app/commands/sim.js:51:22)
    at Command.listener (/app/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/app/node_modules/commander/index.js:635:12)
    at Command.parse (/app/node_modules/commander/index.js:457:21)
    at /app/zenbot.sh:39:11
    at /app/boot.js:28:7
    at f (/app/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/app/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/app/node_modules/glob/glob.js:197:8)
    at done (/app/node_modules/glob/glob.js:182:14)
2017-09-22 11:29:53  3608.44 BTC-USD   +0.28%      184    -- 39        buy  0.22347 BTC   10.81550 USD  -18.28%   +4.72%
end balance: 806.01582632 (-19.40%)
buy hold: 769.53751800 (-23.05%)
vs. buy hold: 4.74%
6 trades over 18 days (avg 0.33 trades/day)
win/loss: 1/2
error rate: 66.67%
wrote /app/models/temp.bcb86862ce16666f80b9da614217ac986dcef4850b1c0f7b065da29132785153-20170923_024306+0000.json-simTrainingResult.html

Final model with results written to models/forex.model_gdax.BTC-USD_period=30m_from=20170923_024416+0000_to=20170922_120000+0000_trainingVsBuyHold=4.74_testVsBuyHold=noTest_created=20170923_024416+0000.json

```

**Comment by BarnumD** [comment]
Perhaps it was because I used --days and not --days_training and --days_test.
