### ISSUE TITLE
Auto_backtester documentation?

### ISSUE THREAD

**Issue by brucetus** [DeviaVir/zenbot#558]
Is there documentation that gives steps on how to run the auto_backtester script?
When I try to run it I get this error:

```module.js:529
    throw err;
    ^

Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/scripts/auto_backtester/backtester.js:14:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

Thanks

**Comment by Wood-Chopper** [comment]
For the ones who get stuck with this type of error, just type
`npm install` in the folder `auto_backtester`
