### ISSUE TITLE
cmd `server` exited with code 1, respawning now.

### ISSUE THREAD

**Issue by backenders-game** [DeviaVir/zenbot#60]
```
09/07/2016 07:55:30 PM MSK [    launcher] cmd `server` exited with code 1, respawning now.
09/07/2016 07:55:31 PM MSK [    launcher] cmd `server` booting
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3013
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at Array.listen (/home/zenbot/node_modules/motley/site/listen.js:3:24)
    at module.exports (/home/zenbot/node_modules/run-series/index.js:20:33)
    at runHook (/home/zenbot/node_modules/motley/hooks/runHook.js:4:29)
    at runListen [as listen] (/home/zenbot/node_modules/motley/hooks/runListen.js:10:25)
    at action (/home/zenbot/plugins/server/action.js:10:9)
09/07/2016 07:55:31 PM MSK [    launcher] cmd `server` exited with code 1, respawning now.
09/07/2016 07:55:32 PM MSK [    launcher] cmd `server` booting
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3013
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at Array.listen (/home/zenbot/node_modules/motley/site/listen.js:3:24)
    at module.exports (/home/zenbot/node_modules/run-series/index.js:20:33)
    at runHook (/home/zenbot/node_modules/motley/hooks/runHook.js:4:29)
    at runListen [as listen] (/home/zenbot/node_modules/motley/hooks/runListen.js:10:25)
    at action (/home/zenbot/plugins/server/action.js:10:9)

```

Why this is happening and what can i do when this happens?

**Comment by grigio** [comment]
a "zenbot server" is still alive.. try with `killall node` and retry

**Comment by carlos8f** [comment]
Zenbot 4 is out, so I'm cleaning up 3.x issues. Please use and test 4, thanks!
