### ISSUE TITLE
map issue

### ISSUE THREAD

**Issue by Beyondem** [DeviaVir/zenbot#61]
I seem to be getting this strange error once I try to run map in sim or direclty as a command:

```
bey@ubuntu:~/zenbot$ zenbot map --backfill
09/07/2016 03:36:25 PM EDT [    launcher] cmd `map` booting
/home/bey/zenbot/utils/get_products.js:6
      if (c.assets.indexOf(product.asset) === -1) return false
                  ^

TypeError: Cannot read property 'indexOf' of undefined
    at /home/bey/zenbot/utils/get_products.js:6:19
    at Array.filter (native)
    at get_products (/home/bey/zenbot/utils/get_products.js:5:23)
    at mapper (/home/bey/zenbot/plugins/gdax/backfiller.js:12:20)
    at /home/bey/zenbot/node_modules/run-parallel/index.js:41:7
    at Array.forEach (native)
    at module.exports (/home/bey/zenbot/node_modules/run-parallel/index.js:40:11)
    at mapper (/home/bey/zenbot/node_modules/zenbrain/core/mapper/mapper.js:9:5)
    at Object.<anonymous> (/home/bey/zenbot/node_modules/zenbrain/core/launcher/launcher.js:76:11)
    at Immediate._onImmediate (/home/bey/zenbot/node_modules/sosa/api.js:15:12)
```

I looked around and there are no open or closed issues related to this.

Does anybody know whats going on here?

**Comment by ruimgoncalves** [comment]
I had this issue, you have to specify the configuration file with the flag
--config

A qua, 7/09/2016, 20:37, Beyondem notifications@github.com escreveu:

**Comment by Beyondem** [comment]
Thanks! I just caught that at the same time!

Will close this issue off now too
