### ISSUE TITLE
ccxt crash 

### ISSUE THREAD

**Issue by nedievas** [DeviaVir/zenbot#621]
Latest pull:
```
rebootfin@zenbot:~/zenbot$ zenbot trade cexio.eth-usd --strategy cci_srsi --period 10m
/home/rebootfin/zenbot/node_modules/ccxt/ccxt.js:494
                    let partial = async params => this[methodName] (url, type, uppercaseMethod, params)
                                        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/rebootfin/zenbot/extensions/exchanges/hitbtc/exchange.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/rebootfin/zenbot/extensions/exchanges/hitbtc/_codemap.js:4:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by DeviaVir** [comment]
What node version?

**Comment by nedievas** [comment]
v6.11.4

**Comment by nedievas** [comment]
v8.6.0 is OK.

**Comment by DeviaVir** [comment]
Looks like a downside of `ccxt`:
https://github.com/ccxt-dev/ccxt/blob/master/package.json#L8
on the other side, ccxt gives us a ton of exchanges... I think we can start recommending folks to upgrade to node 8 (current).
