### ISSUE TITLE
Issues with Hitbtc if removed it runs fine

### ISSUE THREAD

**Issue by ghost** [DeviaVir/zenbot#646]
bot@bot-Vm:~/zenbot$ zenbot list-selectors
/home/bot/zenbot/node_modules/ccxt/ccxt.js:521
                    let partial = async params => this[methodName] (url, type, uppercaseMethod, params)
                                        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bot/zenbot/extensions/exchanges/hitbtc/exchange.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bot/zenbot/extensions/exchanges/hitbtc/_codemap.js:4:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

Can anyone help with this just setting up and hitbtc is my exchange

**Comment by wpvv** [comment]
You have to update your node.js to v8, i had the same issue.
