### ISSUE TITLE
Bot quitting on Bittrex exchange

### ISSUE THREAD

**Issue by ether-btc** [DeviaVir/zenbot#693]
Bot quits after a time period (even in manual mode with no trades) on Bittrex exchange.

`/home/pi/zenbot/node_modules/numbro/numbro.js:1111
        var parts = x.toString().split('.');
                      ^

TypeError: Cannot read property 'toString' of undefined
    at multiplier (/home/pi/zenbot/node_modules/numbro/numbro.js:1111:23)
    at /home/pi/zenbot/node_modules/numbro/numbro.js:1127:22
    at Array.reduce (<anonymous>)
    at correctionFactor (/home/pi/zenbot/node_modules/numbro/numbro.js:1125:21)
    at Numbro.add (/home/pi/zenbot/node_modules/numbro/numbro.js:1197:47)
    at /home/pi/zenbot/commands/trade.js:391:78
    at /home/pi/zenbot/lib/engine.js:192:14
    at /home/pi/zenbot/extensions/exchanges/bittrex/exchange.js:113:18
    at Request._callback (/home/pi/zenbot/node_modules/node.bittrex.api/node.bittrex.api.js:112:25)
    at Request.self.callback (/home/pi/zenbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/pi/zenbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/pi/zenbot/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by luponata** [comment]
check this: #457
