### ISSUE TITLE
Bittrex Trading Error 

### ISSUE THREAD

**Issue by relaxdev** [DeviaVir/zenbot#731]
> 2017-11-18 06:24:00  0.168370 BCC-BTC   -1.33%      728   58 ++      0.0991   0.0573   +1.98%  0.02883648 BCC  0.00000994 BTC   -9.56%   -8.43%
2017-11-18 06:26:00  0.167617 BCC-BTC   -0.45%      656   55 ++      0.0691   0.0483   +1.53%  0.02883648 BCC  0.00000994 BTC   -9.97%   -8.43%
2017-11-18 06:28:00  0.168500 BCC-BTC   +0.53%      283   58 ++      0.0941   0.0504   +2.06%  0.02883648 BCC  0.00000994 BTC   -9.49%   -8.43%
server_1        | undefined
server_1        | /app/node_modules/numbro/numbro.js:1111
server_1        |         var parts = x.toString().split('.');
server_1        |                       ^
server_1        |
server_1        | TypeError: Cannot read property 'toString' of undefined
server_1        |     at multiplier (/app/node_modules/numbro/numbro.js:1111:23)
server_1        |     at /app/node_modules/numbro/numbro.js:1127:22
server_1        |     at Array.reduce (<anonymous>)
server_1        |     at correctionFactor (/app/node_modules/numbro/numbro.js:1125:21)
server_1        |     at Numbro.add (/app/node_modules/numbro/numbro.js:1197:47)
server_1        |     at /app/commands/trade.js:391:78
server_1        |     at /app/lib/engine.js:192:14
server_1        |     at /app/extensions/exchanges/bittrex/exchange.js:113:18
server_1        |     at Request._callback (/app/node_modules/node.bittrex.api/node.bittrex.api.js:112:25)
server_1        |     at Request.self.callback (/app/node_modules/request/request.js:186:22)
server_1        |     at emitTwo (events.js:135:13)
server_1        |     at Request.emit (events.js:224:7)
server_1        |     at Request.<anonymous> (/app/node_modules/request/request.js:1060:10)
server_1        |     at emitOne (events.js:125:13)
server_1        |     at Request.emit (events.js:221:7)
server_1        |     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:980:12)
server_1        |     at Object.onceWrapper (events.js:322:30)
server_1        |     at emitNone (events.js:120:20)
server_1        |     at IncomingMessage.emit (events.js:218:7)
server_1        |     at endReadableNT (_stream_readable.js:1054:12)
server_1        |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
server_1        |     at process._tickCallback (internal/process/next_tick.js:180:9)
>

**Comment by billbartlett** [comment]
There is a previous bug listed #435 that outlines the problem.  For whatever reason, if you point to an alternate config file, the API keys are always read from conf.js.  I haven't looked through the code yet, but a simple solution is to just name your config "conf.js".  I've tested it myself with Bittrex and it works as expected.

**Comment by LoneWolf345** [comment]
Are you still experiencing this problem.  If not, consider closing this.

**Comment by YuriyTigiev** [comment]
I have the same problem with binance. 
A few hours ago the bot has worked. 
I have installed the latest version of zenbot 

c:\zenbot>node zenbot.js sim --strategy cci_srsi binance.ETC-BTC
If you have questions about this strategy, contact me... @talvasconcelos
(node:9316) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
2018-08-06 04:39:00  0.00245900 ETC-BTC   +0.20%     8864     - 46.25      -213   -->         buyc:\zenbot\node_modules\lolex\src\lolex-src.js:663
                throw firstException;
                ^

TypeError: Cannot read property 'toString' of null
    at multiplier (c:\zenbot\node_modules\numbro\numbro.js:1123:23)
    at c:\zenbot\node_modules\numbro\numbro.js:1139:22
    at Array.reduce (<anonymous>)
    at correctionFactor (c:\zenbot\node_modules\numbro\numbro.js:1137:21)
    at Numbro.add (c:\zenbot\node_modules\numbro\numbro.js:1218:47)
    at c:\zenbot\lib\engine.js:362:61
    at c:\zenbot\lib\engine.js:235:9
    at c:\zenbot\lib\engine.js:304:7
    at c:\zenbot\extensions\exchanges\sim\exchange.js:66:18
    at callTimer (c:\zenbot\node_modules\lolex\src\lolex-src.js:356:24)
    at Object.tick (c:\zenbot\node_modules\lolex\src\lolex-src.js:622:25)
    at withOnPeriod (c:\zenbot\lib\engine.js:767:19)
    at onTrade (c:\zenbot\lib\engine.js:934:7)
    at c:\zenbot\lib\engine.js:895:5
    at c:\zenbot\node_modules\async\dist\async.js:4096:9
    at Object.process (c:\zenbot\node_modules\async\dist\async.js:2344:17)
    at c:\zenbot\node_modules\async\dist\async.js:2252:19
    at Immediate._onImmediate (c:\zenbot\node_modules\async\dist\async.js:119:16)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

c:\zenbot>zenbot -v

c:\zenbot>node zenbot.js -v

  error: unknown option `-v'


c:\zenbot>npm --v
5.6.0

c:\zenbot>
