### ISSUE TITLE
Hitbtc API Error

### ISSUE THREAD

**Issue by blastbeng** [DeviaVir/zenbot#733]
Hello, 
i just configured hitbtc to use LTC-EUR and i get this error:

fetching pre-roll data:
An error occurred { Error: hitbtc GET http://api.hitbtc.com/api/1/public/undefined/trades?side=true&id=LTC%2FEUR&by=ts&from=1510921801391 400 Bad Request {"error":{"code":2001,"message":"Symbol not found","description":"Try get /api/2/public/symbol, to get list of all a$
    at response.text.then.text (/media/SATADisk/bitcoin/zenbot/node_modules/ccxt/ccxt.js:668:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeNotAvailable] }

thanks

**Comment by abduegal** [comment]
Correct me if im wrong, but LTC-EUR is not an existing market in HitBTC, that is probably the reason why you get this error.

**Comment by blastbeng** [comment]
list-selectors is returning this, but that still doesnt mean ltc/eur is available on hitbtc?

$: zenbot list-selectors | grep LTC/BTC
  bitfinex.LTC-BTC   (LTC/BTC)
  bitstamp.LTC-BTC   (LTC/BTC)
  btce.LTC-BTC   (LTC/BTC)
  gdax.LTC-BTC   (LTC/BTC)
  **hitbtc.LTC-BTC   (LTC/BTC)**
  therock.LTC-BTC   (LTC/BTC)

**Comment by abduegal** [comment]
Your list-selector is not returning LTC/EUR, neither does HitBTC afaik support it.

**Comment by blastbeng** [comment]
Sorry, I posted the wrong grep

$ zenbot list-selectors | grep LTC/EUR
  bitstamp.LTC-EUR   (LTC/EUR)
  btce.LTC-EUR   (LTC/EUR)
  gdax.LTC-EUR   (LTC/EUR)
  hitbtc.LTC-EUR   (LTC/EUR)
  kraken.XLTC-ZEUR   (LTC/EUR)
  therock.LTC-EUR   (LTC/EUR)

As you can see hitbtc ltc EUR is listed here

**Comment by DeviaVir** [comment]
https://api.hitbtc.com/api/2/public/symbol no LTCEUR here though, perhaps our products.json is outdated.
