### ISSUE TITLE
MIN_TRADE_REQUIREMENT_NOT_MET

### ISSUE THREAD

**Issue by kazdimenator** [DeviaVir/zenbot#741]
Error, if the order is less than 4,1 USD.

{ Error: order not found in cache
    at Object.getOrder (/home/kazdim/zenbot/extensions/exchanges/bittrex/exchange.js:268:29)
    at Timeout.checkOrder [as _onTimeout] (/home/kazdim/zenbot/lib/engine.js:283:24)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) desc: 'could not execute sell: error placing order' }

**Comment by station384** [comment]
Bittrex does not report minimum buy orders, nor minimum sell in there api thru regular means.  so it is using a default of 0.000001 so it covers all markets.   The side effect is this error when you don't meet there minimums

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
