### ISSUE TITLE
Latest update breaks trading on GDAX

### ISSUE THREAD

**Issue by mikeh21** [DeviaVir/zenbot#748]
Hi 

Latest update has broken trading at GDAX:

manual limit SELL command executed

GDAX API is down! unable to call sell, retrying in 10s
{ Error: non-200 status: 400
    at statusErr (/user/zenbot/extensions/exchanges/gdax/exchange.js:30:17)
    at /user/zenbot/extensions/exchanges/gdax/exchange.js:186:25
    at Request._callback (/user/zenbot/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/user/zenbot/node_modules/gdax/node_modules/request/request.js:187:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/user/zenbot/node_modules/gdax/node_modules/request/request.js:1044:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/user/zenbot/node_modules/gdax/node_modules/request/request.js:965:12)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'HTTP_STATUS',
  body: { message: 'price must be a number (NaN)' } }
[ { price: 'NaN',
    size: '0.01857146',
    orig_size: '0.01857146',
    remaining_size: '0.01857146',
    orig_price: 'NaN',
    cancel_after: 'day',
    product_id: 'BTC-GBP',
    post_only: true,
    time_in_force: 'GTT',
    side: 'sell' } ]

**Comment by mikeh21** [comment]
ignore, appears to be some other issue with my setup but a fresh clone has fixed
