### ISSUE TITLE
KRAKEN API returne error for a BUY or SELL

### ISSUE THREAD

**Issue by sfdu** [DeviaVir/zenbot#781]
hi,

using ZENBOT version 4.0.5  on a linux computer and I got this error during a BUY:

 Error: 
order rejected
    at /home/stephane/crypt/zenbot/lib/engine.js:240:23
    at KrakenClient.<anonymous> (/home/stephane/crypt/zenbot/extensions/exchanges/kraken/exchange.js:276:20)
    at Request._callback (/home/stephane/crypt/zenbot/node_modules/kraken-api/kraken.js:155:23)
    at Request.self.callback (/home/stephane/crypt/zenbot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/stephane/crypt/zenbot/node_modules/request/request.js:1060:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/stephane/crypt/zenbot/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  order: 
   { id: null,
     status: 'rejected',
     price: '24.42900000',
     size: '1.63285849',
     created_at: 1512222415958,
     filled_size: '0',
     post_only: true,
     reject_reason: 'Kraken API returned error: General:Invalid arguments:expiretm' },
  desc: 'could not execute buy: error placing order' }

Can't find where the problem is...

**Comment by sfdu** [comment]
after a new installation - problem solved.
