### ISSUE TITLE
GDAX (also Bittrex) error message

### ISSUE THREAD

**Issue by ether-btc** [DeviaVir/zenbot#793]
for the last weeks I ran two instances of zenbot. one gdax, one bittrex one. then I used another bittrex api key to run a third instance. went without major issues, so I then used a fourth api key to occassionally run a fourth instance of the bot.

tonight, all instances showed this code (still pulled ticks):

`fetching pre-roll data:
{ MongoError: BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO
    at Function.MongoError.create (/home/pi/zenbot/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/pi/zenbot/node_modules/mongodb/lib/utils.js:139:22)
    at /home/pi/zenbot/node_modules/mongodb/lib/collection.js:1059:60
    at getLastErrorCallback (/home/pi/zenbot/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:466:18)
    at /home/pi/zenbot/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  driver: true,
  ok: 1,
  n: 0,
  nModified: 0,
  code: 10334,
  errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  writeConcernError: 
   { code: 10334,
     errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO' },
  saved: false,
  obj: 
   { trade_id: 1052045,
     time: 1512367967053,
     size: 1.12977225,
     price: 398.2,
     side: 'sell',
     id: 'gdax.ETH-EUR-1052045',
     selector: 'gdax.ETH-EUR' } }
retrying...
{ MongoError: BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO
    at Function.MongoError.create (/home/pi/zenbot/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/pi/zenbot/node_modules/mongodb/lib/utils.js:139:22)
    at /home/pi/zenbot/node_modules/mongodb/lib/collection.js:1059:60
    at getLastErrorCallback (/home/pi/zenbot/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:466:18)
    at /home/pi/zenbot/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  driver: true,
  ok: 1,
  n: 0,
  nModified: 0,
  code: 10334,
  errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  writeConcernError: 
   { code: 10334,
     errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO' },
  saved: false,
  obj: 
   { trade_id: 1052044,
     time: 1512367592064,
     size: 0.00250503,
     price: 398.2,
     side: 'sell',
     id: 'gdax.ETH-EUR-1052044',
     selector: 'gdax.ETH-EUR' } }
retrying...
{ MongoError: BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO
    at Function.MongoError.create (/home/pi/zenbot/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/pi/zenbot/node_modules/mongodb/lib/utils.js:139:22)
    at /home/pi/zenbot/node_modules/mongodb/lib/collection.js:1059:60
    at getLastErrorCallback (/home/pi/zenbot/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:466:18)
    at /home/pi/zenbot/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  driver: true,
  ok: 1,
  n: 0,
  nModified: 0,
  code: 10334,
  errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  writeConcernError: 
   { code: 10334,
     errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO' },
  saved: false,
  obj: 
   { trade_id: 1052042,
     time: 1512366218501,
     size: 0.030342,
     price: 398.23,
     side: 'sell',
     id: 'gdax.ETH-EUR-1052042',
     selector: 'gdax.ETH-EUR' } }
retrying...
{ MongoError: BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO
    at Function.MongoError.create (/home/pi/zenbot/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/pi/zenbot/node_modules/mongodb/lib/utils.js:139:22)
    at /home/pi/zenbot/node_modules/mongodb/lib/collection.js:1059:60
    at getLastErrorCallback (/home/pi/zenbot/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:466:18)
    at /home/pi/zenbot/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  driver: true,
  ok: 1,
  n: 0,
  nModified: 0,
  code: 10334,
  errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  writeConcernError: 
   { code: 10334,
     errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO' },
  saved: false,
  obj: 
   { trade_id: 1052045,
     time: 1512367967053,
     size: 1.12977225,
     price: 398.2,
     side: 'sell',
     id: 'gdax.ETH-EUR-1052045',
     selector: 'gdax.ETH-EUR' } }
retrying...
{ MongoError: BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO
    at Function.MongoError.create (/home/pi/zenbot/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/pi/zenbot/node_modules/mongodb/lib/utils.js:139:22)
    at /home/pi/zenbot/node_modules/mongodb/lib/collection.js:1059:60
    at getLastErrorCallback (/home/pi/zenbot/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:466:18)
    at /home/pi/zenbot/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  driver: true,
  ok: 1,
  n: 0,
  nModified: 0,
  code: 10334,
  errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  writeConcernError: 
   { code: 10334,
     errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO' },
  saved: false,
  obj: 
   { trade_id: 1052045,
     time: 1512367967053,
     size: 1.12977225,
     price: 398.2,
     side: 'sell',
     id: 'gdax.ETH-EUR-1052045',
     selector: 'gdax.ETH-EUR' } }
retrying...
{ MongoError: BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO
    at Function.MongoError.create (/home/pi/zenbot/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/pi/zenbot/node_modules/mongodb/lib/utils.js:139:22)
    at /home/pi/zenbot/node_modules/mongodb/lib/collection.js:1059:60
    at getLastErrorCallback (/home/pi/zenbot/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:466:18)
    at /home/pi/zenbot/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  driver: true,
  ok: 1,
  n: 0,
  nModified: 0,
  code: 10334,
  errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO',
  writeConcernError: 
   { code: 10334,
     errmsg: 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: EOO' },
  saved: false,
  obj: 
   { trade_id: 1052045,
     time: 1512367967053,
     size: 1.12977225,
     price: 398.2,
     side: 'sell',
     id: 'gdax.ETH-EUR-1052045',
     selector: 'gdax.ETH-EUR' } }
retrying...
`

I am running the bot on a raspi3 (8gb sd-card). Is that an issue? was fine for last couple weeks. heard, a 32-bit OS is not optimal,  but installing the 64-bit one headless is not possible atm.

when I tried restarting the bot instances (Shift+X first), I got the same message as above.

**Comment by DeviaVir** [comment]
Looks like an issue with your Mongo, I'd look around there.

**Comment by nrdroque** [comment]
check the mongod status
sudo service mongodb status
if not running try to run the mongod manually

 sudo mongod

and check again the status

**Comment by ether-btc** [comment]
Thank you all for the replies! I resetup the pi and it worked.
