### ISSUE TITLE
Error when starting zenbot

### ISSUE THREAD

**Issue by jellebens** [DeviaVir/zenbot#796]
**platform**: 4.13.0-17-generic #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**npm --version**: 3.5.2

./zenbot.sh trade --paper
/home/nuc/zenbot/node_modules/ccxt/js/base/Exchange.js:309
                    let partial = async params => this[methodName] (url, type, uppercaseMethod, params || {})
                                        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nuc/zenbot/node_modules/ccxt/ccxt.js:33:19)

**Comment by MT00x** [comment]
nodejs --version ?

**Comment by jellebens** [comment]
**node version**: v6.11.4

**Comment by MT00x** [comment]
Try update nodejs to last 8.x.x

**Comment by jellebens** [comment]
yep solved! thx
