### ISSUE TITLE
mongodb not accessible error

### ISSUE THREAD

**Issue by TonyStark** [DeviaVir/zenbot#803]
$stark: zenbot trade poloniex.eth-btc
```warning: mongodb not accessible. some features (such as backfilling/simulation) may be disabled.
/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/sosa_mongo/mongo_backend.js:6
  if (!backend_options.db) throw new Error('must pass a node-mongodb-native db with backend_options.db');
                           ^

Error: must pass a node-mongodb-native db with backend_options.db
    at module.exports (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/sosa_mongo/mongo_backend.js:6:34)
    at /media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/sosa/index.js:7:17
    at createCollection (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/db/createCollection.js:5:7)
    at Object.container (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/db/sessions.js:2:36)
    at Object.getValue (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/codemap/index.js:298:22)
    at /media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/codemap/index.js:238:23
    at Array.forEach (<anonymous>)
    at Object.get (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/codemap/index.js:237:13)
    at get (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/codemap/index.js:60:22)
    at Command.<anonymous> (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/commands/trade.js:319:24)
    at Command.listener (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/commander/index.js:653:12)
    at Command.parse (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/commander/index.js:475:21)
    at /media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/zenbot.js:39:11
    at /media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/boot.js:28:7
    at f (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/zenbot/node_modules/glob/glob.js:197:8)```

**Comment by DeviaVir** [comment]
Has it worked for you before this?

**Comment by TonyStark** [comment]
@DeviaVir 
no this is first time

**Comment by DeviaVir** [comment]
Do you have mongo running?

**Comment by TonyStark** [comment]
i dont think so
by entering mongo in command line it said no command found

**Comment by DeviaVir** [comment]
zenbot requires mongodb, please install mongodb or use docker-compose.
