### ISSUE TITLE
sim crash

### ISSUE THREAD

**Issue by enstat** [DeviaVir/zenbot#813]
root@2dev:~/zenbot# ./zenbot.sh sim trend_ema gdax.BTC-EUR
/root/zenbot/node_modules/codemap/index.js:233
        throw err;
        ^

Error: path `zenbot:exchanges.trend_ema` is undefined
    at Object.get (/root/zenbot/node_modules/codemap/index.js:231:19)
    at get (/root/zenbot/node_modules/codemap/index.js:60:22)
    at /root/zenbot/lib/engine.js:19:18
    at Command.<anonymous> (/root/zenbot/commands/sim.js:78:39)
    at Command.listener (/root/zenbot/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/root/zenbot/node_modules/commander/index.js:653:12)
    at Command.parse (/root/zenbot/node_modules/commander/index.js:475:21)
    at /root/zenbot/zenbot.js:39:11
    at /root/zenbot/boot.js:28:7
    at f (/root/zenbot/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/root/zenbot/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/root/zenbot/node_modules/glob/glob.js:197:8)
    at done (/root/zenbot/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/root/zenbot/node_modules/glob/glob.js:637:12)
    at /root/zenbot/node_modules/glob/glob.js:626:10
    at RES (/root/zenbot/node_modules/inflight/inflight.js:31:16)
    at f (/root/zenbot/node_modules/once/once.js:25:25)
    at lstatcb_ (/root/zenbot/node_modules/glob/glob.js:519:7)
root@2dev:~/zenbot# 

The same with all type of strategies list.
How to fix this problem?

Zenbot Version: 4.0.5

**Comment by DeviaVir** [comment]
Please read the README to discover the right way to call `zenbot sim`.
