### ISSUE TITLE
wex.nz - buy/sell wont work - Error: You incorrectly entered one of fields

### ISSUE THREAD

**Issue by flintmcbeth** [DeviaVir/zenbot#849]
WEXNZ API is down! unable to call buy, retrying in 10s
Error: You incorrectly entered one of fields.
    at Function.WEXNZ.responseHandler (/app/node_modules/wexnz/wexnz.js:363:16)
    at IncomingMessage.<anonymous> (/app/node_modules/wexnz/wexnz.js:210:13)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[ 'buy',
  { price: '252.9290',
    size: '1.30623089',
    orig_size: '1.30623089',
    remaining_size: '1.30623089',
    orig_price: '252.9290',
    cancel_after: 'day',
    product_id: 'LTC-EUR',
    post_only: true } ]
    return (product_id.split('-')[0] + '_' + product_id.split('-')[1]).toLowerCase()
                       ^

TypeError: Cannot read property 'split' of undefined
    at joinProduct (/app/extensions/exchanges/wexnz/exchange.js:35:24)
    at Object.trade (/app/extensions/exchanges/wexnz/exchange.js:158:18)
    at Object.buy (/app/extensions/exchanges/wexnz/exchange.js:188:16)
    at Timeout._onTimeout (/app/extensions/exchanges/wexnz/exchange.js:61:24)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)

**Comment by tinhien11** [comment]
+1

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
