### ISSUE TITLE
MongoError: server instance pool was destroyed

### ISSUE THREAD

**Issue by dextervip** [DeviaVir/zenbot#856]
Hey,
I am running the bot over kraken however when the bot is going to buy/sell. I am getting this error and no effective trades. Anyone has an idea what could be happening?

```
12/13/2017 3:53:52 PM2017-12-13 17:53:52 - error saving session
12/13/2017 3:53:52 PM{ MongoError: server instance pool was destroyed
12/13/2017 3:53:52 PM    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:29:11)
12/13/2017 3:53:52 PM    at basicWriteValidations (/app/node_modules/mongodb-core/lib/topologies/server.js:462:51)
12/13/2017 3:53:52 PM    at Server.update (/app/node_modules/mongodb-core/lib/topologies/server.js:581:16)
12/13/2017 3:53:52 PM    at Server.update (/app/node_modules/mongodb/lib/server.js:397:17)
12/13/2017 3:53:52 PM    at updateDocuments (/app/node_modules/mongodb/lib/collection.js:1054:19)
12/13/2017 3:53:52 PM    at save (/app/node_modules/mongodb/lib/collection.js:1340:12)
12/13/2017 3:53:52 PM    at Collection.save (/app/node_modules/mongodb/lib/collection.js:1323:44)
12/13/2017 3:53:52 PM    at Object.save (/app/node_modules/sosa_mongo/mongo_backend.js:35:12)
12/13/2017 3:53:52 PM    at withHooks (/app/node_modules/sosa/api.js:68:15)
12/13/2017 3:53:52 PM    at Object.save (/app/node_modules/sosa/api.js:65:12)
12/13/2017 3:53:52 PM    at /app/commands/trade.js:519:24
12/13/2017 3:53:52 PM    at /app/lib/engine.js:192:14
12/13/2017 3:53:52 PM    at KrakenClient.<anonymous> (/app/extensions/exchanges/kraken/exchange.js:177:9)
12/13/2017 3:53:52 PM    at Request._callback (/app/node_modules/kraken-api/kraken.js:159:22)
12/13/2017 3:53:52 PM    at Request.self.callback (/app/node_modules/request/request.js:186:22)
12/13/2017 3:53:52 PM    at Request.emit (events.js:159:13)
12/13/2017 3:53:52 PM    at Request.<anonymous> (/app/node_modules/request/request.js:1060:10)
12/13/2017 3:53:52 PM    at Request.emit (events.js:159:13)
12/13/2017 3:53:52 PM    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:980:12)
12/13/2017 3:53:52 PM    at Object.onceWrapper (events.js:254:19)
12/13/2017 3:53:52 PM    at IncomingMessage.emit (events.js:164:20)
12/13/2017 3:53:52 PM    at endReadableNT (_stream_readable.js:1054:12)
12/13/2017 3:53:52 PM  name: 'MongoError',
12/13/2017 3:53:52 PM  message: 'server instance pool was destroyed',
12/13/2017 3:53:52 PM  saved: false,
12/13/2017 3:53:52 PM  obj:
12/13/2017 3:53:52 PM   { id: 'c7c5d731',
12/13/2017 3:53:52 PM     selector: 'kraken.XXBT-ZUSD',
12/13/2017 3:53:52 PM     started: 1513136404235,
12/13/2017 3:53:52 PM     mode: 'live',
12/13/2017 3:53:52 PM     options:
12/13/2017 3:53:52 PM      { strategy: 'trend_ema',
12/13/2017 3:53:52 PM        oversold_rsi: 40,
12/13/2017 3:53:52 PM        trend_ema: 35,
12/13/2017 3:53:52 PM        profit_stop_enable_pct: 10,
12/13/2017 3:53:52 PM        profit_stop_pct: 8,
12/13/2017 3:53:52 PM        sell_stop_pct: 0,
12/13/2017 3:53:52 PM        buy_stop_pct: 0,
12/13/2017 3:53:52 PM        max_slippage_pct: 5,
12/13/2017 3:53:52 PM        buy_pct: 99,
12/13/2017 3:53:52 PM        sell_pct: 99,
12/13/2017 3:53:52 PM        order_adjust_time: 5000,
12/13/2017 3:53:52 PM        max_sell_loss_pct: 25,
12/13/2017 3:53:52 PM        order_poll_time: 5000,
12/13/2017 3:53:52 PM        markdown_buy_pct: 0,
12/13/2017 3:53:52 PM        markup_sell_pct: 0,
12/13/2017 3:53:52 PM        order_type: 'maker',
12/13/2017 3:53:52 PM        poll_trades: 30000,
12/13/2017 3:53:52 PM        currency_capital: 1000,
12/13/2017 3:53:52 PM        asset_capital: 0,
12/13/2017 3:53:52 PM        rsi_periods: 14,
12/13/2017 3:53:52 PM        avg_slippage_pct: 0.045,
12/13/2017 3:53:52 PM        debug: undefined,
12/13/2017 3:53:52 PM        stats: true,
12/13/2017 3:53:52 PM        mode: 'live',
12/13/2017 3:53:52 PM        selector: 'kraken.XXBT-ZUSD',
12/13/2017 3:53:52 PM        period: '2m',
12/13/2017 3:53:52 PM        min_periods: 52,
12/13/2017 3:53:52 PM        neutral_rate: 'auto',
12/13/2017 3:53:52 PM        oversold_rsi_periods: 14 },
12/13/2017 3:53:52 PM     orig_capital: 134.17389365199998,
12/13/2017 3:53:52 PM     orig_price: 13905.9,
12/13/2017 3:53:52 PM     updated: 1513187632626,
12/13/2017 3:53:52 PM     balance:
12/13/2017 3:53:52 PM      { id: 'kraken.XXBT-ZUSD-15m1681319',
12/13/2017 3:53:52 PM        selector: 'kraken.XXBT-ZUSD',
12/13/2017 3:53:52 PM        time: 1513187100000,
12/13/2017 3:53:52 PM        currency: '134.14970000',
12/13/2017 3:53:52 PM        asset: '0.00000000',
12/13/2017 3:53:52 PM        price: 16411.2,
12/13/2017 3:53:52 PM        start_capital: 134.17389365199998,
12/13/2017 3:53:52 PM        start_price: 13905.9,
12/13/2017 3:53:52 PM        consolidated: 134.1497,
12/13/2017 3:53:52 PM        profit: -0.00018031564368795573,
12/13/2017 3:53:52 PM        buy_hold: 158.3467883058056,
12/13/2017 3:53:52 PM        buy_hold_profit: 0.18016093888205734,
12/13/2017 3:53:52 PM        vs_buy_hold: -0.15281072994720443 },
12/13/2017 3:53:52 PM     start_capital: 133.78277552,
12/13/2017 3:53:52 PM     start_price: 16528,
12/13/2017 3:53:52 PM     num_trades: 0,
12/13/2017 3:53:52 PM     price: 16411.2 } }
```

**Comment by LoneWolf345** [comment]
It has been quite awhile since the last comment.  Do you feel your issue is resolved?  Please consider closing it.

**Comment by DeviaVir** [comment]
Closing, it's cheap to re-open.

**Comment by a1492dc** [comment]
the having the same issue, can be reopened? specifically is happening on 2 instances:
1 binance.eth-btc
2 binance.ltc-btc

here my error:

2018-05-03 23:45:03 - error saving session
{ MongoError: server instance pool was destroyed
    at basicWriteValidations (zenbot/node_modules/mongodb-core/lib/topologies/server.js:641:41)
    at Server.update (zenbot/node_modules/mongodb-core/lib/topologies/server.js:781:16)
    at Server.update (zenbot/node_modules/mongodb/lib/topologies/topology_base.js:326:25)
    at updateDocuments (zenbot/node_modules/mongodb/lib/collection.js:1023:19)
    at save (zenbot/node_modules/mongodb/lib/collection.js:1273:12)
    at executeOperation (zenbot/node_modules/mongodb/lib/utils.js:420:24)
    at Collection.save (zenbot/node_modules/mongodb/lib/collection.js:1260:10)
    at /home/cryptowisebot/zenbot/commands/trade.js:611:22
    at /home/cryptowisebot/zenbot/lib/engine.js:240:9
    at /home/cryptowisebot/zenbot/lib/engine.js:309:7
  name: 'MongoError',
  message: 'server instance pool was destroyed' }
