### ISSUE TITLE
Zenbot tries to buy an amount lower then the Poloniex minimum allowed

### ISSUE THREAD

**Issue by denniswiemer** [DeviaVir/zenbot#919]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Zenbot version**: 4.0.5
- **NodeJS version**: 9.3.1
- **Python version**: 2.7.9
- **Exact command to reproduce**:"poloniex.XRP-USDT --strategy=trust_distrust --period=40m --min_periods=100 --sell_threshold=4 --sell_threshold_max=0 --reset_profit"

### Describe the problem
When running the bot on Poloniex (XRP/USDT) it creates an error when trying to buy an amount of XRP which is lower then the allowed minimum on Poloniex. How can I solve this? Is it a configuration thing or a bug? Maybe make this minimum amount configurable?
My config buy_pct & sell_pct are 99

### Source code / logs
The error:
`{ Error: unable to buy
    at /bot/node_modules/zenbot4/extensions/exchanges/poloniex/exchange.js:197:17
    at Request._callback (/bot/node_modules/poloniex.js/lib/poloniex.js:79:7)
    at Request.self.callback (/bot/node_modules/poloniex.js/node_modules/request/request.js:122:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/bot/node_modules/poloniex.js/node_modules/request/request.js:888:14)
    at Request.emit (events.js:164:20)
    at IncomingMessage.<anonymous> (/bot/node_modules/poloniex.js/node_modules/request/request.js:839:12)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  body: { error: 'Total must be at least 0.5.' },
  desc: 'could not execute buy: error placing order' }`

**Comment by DeviaVir** [comment]
Looking at the `update-products.sh` of poloniex I think we don't get this information from them:
https://github.com/carlos8f/zenbot/blob/master/extensions/exchanges/poloniex/update-products.sh#L27

So we'd have to manually update `products.json` for XRP's `min_total` to `0.5`.

Do note that then no trades would happen.

**Comment by denniswiemer** [comment]
Think so too, I've tried the currencies api call on Poloniex but didn't found any minimum in there.

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#40
