### ISSUE TITLE
Api order status error causes crash (on CEXio)

### ISSUE THREAD

**Issue by albabosh** [DeviaVir/zenbot#947]
PgetOrder error: Invalid Order ID
/home/tradeops/zenbot/lib/engine.js:298
              order.status = api_order.status
                                       ^
TypeError: Cannot read property 'status' of undefined
    at /home/tradeops/zenbot/lib/engine.js:298:40
    at /home/tradeops/zenbot/extensions/exchanges/cexio/exchange.js:181:9
    at Request.request [as _callback] (/home/tradeops/zenbot/node_modules/cexio-api-node/rest.js:72:16)
    at Request.self.callback (/home/tradeops/zenbot/node_modules/cexio-api-node/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/tradeops/zenbot/node_modules/cexio-api-node/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/tradeops/zenbot/node_modules/cexio-api-node/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9
------------------------

### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:
- **OS Platform and Distribution : Ubuntu 16.04
- **Zenbot version**: latest
- **NodeJS version**: 8.9.1
- **Python version**:
- **Exact command to reproduce**: any trading on cexio

Exchange API responce seems to be not always correct. A patch is welcome whitch will prevent bot from crash in case of incorrect api responce

**Comment by McClean** [comment]
I had the same issue, apparently(in my case at least) it's caused when you activate 2FA before activating the API. Try disabling 2FA then activate the API key and try again(don't forget to reactivate 2FA when you're done). That was the solution given to me by CEX support and it fixed all my CEX API issues

**Comment by albabosh** [comment]
No, this is not the case, my api key is already activated.

**Comment by nedievas** [comment]
Pushed PR #956 which fixes #931

**Comment by nedievas** [comment]
Looks so nice and stable after PR.
![capture](https://user-images.githubusercontent.com/6176288/34240049-2fe736a6-e614-11e7-94e8-e20f417dffd8.PNG)
