### ISSUE TITLE
Zenbot - Binance (TIMEOUT)

### ISSUE THREAD

**Issue by masonmatthewhauk** [DeviaVir/zenbot#975]
Hi,

> _./zenbot.sh trade binance.BTC-USDT_
`node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:635:30
fetching pre-roll data:
api running on :20054/trades
Fri, 22 Dec 2017 15:15:48 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:635:30
An error occurred { Error: binance GET https://api.binance.com/api/v1/aggTrades?symbol=BTCUSDT&startTime=1513869349026&endTime=1513912549026 request timed out (10000 ms)
    at timeout.catch.e (/zenbot/node_modules/ccxt/js/base/Exchange.js:277:27)
    at <anonymous> constructor: [Function: RequestTimeout] }
`
**This happens also with** 

> `**./zenbot.sh trade binance.BTC-USDT --strategy=neural --period=5s  --momentum=0 --max_sell_loss_pct=3 --poll_trades=3000 --order_poll_time=1500 --order_adjust_time=1500**`

`node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:635:30
fetching pre-roll data:
api running on :20042/trades
Fri, 22 Dec 2017 14:57:48 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:635:30
An error occurred { Error: binance GET https://api.binance.com/api/v1/aggTrades?symbol=BTCUSDT&startTime=1513868269530&endTime=1513911469530 request timed out (10000 ms)
    at timeout.catch.e (/zenbot/node_modules/ccxt/js/base/Exchange.js:277:27)
    at <anonymous> constructor: [Function: RequestTimeout] }
`
`**https://api.binance.com/api/v1/aggTrades?symbol=BTCUSDT&startTime=1513868269530&endTime=1513911469530**`
is accessable from web browser so, I was suggested to write an issue. 
This is a **Fresh Install** of Zenbot done this morning at 7:15 DECEMBER - 22 - 2017
Anyways, thanks for all your help, in advance and Merry Christmas and Happy Holidays !!

Mason

**Comment by masonmatthewhauk** [comment]
Fixed... node_modules/ccxt/js/base/Exchange.js (        this.timeout          = 1000000000 // milliseconds    )
-Thanks Tangy !

Mason
