### ISSUE TITLE
Property 'exchange_id' undefined

### ISSUE THREAD

**Issue by tbressers** [DeviaVir/zenbot#981]
Anyone else who gets the following errors after a fresh install using the latest master branch? This did work on a previous version (using the same conf.js). The used exchange/product is GDAX.LTC-BTC -->

osmc@osmc:~/zenbot_new$ zenbot balance
/home/osmc/zenbot_new/lib/engine.js:17
    s.exchange = get('exchanges.' + so.selector.**_exchange_id_**)

TypeError: Cannot read property 'exchange_id' of undefined
    at /home/osmc/zenbot_new/lib/engine.js:17:49
    at Command.<anonymous> (/home/osmc/zenbot_new/commands/balance.js:33:39)
    at Command.listener (/home/osmc/zenbot_new/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:159:13)
    at Command.parseArgs (/home/osmc/zenbot_new/node_modules/commander/index.js:653:12)
    at Command.parse (/home/osmc/zenbot_new/node_modules/commander/index.js:475:21)
    at /home/osmc/zenbot_new/zenbot.js:39:11
    at /home/osmc/zenbot_new/boot.js:24:7
    at f (/home/osmc/zenbot_new/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/osmc/zenbot_new/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:159:13)
    at Glob._finish (/home/osmc/zenbot_new/node_modules/glob/glob.js:197:8)
    at done (/home/osmc/zenbot_new/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/home/osmc/zenbot_new/node_modules/glob/glob.js:637:12)
    at /home/osmc/zenbot_new/node_modules/glob/glob.js:626:10
    at RES (/home/osmc/zenbot_new/node_modules/inflight/inflight.js:31:16)
    at f (/home/osmc/zenbot_new/node_modules/once/once.js:25:25)
    at lstatcb_ (/home/osmc/zenbot_new/node_modules/glob/glob.js:519:7)
    at RES (/home/osmc/zenbot_new/node_modules/inflight/inflight.js:31:16)
    at f (/home/osmc/zenbot_new/node_modules/once/once.js:25:25)
    at FSReqWrap.oncomplete (fs.js:167:5)

**Comment by haxwell** [comment]
Duplicate.. see issue #938, and PR #978 .

**Comment by nedievas** [comment]
Please fix it.
```
[test@nedievas zenbot]$ git pull
Already up-to-date.
[test@nedievas zenbot]$ ./zenbot.sh trade bitfinex.btc-usd
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:635:30
/home/test/zenbot/node_modules/codemap/index.js:233
        throw err;
        ^

Error: path `zenbot:exchanges.undefined` is undefined
    at Object.get (/home/test/zenbot/node_modules/codemap/index.js:231:19)
    at get (/home/test/zenbot/node_modules/codemap/index.js:60:22)
    at /home/test/zenbot/lib/engine.js:17:18
    at Command.<anonymous> (/home/test/zenbot/commands/trade.js:75:39)
    at Command.listener (/home/test/zenbot/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/home/test/zenbot/node_modules/commander/index.js:653:12)
    at Command.parse (/home/test/zenbot/node_modules/commander/index.js:475:21)
    at /home/test/zenbot/zenbot.js:39:11
    at /home/test/zenbot/boot.js:24:7
    at f (/home/test/zenbot/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/test/zenbot/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/home/test/zenbot/node_modules/glob/glob.js:197:8)
    at done (/home/test/zenbot/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/home/test/zenbot/node_modules/glob/glob.js:637:12)
    at /home/test/zenbot/node_modules/glob/glob.js:626:10
    at RES (/home/test/zenbot/node_modules/inflight/inflight.js:31:16)
    at f (/home/test/zenbot/node_modules/once/once.js:25:25)
    at lstatcb_ (/home/test/zenbot/node_modules/glob/glob.js:519:7)
```

**Comment by haxwell** [comment]
On the latest master, I do not get this error.

```
jjames@johnathan-HPPAV02 ~/src/zenbot $ git remote -v
origin	https://github.com/haxwell/zenbot.git (fetch)
origin	https://github.com/haxwell/zenbot.git (push)
upstream	https://github.com/carlos8f/zenbot.git (fetch)
upstream	https://github.com/carlos8f/zenbot.git (push)
jjames@johnathan-HPPAV02 ~/src/zenbot $ 
jjames@johnathan-HPPAV02 ~/src/zenbot $ /usr/bin/git fetch upstream
jjames@johnathan-HPPAV02 ~/src/zenbot $ 
jjames@johnathan-HPPAV02 ~/src/zenbot $ git merge upstream/master
Already up-to-date.
jjames@johnathan-HPPAV02 ~/src/zenbot $ ./zenbot.sh trade bitfinex.btc-usd
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:635:30
emitting: command:trade
fetching pre-roll data:
api running on 172.16.37.32:20049/trades
Wed, 27 Dec 2017 23:22:56 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:635:30

bitfinex.BTC-USD saved 1000 trades 1 days left
....^C
jjames@johnathan-HPPAV02 ~/src/zenbot $ ^C
jjames@johnathan-HPPAV02 ~/src/zenbot $ 
```

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#14
