### ISSUE TITLE
How to use genetic_algo without docker ?

### ISSUE THREAD

**Issue by albabosh** [DeviaVir/zenbot#989]
How to use genetic_algo without docker ?

**Comment by DeviaVir** [comment]
This issue was moved to highvelocityspace/zenbot#13

**Comment by yang2lalang** [comment]
Look into the Dockerfile and see all the dependencies of the python script

follow the sequence enumerated in the Dockerfile file to install python 3.6 and all these dependencies needed for python 3.6

run fabfile.py to backfill but note that this uses the same backfill of zenbot in mongodb

then call main.py as described by the author

Caveat: This process could result in clashing python dependencies in ubuntu and possibly broken packages if you install python 3.6 dependencies it could remove some python 3.5 dependencies leading to a big mess

A solution is to perform the install in a virtual environment for python before starting this journey. Search google for python virtual enviroments

And of course, you can report your experiences

**Comment by kbfifi** [comment]
Hi I think I managed to get this installed under bash Ubuntu shell in Windows 10. I followed the steps of the README and running it results in:

> python -m scoop main.py BTC-CUR 3
[2018-01-20 15:03:42,581] launcher  INFO    SCOOP 0.7 1.1 on linux2 using Python 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4], API: 1013
[2018-01-20 15:03:42,582] launcher  INFO    Deploying 4 worker(s) over 1 host(s).
[2018-01-20 15:03:42,582] launcher  INFO    Worker distribution:
[2018-01-20 15:03:42,583] launcher  INFO       127.0.0.1:       3 + origin
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "main.py", line 32
    print(colored(f"Mating function is ", 'blue') + colored(Andividual.mate, 'green'))
                                       ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "main.py", line 32
    print(colored(f"Mating function is ", 'blue') + colored(Andividual.mate, 'green'))
                                       ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "main.py", line 32
    print(colored(f"Mating function is ", 'blue') + colored(Andividual.mate, 'green'))
                                       ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "main.py", line 32
    print(colored(f"Mating function is ", 'blue') + colored(Andividual.mate, 'green'))
                                       ^
SyntaxError: invalid syntax
[2018-01-20 15:03:43,505] launcher  (127.0.0.1:58374) INFO    Root process is done.
[2018-01-20 15:03:43,508] launcher  (127.0.0.1:58374) INFO    Finished cleaning spawned subprocesses.

Any hints?

**Comment by DeviaVir** [comment]
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖
