### ISSUE TITLE
Error: Cannot find module 'zenbrain'

### ISSUE THREAD

**Issue by daedalus** [DeviaVir/zenbot#99]
$ ./run.sh 
module.js:327
    throw err;
    ^

Error: Cannot find module 'zenbrain'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/dclavijo/code/BTC/zenbot/zenbot:4:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by tregismoreira** [comment]
I had the same issue and fixed just by running `npm install zenbrain`.

**Comment by daedalus** [comment]
thank you
